# -*- coding: utf-8 -*-
"""Guide BSE Medical System — textes ALLEMANDS.

   Meme jeu de cles que guide-fr.py, qui est la reference.
   Le balisage <b>, <br/> et <font> doit etre conserve tel quel.
"""
TEXTES = {
    "m07": "ganz unten: links die <b>Sprachauswahl</b>, rechts die Links zu <b>Bravo Sierra Events</b> &mdash; Website, Discord, Instagram, YouTube und Facebook.",
    "m01": "Rumpf",
    "m02": "SCHUTZ",
    "m03": "BEFUND",
    "m04": "Titel",
    "m05": "Schutz",
    "m06": "Befund",
    "chapitre_apres": "",
    "chapitre": "KAPITEL",
    "g001": "<font size=\"7\" color=\"#8a8a84\">TRIAGE-BLATT</font>",
    "g002": "<font size=\"8\" color=\"white\"><b> KRITISCH </b></font>",
    "g003": "INNERE BLUTUNG",
    "g004": "GETROFFENER BEREICH",
    "g005": "Ballistische Platten getragen: NEIN",
    "g006": "Durchdringende Bauchverletzung mit<br/>starker innerer Blutung.",
    "g007": "BEHANDLUNGSPROTOKOLL",
    "g008": "Verband + Blutbeutel<br/>+ Adrenalin",
    "g009": "BSE MEDICAL SYSTEM  //  BEDIENUNGSANLEITUNG",
    "g010": "Bravo Sierra Events",
    "g011": "BSE MEDICAL SYSTEM",
    "g012": "FRONTLINE  //  FIELD APPLICATION",
    "g013": "<font color=\"white\" size=\"15\"><b>Bedienungsanleitung</b></font>",
    "g014": "<font color=\"#9b9b96\" size=\"10.5\">Um die App kennenzulernen, ganz ohne Vorwissen</font>",
    "g015": "<font color=\"#c49708\" size=\"9\">https://project-bsm-7d32c.web.app</font>",
    "g016": "Wozu diese App dient",
    "g017": "Die App auf dem Telefon einrichten",
    "g018": "Ihre erste Beurteilung",
    "g019": "Ein Triage-Blatt lesen",
    "g020": "Die Schweregrade",
    "g021": "Die Spielmodi",
    "g022": "Der Extrem-Modus im Detail",
    "g023": "Die Einstellungen",
    "g024": "Eigene Kartendecks bauen",
    "g025": "Zu mehreren spielen: der Organisator",
    "g026": "Zu mehreren spielen: der Spieler",
    "g027": "Das HQ, Reiter für Reiter",
    "g028": "Im Gelände: praktische Hinweise",
    "g029": "Wenn etwas nicht klappt",
    "g030": "An wen sich diese Anleitung richtet",
    "g031": "Sie haben die App noch nie geöffnet? Dann sind Sie genau richtig. Diese Anleitung fängt bei null an und setzt keinerlei Vorkenntnisse voraus, weder im Airsoft-Sanitätsspiel noch am Computer. Lesen Sie die Kapitel 1 bis 5, um noch heute Nachmittag zu spielen; der Rest hilft Ihnen, wenn Sie selbst ein Spiel leiten wollen.",
    "g032": "Wozu diese App dient",
    "g033": "BSE Medical System ersetzt das Papierkartenspiel, das Airsoft-Sanitäter in der Tasche mit sich herumtragen. Wird ein Spieler getroffen, zieht der Sanitäter sein Telefon heraus, drückt einen Knopf, und die App zieht eine zufällige Verletzung samt passendem Behandlungsprotokoll.",
    "g034": "Schluss mit nassen, verlorenen oder durcheinandergeratenen Karten. Und vor allem: der Organisator kann aus der Ferne bestimmen, was jedes Team zieht.",
    "g035": "Das Prinzip in vier Schritten",
    "g036": "Ein Spieler wird getroffen",
    "g037": "Er geht zu Boden und ruft einen Sanitäter.",
    "g038": "Der Sanitäter kommt und öffnet die App",
    "g039": "Er drückt den großen runden Knopf in der Bildschirmmitte.",
    "g040": "Die App zieht eine Verletzung",
    "g041": "Ein Blatt erscheint: der getroffene Bereich, der Schweregrad und die anzuwendende Behandlung.",
    "g042": "Der Sanitäter wendet das Protokoll an",
    "g043": "Tourniquet, Verband, Schiene... je nach Blatt. Danach geht der Verwundete zurück ins Spiel.",
    "g044": "Das Material bleibt echt",
    "g045": "Die App ersetzt Ihre Sanitätstasche nicht. Sie sagt Ihnen, <b>was zu tun ist</b>; das echte Dummy-Tourniquet und den echten Verband müssen Sie selbst anlegen. Ist eine Behandlungsart auf der Veranstaltung nicht verfügbar &mdash; niemand hat einen dreiseitigen Verband, zum Beispiel &mdash; nimmt der Organisator sie <b>vor</b> dem Spiel aus dem Spiel, und die Verletzungen, die sie verlangen, kommen nicht mehr vor.",
    "g046": "Die App auf dem Telefon einrichten",
    "g047": "Es gibt nichts aus einem App-Store herunterzuladen. Alles läuft über Ihren gewohnten Browser.",
    "g048": "Öffnen Sie die Adresse im Browser",
    "g049": "<b>https://project-bsm-7d32c.web.app</b> &mdash; Chrome auf Android, Safari auf dem iPhone.",
    "g050": "Legen Sie die App auf den Startbildschirm",
    "g051": "Auf <b>Android</b>: Menü „drei Punkte“, dann „App installieren“ oder „Zum Startbildschirm hinzufügen“.<br/>Auf dem <b>iPhone</b>: Teilen-Knopf (das Quadrat mit dem Pfeil), dann „Zum Home-Bildschirm“.",
    "g052": "Starten Sie sie über das Symbol",
    "g053": "Ein goldenes Sanitätskreuz auf schwarzem Grund erscheint bei Ihren anderen Apps. Sie öffnet sich im Vollbild, ohne Adressleiste.",
    "g054": "Beim Briefing erledigen, nicht im Gelände",
    "g055": "Jedes Telefon muss die App <b>einmal mit Netz</b> öffnen. Die App legt sich dann vollständig auf dem Gerät ab.",
    "g056": "Ist dieses erste Öffnen erledigt, funktioniert sie <b>ganz ohne Netz</b>: Sie können mitten im Wald im Flugmodus Verletzungen ziehen. Nur das Spiel zu mehreren braucht eine Verbindung.",
    "g057": "Was Sie beim Start sehen",
    "g058": "Der Startbildschirm heißt <b>MEDIZINISCHE BEURTEILUNG</b>. Darauf finden Sie:",
    "g059": "einen oder mehrere <b>große runde Knöpfe</b> in der Mitte: das sind Ihre verfügbaren Züge;",
    "g060": "unten ein Band <b>AKTIVES DECK</b>, das anzeigt, wie viele Karten im Spiel sind;",
    "g061": "oben rechts drei Knöpfe: <b>Mehrspieler</b>, <b>meine Decks</b> und <b>Einstellungen</b>;",
    "g062": "oben ein graues Band mit Ihrem Spielernamen und Ihrem Team.",
    "g063": "Ihre erste Beurteilung",
    "g064": "Das ist die Hauptfunktion der App, und die einfachste.",
    "g065": "Drücken Sie den runden Knopf",
    "g066": "Der häufigste heißt <b>BALLISTIK</b>: eine Schussverletzung.",
    "g067": "Warten Sie die Analyse ab",
    "g068": "Eine <b>MARCH</b>-Beurteilung läuft einige Sekunden durch. Das ist die Diagnosezeit; nutzen Sie sie, um den Verwundeten anzusehen.",
    "g069": "Lesen Sie das Blatt",
    "g070": "Es nennt den Schweregrad, den getroffenen Bereich und das anzuwendende Protokoll.",
    "g071": "Behandeln Sie, dann drücken Sie „Neue Beurteilung“",
    "g072": "Sie kehren zum Startbildschirm zurück, bereit für den nächsten Verwundeten.",
    "g073": "Was bedeutet MARCH?",
    "g074": "Es ist die Reihenfolge, in der ein Ersthelfer einen Verwundeten untersucht, vom Tödlichsten zum am wenigsten Dringenden. Die App zeigt sie an, um Sie in Stimmung zu bringen:",
    "g075": "<b>Massive bleeding</b> &mdash; zuerst die massiven Blutungen",
    "g076": "<b>Airways</b> &mdash; die Atemwege",
    "g077": "<b>Respiration</b> &mdash; die Atmung",
    "g078": "<b>Circulation</b> &mdash; Puls und Schock",
    "g079": "<b>Head / Hypothermia</b> &mdash; der Kopf und das Auskühlen",
    "g080": "Der Bildschirm bleibt an",
    "g081": "Solange ein Blatt angezeigt wird, sperrt sich das Telefon nicht. Sie können es ablegen, um mit beiden Händen zu arbeiten: das Protokoll ist noch da, wenn Sie es wieder aufnehmen.",
    "g082": "Ein Triage-Blatt lesen",
    "g083": "Alle Blätter sind gleich aufgebaut. So sieht ein vollständiges Blatt aus:",
    "g084": "Jeder Teil, einer nach dem anderen",
    "g085": "Bereich des Blattes",
    "g086": "Was das bedeutet",
    "g087": "<b>Schweregrad-Abzeichen</b>",
    "g088": "Oben rechts, farbig. Es zeigt auf einen Blick, wie dringend die Lage ist. Der Streifen am oberen Rand des Blattes hat dieselbe Farbe.",
    "g089": "Der kurze Name der Verletzung, in großer Schrift.",
    "g090": "<b>Getroffener Bereich</b>",
    "g091": "Wo der Verwundete getroffen ist: Kopf, Rumpf, linker Arm, rechtes Bein...",
    "g092": "Erscheint nur im Extrem-Modus. Erinnert daran, ob der Verwundete Helm oder Platten trug.",
    "g093": "Die Beschreibung der Verletzung, dem Verwundeten laut vorzulesen, für das Rollenspiel.",
    "g094": "<b>Behandlungsprotokoll</b>",
    "g095": "<b>Der wichtigste Teil</b>: genau das, was Sie tun müssen.",
    "g096": "Achtung auf den Countdown",
    "g097": "Hat der Organisator die Hardcore-Option aktiviert, lösen manche Verletzungen einen <b>regelmäßigen Piepton</b> und ein rotes Band <b>AKTIVE BLUTUNG</b> aus.",
    "g098": "Sie haben dann begrenzte Zeit, um zu behandeln und <b>BEHANDLUNG ERFOLGT</b> zu drücken. Läuft die Zeit ab, stirbt der Verwundete: der Bildschirm wird schwarz und der Piepton wird zum Dauerton.",
    "g099": "Die Schweregrade",
    "g100": "Fünf Stufen, immer dieselben, mit einem Farbcode, der in der ganzen App gleich bleibt.",
    "g101": "Schweregrad",
    "g102": "Was das für den Sanitäter bedeutet",
    "g103": "TOD",
    "g104": "Nichts zu tun. Der Spieler ist tot und geht zum Wiedereinstiegspunkt zurück.",
    "g105": "Lebensbedrohlich. Bei diesen Verletzungen startet der Countdown, wenn die Option aktiv ist.",
    "g106": "Ernst, aber stabil. Nehmen Sie sich die Zeit, das Protokoll sauber anzuwenden.",
    "g107": "LEICHT",
    "g108": "Kleinkram. Ein Verband und der Spieler ist wieder im Spiel.",
    "g109": "SPEZIAL",
    "g110": "Ein Sonderfall, meist an eine Schutzausrüstung gebunden. Lesen Sie das Protokoll genau: es hängt davon ab, ob Helm oder Weste getragen wurden.",
    "g111": "Warum manche Verletzungen häufiger kommen",
    "g112": "Jede Karte hat eine <b>Menge</b>, so als lägen mehrere Exemplare derselben Karte im Deck. Eine Karte mit 4 Exemplaren kommt doppelt so oft wie eine mit 2. Der Organisator stellt diese Mengen ein, um seinem Spiel den Ton zu geben: mehr Kleinkram oder mehr lebensbedrohliche Notfälle.",
    "g113": "Die Spielmodi",
    "g114": "Der Modus bestimmt, welches Kartendeck benutzt wird. Man wählt ihn in den <b>Einstellungen</b>, oder der Organisator gibt ihn im Spiel vor.",
    "g115": "Für Anfänger. Einfache Behandlung: Tourniquet, Verband, Schiene. Ideal für ein erstes Spiel.",
    "g116": "<b>Fortgeschritten</b>",
    "g117": "Für Erfahrene. Längere Protokolle, Morphin und Adrenalin kommen ins Spiel.",
    "g118": "<b>Extrem</b>",
    "g119": "Am realistischsten. Sie zeigen den getroffenen Bereich auf einer Silhouette an, und die Verletzungen ergeben sich daraus. Siehe nächstes Kapitel.",
    "g120": "Ein <b>zusätzliches</b> Deck für Granaten und Sprengstoff. Es fügt einen zweiten runden Knopf auf dem Startbildschirm hinzu.",
    "g121": "Der Sonderfall Explosion",
    "g122": "Das Explosions-Deck enthält die Verletzungen durch Druckwelle und Splitter. Es wird in den Einstellungen aktiviert, im Modus Fortgeschritten oder Extrem, und lässt einen orangefarbenen Knopf <b>EXPLOSION</b> neben dem Ballistik-Knopf erscheinen.",
    "g123": "Eine Explosion achtet nicht auf Schutzausrüstung",
    "g124": "Das ist Absicht: anders als Schussverletzungen kann eine Explosionskarte einen Spieler töten, <b>selbst wenn er Helm und Platten trägt</b>. Eine Druckwelle geht hindurch. Suchen Sie keinen Fehler &mdash; das ist die Regel.",
    "g125": "Der Extrem-Modus im Detail",
    "g126": "Das ist der eindringlichste Modus und der einzige, in dem <b>Sie</b> den getroffenen Bereich bestimmen, statt ihn dem Zufall zu überlassen.",
    "g127": "Drücken Sie den Zug-Knopf",
    "g128": "Statt des Blattes erscheint eine <b>menschliche Silhouette</b>.",
    "g129": "Tippen Sie den getroffenen Bereich an",
    "g130": "Kopf, Rumpf, Arm oder Bein. <b>Die Ansicht ist gespiegelt</b>: der rechte Arm des Verwundeten liegt auf dem Bildschirm links von Ihnen, so als stünden Sie ihm gegenüber.",
    "g131": "Beantworten Sie die Schutzfrage",
    "g132": "Für den Kopf: „Ballistischer Helm getragen?“. Für den Rumpf: „Schutzweste getragen?“. Sehen Sie den Verwundeten an und antworten Sie ehrlich.",
    "g133": "Das Blatt erscheint",
    "g134": "Es enthält nur Verletzungen, die zum Bereich <b>und</b> zu Ihrer Antwort passen.",
    "g135": "Warum die Schutzfrage alles verändert",
    "g136": "Die Antwort filtert die verfügbaren Karten wirklich. Ein behelmter Spieler kann nicht „Direkter Schuss in den Kopf (ohne Helm)“ ziehen:",
    "g137": "Getroffener Bereich",
    "g138": "Schutz getragen",
    "g139": "Ohne Schutz",
    "g140": "<b>Kopf</b>",
    "g141": "Treffer auf den Helm<br/><font size='8' color='#5d5d58'>2 Minuten Ruhe</font>",
    "g142": "Stirnwunde, Schädel-Hirn-Trauma, <b>oder tödlicher Schuss</b>",
    "g143": "Treffer auf die Platte, Schürfwunde an der Flanke, Rippenbrüche",
    "g144": "Pneumothorax, innere Blutung, <b>oder tödlicher Schuss</b>",
    "g145": "<b>Arm / Bein</b>",
    "g146": "<font color='#5d5d58'>Frage wird nicht gestellt</font>",
    "g147": "Verletzungen, die zur Gliedmaße passen: eine Oberschenkelfraktur kann nicht an einem Arm auftreten.",
    "g148": "Die Moral des Extrem-Modus",
    "g149": "Helm und Platten zu tragen rettet Ihnen in diesem Modus wirklich das Leben. Das ist das beste Argument, um Ihre Spieler zu ordentlicher Ausrüstung zu bewegen.",
    "g150": "Die Einstellungen",
    "g151": "Sie erreichen sie über den <b>Regler</b>-Knopf oben rechts auf dem Bildschirm. Denken Sie daran, unten <b>BESTÄTIGEN</b> zu drücken, um Ihre Änderungen zu behalten; <b>ABBRECHEN</b> setzt alles zurück.",
    "g152": "Mehrspieler-Profil",
    "g153": "Ihr <b>Spielername</b>. Unter diesem Namen sieht Sie der Organisator. Setzen Sie ihn, bevor Sie einem Spiel beitreten: das ist für alle einfacher.",
    "g154": "Klassisch, Fortgeschritten, Extrem oder eines Ihrer eigenen Decks. Im Spiel ist diese Einstellung gesperrt: der Organisator entscheidet.",
    "g155": "Hardcore-Option: das Todesrisiko",
    "g156": "Einmal angehakt, erscheinen vier Einstellungen:",
    "g157": "Einstellung",
    "g158": "<b>Wahrscheinlichkeit</b>",
    "g159": "Die Chance, dass eine Verletzung den Countdown auslöst. 40% als Standard: ungefähr jede zweite kritische Verletzung.",
    "g160": "<b>Mindestzeit</b>",
    "g161": "Die kürzeste Zeit, die der Sanitäter hat. 30 Sekunden als Standard.",
    "g162": "<b>Höchstzeit</b>",
    "g163": "Die längste Zeit. 60 Sekunden als Standard. Die tatsächliche Zeit wird zufällig zwischen beiden gezogen, und der Sanitäter sieht sie nicht.",
    "g164": "<b>Auf Schwere ausweiten</b>",
    "g165": "Standardmäßig können nur kritische Verletzungen töten. Haken Sie das an, um das Spiel deutlich zu verschärfen.",
    "g166": "Benötigtes Material",
    "g167": "Diese Liste verfolgt nicht den Inhalt Ihrer Tasche im Lauf des Spiels. Sie legt fest, <b>welche Behandlungsarten im Spiel sind</b>: man hakt das Material ab, das man nicht hat, und die App zieht die Verletzungen nicht mehr, die es verlangen.",
    "g168": "Es ist eine Einstellung der <b>Vorbereitung</b>, keine im Gelände: sie wird vor dem Spiel gemacht, und normalerweise vom Organisator.",
    "g169": "Ein Spieler nimmt keine Karten aus dem Spiel",
    "g170": "Im Spiel sind Ihre Einstellungen <b>gesperrt</b>: der Organisator entscheidet über Material und Mengen, damit alle Sanitäter dasselbe Deck spielen. Sie können eine Verletzung also nicht aussortieren, weil sie Ihnen gerade nicht passt.",
    "g171": "Im Solospiel dagegen richten Sie Ihr eigenes Spiel frei ein.",
    "g172": "<b>Beispiel.</b> Kein Sanitäter der Veranstaltung hat einen dreiseitigen Verband? Der Organisator hakt dieses Material vor dem Spiel ab: der offene Pneumothorax und der Pneumothorax verschwinden für alle aus dem Deck.",
    "g173": "Aktive Karten",
    "g174": "Die vollständige Liste der Verletzungen des Modus, <b>nach Schweregrad sortiert</b>: Tod zuerst, dann kritisch, schwer, leicht und speziell. Für jede Karte:",
    "g175": "das Auge öffnet den <b>Katalog</b> und zeigt Ihnen die ganze Karte;",
    "g176": "die Knöpfe <b>&ndash;</b> und <b>+</b> stellen ihre Menge im Deck ein;",
    "g177": "der <b>Prozentwert</b> rechts nennt ihre Chance zu erscheinen. Er aktualisiert sich von selbst;",
    "g178": "eine <b>ausgegraute</b> Zeile heißt, dass das Material fehlt: diese Karte wird nicht gezogen.",
    "g179": "Eine Karte auf null stellen",
    "g180": "Die Menge auf 0 zu setzen nimmt die Karte ganz aus dem Deck. Das ist der saubere Weg, eine Verletzung auszusortieren, die Ihnen nicht gefällt, ohne am Rest zu rühren.",
    "g181": "Eigene Kartendecks bauen",
    "g182": "Der <b>Stift</b>-Knopf oben rechts öffnet „Meine Decks“. Dort können Sie eigene Verletzungen bauen: chemische Verseuchung, Strahlung, Bisse, was Ihr Szenario verlangt.",
    "g183": "Ein Deck erstellen",
    "g184": "Geben Sie ihm einen Namen. Haken Sie <b>Auf dem Startbildschirm zeigen</b> an, damit es einen eigenen runden Knopf bekommt.",
    "g185": "Karten hinzufügen",
    "g186": "Für jede: ein Schweregrad, ein Titel, ein Bereich, ein Behandlungsprotokoll.",
    "g187": "Das benötigte Material wählen",
    "g188": "Tippen Sie die passenden Chips an. Sie können Material anlegen, das in der Grundliste nicht existiert &mdash; „Anti-Rad“, „Serum“...",
    "g189": "Das Symbol der Schaltfläche wählen",
    "g190": "Rund dreißig Piktogramme zur Auswahl: Kugel, Granate, Explosion, Biogefährdung, Strahlung, Zombie, Kreatur, Roboter, Spritze, Tabletten, Infusion... Es kennzeichnet das Deck auf dem Startbildschirm und begleitet es, wenn Sie es teilen oder im Spiel zuweisen.",
    "g191": "Das Deck erscheint auf Ihrem Startbildschirm, einsatzbereit.",
    "g192": "Ein Deck mit jemandem teilen",
    "g193": "Der <b>Teilen</b>-Knopf auf einer Deck-Karte erzeugt einen langen Code, der mit <b>TMDECK1</b> beginnt. Schicken Sie ihn per SMS oder Messenger; der Empfänger nutzt <b>Deck importieren</b> und fügt den Code ein. Er bekommt alle Karten und das zugehörige Material.",
    "g194": "Die Option „Extrem-Modus“ des Decks",
    "g195": "Angehakt löst auch Ihr eigenes Deck die Silhouette und die Schutzfrage aus, genau wie der offizielle Extrem-Modus.",
    "g196": "Während eines Spiels werden Ihre Decks beiseitegelegt",
    "g197": "Wenn Sie einem Spiel beitreten, gibt der Organisator seine Konfiguration vor: Ihre eigenen Decks verschwinden vorübergehend und das Erstellen ist gesperrt. <b>Sie bekommen sie vollständig zurück, sobald Sie das Spiel verlassen.</b> Nichts geht verloren.",
    "g198": "Zu mehreren spielen: der Organisator",
    "g199": "Der Organisator erstellt das Spiel und steuert, was jeder Spieler zieht. Der <b>Mehrspieler</b>-Knopf ist oben rechts.",
    "g200": "Öffnen Sie das Mehrspieler-Menü",
    "g201": "Der erste Knopf oben rechts, mit den zwei Silhouetten.",
    "g202": "Geben Sie dem Spiel einen Namen",
    "g203": "Zum Beispiel „Übung Alpha“. Diesen Namen tippen Ihre Spieler ein, um zu Ihnen zu stoßen.",
    "g204": "Geben Sie Ihren Spielernamen an",
    "g205": "Der Name, unter dem Sie erscheinen.",
    "g206": "Lassen Sie die Verbindung auf „Firebase-Server“",
    "g207": "Das ist die empfohlene Einstellung. Sie funktioniert zwischen verschiedenen Netzen (das 4G des einen und das WLAN des anderen Spielers) und erlaubt Ihnen, Ihre Seite zu schließen, ohne das Spiel zu beenden.",
    "g208": "Drücken Sie SPIEL ERSTELLEN",
    "g209": "Das <b>HQ</b> öffnet sich: das ist Ihre Übersicht.",
    "g210": "Die Spieler einladen",
    "g211": "Der Reiter <b>Einladung</b> zeigt einen <b>QR-Code</b> und einen Link. Drei Wege, Ihre Spieler hereinzuholen, vom einfachsten zum manuellsten:",
    "g212": "sie <b>scannen den QR-Code</b> aus ihrer App: das geht sofort;",
    "g213": "Sie schicken ihnen den <b>Link</b> per Messenger, mit dem <b>Kopieren</b>-Knopf in der Link-Zeile;",
    "g214": "Sie geben ihnen nur den <b>Spielcode</b> &mdash; der <b>Kopieren</b>-Knopf daneben legt ihn in die Zwischenablage, praktisch zum Vorlesen oder Verschicken ohne den ganzen Link;",
    "g215": "sie <b>tippen den Code</b> in ihrem Beitreten-Menü ein.",
    "g216": "Sie können Ihr Telefon wegstecken",
    "g217": "Mit der Firebase-Verbindung lebt das Spiel auf dem Server, nicht in Ihrem Telefon. Sie können die App schließen, den Bildschirm sperren oder das Gerät sogar neu starten: beim erneuten Öffnen finden Sie Ihr HQ, Ihre Spieler und Ihr Protokoll wieder.",
    "g218": "Das ist der große Unterschied zur alten Peer-to-Peer-Verbindung, bei der Ihre Seite ständig offen bleiben musste.",
    "g219": "Bestimmen, was jedes Team zieht",
    "g220": "Das ist der Kern der Organisatorrolle, im Reiter <b>Decks</b>.",
    "g221": "Wählen Sie ein Deck",
    "g222": "Klassisch, Fortgeschritten, Extrem, Explosion oder eines Ihrer eigenen Decks.",
    "g223": "Wählen Sie, wer es bekommt",
    "g224": "Alle, nur ein Team, oder ein bestimmter Spieler.",
    "g225": "Drücken Sie DIESES DECK ZUWEISEN",
    "g226": "Es erscheint sofort auf dem Startbildschirm der Empfänger.",
    "g227": "Das zugewiesene Deck ersetzt den Modus",
    "g228": "Ein Spieler, der „Klassisch“ bekommt, zieht <b>nur</b> Klassisch. Er behält weder den Modus des Spiels noch die Explosionskarten noch seine eigenen Decks.",
    "g229": "Ein Spieler, dem Sie <b>nichts</b> zuweisen, spielt den aktuellen Modus, den Sie im Reiter Editor festgelegt haben.",
    "g230": "Ein konkretes Beispiel",
    "g231": "Sie wollen, dass die erfahrenen Sanitäter des roten Teams schweres Geschütz abbekommen, während die Anfänger des blauen Teams lernen:",
    "g232": "Zugewiesenes Deck",
    "g233": "Ergebnis",
    "g234": "Blaues Team",
    "g235": "Einfache Behandlung, sanfter Einstieg.",
    "g236": "Rotes Team",
    "g237": "Extrem",
    "g238": "Silhouette, Schutzausrüstung, lange Protokolle.",
    "g239": "Zu mehreren spielen: der Spieler",
    "g240": "Viel einfacher: Sie haben fast nichts zu tun.",
    "g241": "Der einfachste Weg: <b>den Einladungslink des Organisators öffnen</b>.",
    "g242": "Öffnen Sie den erhaltenen Link",
    "g243": "Per SMS, Messenger oder durch Scannen des QR-Codes. Er öffnet sich in Ihrem Browser, oder direkt in der App, wenn sie installiert ist.",
    "g244": "Geben Sie Spielernamen und Team an",
    "g245": "Die App ist bereits mit dem Spiel verbunden: sie fragt nur noch, unter welchem Namen Sie spielen und in welchem Team.",
    "g246": "Ihr Startbildschirm aktualisiert sich mit den Decks, die Ihnen zugewiesen wurden.",
    "g247": "Ohne den Link",
    "g248": "Öffnen Sie das Mehrspieler-Menü",
    "g249": "Der Knopf mit den zwei Silhouetten, oben rechts.",
    "g250": "Drücken Sie EINEM SPIEL BEITRETEN",
    "g251": "Der Bereich klappt auf: scannen Sie den QR-Code des Organisators oder tippen Sie den Spielcode ein. Ein erneuter Druck klappt ihn wieder zu.",
    "g252": "Geben Sie Spielernamen und Team an",
    "g253": "Die Teamliste ist die vom Organisator erstellte.",
    "g254": "Was sich im Spiel ändert",
    "g255": "das obere Band zeigt Ihr <b>Team</b> und den <b>Spielnamen</b>;",
    "g256": "oben erscheint ein Knopf <b>VERLASSEN</b>;",
    "g257": "Ihre <b>Einstellungen sind gesperrt</b>: der Organisator entscheidet über Modus, Material und Mengen;",
    "g258": "jeder Ihrer Züge erscheint im <b>Protokoll</b> des Organisators.",
    "g259": "Wenn Sie das Netz verlieren",
    "g260": "Die App verbindet sich von selbst wieder, sobald das Netz zurück ist. Während des Ausfalls <b>behalten Sie Ihre zugewiesenen Karten</b> und können weiter ziehen: nur das Protokoll und die Änderungen des Organisators warten auf das Signal.",
    "g261": "Der Knopf VERLASSEN ist endgültig",
    "g262": "Das Spiel zu verlassen löscht Ihre Sitzungsidentität. Kommen Sie zurück, sind Sie ein neuer Spieler: der Organisator muss Ihnen Ihr Team und gegebenenfalls Ihren Co-Organisator-Rang neu geben. Für eine kurze Pause <b>schließen Sie die App, ohne Verlassen zu drücken</b>.",
    "g263": "Das HQ, Reiter für Reiter",
    "g264": "Das HQ ist die Übersicht des Organisators. Sechs Reiter, jeder mit einer klaren Aufgabe.",
    "g265": "Wozu er dient",
    "g266": "Der Spielname, der QR-Code und der Link zum Teilen. Hierhin schicken Sie Ihre Spieler.",
    "g267": "Die Liste der Verbundenen. Für jeden: sein Team mit einem Druck wechseln, ihn auf <b>Admin</b> setzen oder ihn <b>Kicken</b>. Offline-Spieler bleiben ausgegraut sichtbar.",
    "g268": "<b>Teams</b>",
    "g269": "Teams anlegen oder löschen, mit ihrer Farbe. Mindestens zwei. Ein Team zu löschen verteilt seine Spieler automatisch anderswohin.",
    "g270": "<b>Editor</b>",
    "g271": "Jedes Deck <b>vor</b> dem Verteilen einstellen: Mengen, Material, Todesrisiko. Der mit <b>IM SPIEL</b> markierte Modus ist der für Spieler ohne Zuweisung.",
    "g272": "Ein Deck allen, einem Team oder einem Spieler zuweisen. Die Liste unten zeigt, was verteilt ist, mit einem Papierkorb zum Entfernen.",
    "g273": "Das Protokoll in Echtzeit: wer beigetreten ist, wer welche Verletzung gezogen hat, um welche Uhrzeit und in welchem <b>Team</b>. Als Textdatei herunterladbar.",
    "g274": "Der Co-Organisator",
    "g275": "Einen Spieler auf <b>Admin</b> zu setzen gibt ihm Zugang zum selben HQ wie Ihnen. Er kann Spieler verschieben, Decks verteilen, Teams anlegen. Sehr praktisch auf einem großen Gelände, wo Sie nicht überall sein können.",
    "g276": "Niemand kann sich selbst befördern",
    "g277": "Der Administratorrang kann nur von Ihnen oder einem bestehenden Co-Organisator vergeben werden, und diese Regel wird <b>vom Server</b> durchgesetzt. Selbst ein Spieler, der die App in- und auswendig kennt, kann ihn sich nicht selbst geben, noch die Identität eines anderen übernehmen, indem er dessen Spielernamen kopiert.",
    "g278": "Das Spiel beenden",
    "g279": "Der rote Knopf unten im HQ benachrichtigt alle Spieler und trennt sie. <b>Denken Sie daran, vorher Ihre Logs herunterzuladen</b>, wenn Sie eine Spur des Spiels behalten wollen.",
    "g280": "Im Gelände: praktische Hinweise",
    "g281": "Vor dem Spiel",
    "g282": "lassen Sie alle Sanitäter beim Briefing die App <b>einmal mit Netz öffnen</b>;",
    "g283": "bitten Sie sie, das <b>Symbol</b> auf ihrem Startbildschirm abzulegen;",
    "g284": "lassen Sie sie ihren <b>Spielernamen</b> vor dem Beitreten setzen;",
    "g285": "erstellen Sie das Spiel und testen Sie die Verbindung <b>mit einem Telefon</b>, bevor alle eintreffen;",
    "g286": "stellen Sie Ihre Mengen im Reiter <b>Editor</b> ein, bevor Sie die Decks verteilen.",
    "g287": "Während des Spiels",
    "g288": "lassen Sie das HQ auf dem Reiter <b>Logs</b> offen, um das Geschehen live zu verfolgen;",
    "g289": "stellt sich eine Behandlungsart im Gelände als nicht auffindbar heraus, nehmen Sie ihr Material im Reiter <b>Editor</b> heraus: die Änderung gilt sofort für alle Spieler;",
    "g290": "um mitten im Spiel zu verschärfen, erhöhen Sie die Wahrscheinlichkeit des Todesrisikos: die Änderung ist bei allen Spielern sofort wirksam;",
    "g291": "ernennen Sie einen <b>Co-Organisator</b>, wenn das Gelände groß ist.",
    "g292": "Nach dem Spiel",
    "g293": "<b>laden Sie die Logs herunter</b>, bevor Sie beenden: ausgezeichnete Grundlage für das Debriefing;",
    "g294": "beenden Sie sauber, um den Spielnamen freizugeben.",
    "g295": "Der Bildschirm bleibt an, solange ein Blatt angezeigt wird, und die dauerhafte Verbindung verbraucht Strom. Für einen ganzen Tag sollten Sie eine <b>Powerbank</b> für den Organisator und für die meistbeschäftigten Sanitäter einplanen.",
    "g296": "Wenn etwas nicht klappt",
    "g297": "Symptom",
    "g298": "<b>Die App öffnet sich ohne Netz nicht</b>",
    "g299": "Sie wurde auf diesem Gerät nie mit Netz geöffnet. Verbinden Sie sich einmal, lassen Sie sie vollständig laden, danach funktioniert sie offline.",
    "g300": "<b>„Spiel nicht gefunden“</b>",
    "g301": "Prüfen Sie die genaue Schreibweise des Namens beim Organisator. Akzente und Leerzeichen spielen keine Rolle, Buchstaben schon. Am sichersten bleibt der QR-Code.",
    "g302": "<b>„Keine Karte verfügbar“</b>",
    "g303": "Entweder stehen alle Karten auf null, oder sie sind durch fehlendes Material blockiert. Im Solospiel öffnen Sie die Einstellungen und haken Material wieder an. Im Spiel melden Sie es dem Organisator: nur er kann daran etwas ändern.",
    "g304": "<b>Ein Spieler erscheint doppelt</b>",
    "g305": "Zwei Spieler haben denselben Namen: der zweite wird automatisch zu „Name (2)“. Bitten Sie ihn, den Namen zu ändern, oder lassen Sie es so.",
    "g306": "<b>Ein Spieler bleibt „offline“</b>",
    "g307": "Sein Telefon hat das Netz verloren. Er kommt von selbst zurück. Ist er wirklich weg, entfernen Sie ihn mit dem Kick-Knopf.",
    "g308": "<b>Ich finde meine eigenen Decks nicht mehr</b>",
    "g309": "Sie sind im Spiel: sie sind beiseitegelegt und werden Ihnen beim Verlassen zurückgegeben. Nichts geht verloren.",
    "g310": "<b>Die Anzeige wirkt veraltet</b>",
    "g311": "Schließen Sie die App vollständig und öffnen Sie sie mit Netz erneut: sie aktualisiert sich von selbst.",
    "g312": "<font color=\"white\" size=\"11\"><b>Gutes Spiel, und gute Behandlung.</b></font><br/><font color=\"#c49708\" size=\"9\">Bravo Sierra Events // Frontline</font>",
    "g313": "BSE Medical System - Bedienungsanleitung",
    "g314": "Bravo Sierra Events",
    "g315": "Bedienungsanleitung der Anwendung BSE Medical System",
    "g316": "PDF genere :",
    "g317": "taille     :",
}
