# -*- coding: utf-8 -*-
"""Guide BSE Medical System — textes ANGLAIS.

   Meme jeu de cles que guide-fr.py, qui est la reference.
   Le balisage <b>, <br/> et <font> doit etre conserve tel quel.
"""
TEXTES = {
    "m01": "Torso",
    "m02": "BODY ARMOUR",
    "m03": "ASSESSMENT",
    "m04": "Title",
    "m05": "Body armour",
    "m06": "Assessment",
    "chapitre_apres": "",
    "chapitre": "CHAPTER",
    "g001": "<font size=\"7\" color=\"#8a8a84\">TRIAGE SHEET</font>",
    "g002": "<font size=\"8\" color=\"white\"><b> CRITICAL </b></font>",
    "g003": "INTERNAL HAEMORRHAGE",
    "g004": "AREA HIT",
    "g005": "Ballistic plates worn: NO",
    "g006": "Penetrating wound to the abdomen causing<br/>heavy internal bleeding.",
    "g007": "TREATMENT PROTOCOL",
    "g008": "Bandage + Blood bag<br/>+ Epinephrine",
    "g009": "BSE MEDICAL SYSTEM  //  USER GUIDE",
    "g010": "Bravo Sierra Events",
    "g011": "BSE MEDICAL SYSTEM",
    "g012": "FRONTLINE  //  FIELD APPLICATION",
    "g013": "<font color=\"white\" size=\"15\"><b>User guide</b></font>",
    "g014": "<font color=\"#9b9b96\" size=\"10.5\">To discover the app, knowing nothing at the start</font>",
    "g015": "<font color=\"#c49708\" size=\"9\">https://project-bsm-7d32c.web.app</font>",
    "g016": "What this application is for",
    "g017": "Installing the app on your phone",
    "g018": "Your first assessment",
    "g019": "Reading a triage sheet",
    "g020": "The severity levels",
    "g021": "The game modes",
    "g022": "Extreme mode in detail",
    "g023": "The settings",
    "g024": "Building your own card decks",
    "g025": "Playing together: the organiser",
    "g026": "Playing together: the player",
    "g027": "The HQ, tab by tab",
    "g028": "In the field: practical advice",
    "g029": "If something goes wrong",
    "g030": "Who this guide is for",
    "g031": "Never opened the app? You are exactly the right person. This guide starts from scratch and assumes no prior knowledge, neither in airsoft medical play nor in computers. Read chapters 1 to 5 to play this very afternoon; the rest will serve you when you want to run a game.",
    "g032": "What this application is for",
    "g033": "BSE Medical System replaces the paper card deck that airsoft medics carry around in their pocket. When a player is hit, the medic pulls out their phone, presses a button, and the app draws a random injury with the matching treatment protocol.",
    "g034": "No more wet, lost or shuffled cards. And above all: the organiser can decide remotely what each team will draw.",
    "g035": "The principle, in four steps",
    "g036": "A player is hit",
    "g037": "They go down and call for a medic.",
    "g038": "The medic arrives and opens the app",
    "g039": "They press the big round button in the middle of the screen.",
    "g040": "The app draws an injury",
    "g041": "A sheet appears: the area hit, the severity, and the treatment to apply.",
    "g042": "The medic applies the protocol",
    "g043": "Tourniquet, bandage, splint... as the sheet says. The casualty then goes back into play.",
    "g044": "The equipment stays very real",
    "g045": "The app does not replace your med kit. It tells you <b>what to do</b>; putting on the actual dummy tourniquet and the actual bandage is up to you. If a type of treatment is not available at the event &mdash; nobody has a 3-sided seal, for example &mdash; the organiser removes it from play <b>before</b> the game, and the injuries that require it stop coming up.",
    "g046": "Installing the app on your phone",
    "g047": "There is nothing to download from an app store. It all goes through your usual browser.",
    "g048": "Open the address in your browser",
    "g049": "<b>https://project-bsm-7d32c.web.app</b> &mdash; Chrome on Android, Safari on iPhone.",
    "g050": "Add the app to your home screen",
    "g051": "On <b>Android</b>: the “three dots” menu, then “Install app” or “Add to Home screen”.<br/>On <b>iPhone</b>: the Share button (the square with the arrow), then “Add to Home Screen”.",
    "g052": "Launch it from the icon",
    "g053": "A golden medical cross on a black background appears with your other apps. It opens full screen, with no address bar.",
    "g054": "Do this at the briefing, not in the field",
    "g055": "Every phone must open the app <b>once with a network connection</b>. The app then stores itself entirely on the device.",
    "g056": "Once that first opening is done, it works <b>with no network at all</b>: you can draw injuries deep in the woods, in flight mode. Only multiplayer needs a connection.",
    "g057": "What you see when you arrive",
    "g058": "The home screen is called <b>MEDICAL ASSESSMENT</b>. On it you will find:",
    "g059": "one or more <b>big round buttons</b> in the middle: these are your available draws;",
    "g060": "an <b>ACTIVE DECK</b> strip at the bottom, showing how many cards are in play;",
    "g061": "top right, three buttons: <b>multiplayer</b>, <b>my decks</b> and <b>settings</b>;",
    "g062": "at the top, a grey strip with your player name and your team.",
    "g063": "Your first assessment",
    "g064": "This is the app's main use, and the simplest one.",
    "g065": "Press the round button",
    "g066": "The most common one is called <b>BALLISTIC</b>: an injury caused by gunfire.",
    "g067": "Wait for the analysis",
    "g068": "A <b>MARCH</b> assessment scrolls by for a few seconds. That is the diagnosis time; use it to look the casualty over.",
    "g069": "Read the sheet",
    "g070": "It gives the severity, the area hit and the protocol to apply.",
    "g071": "Apply the treatment, then press “New assessment”",
    "g072": "You go back to the home screen, ready for the next casualty.",
    "g073": "What does MARCH mean?",
    "g074": "It is the order in which a first responder examines a casualty, from the most lethal to the least urgent. The app displays it to get you in the mood:",
    "g075": "<b>Massive bleeding</b> &mdash; massive haemorrhages first",
    "g076": "<b>Airways</b> &mdash; the airway",
    "g077": "<b>Respiration</b> &mdash; breathing",
    "g078": "<b>Circulation</b> &mdash; pulse and shock",
    "g079": "<b>Head / Hypothermia</b> &mdash; the head and cooling down",
    "g080": "The screen stays on",
    "g081": "As long as a sheet is displayed, the phone does not lock. You can put it down to work with both hands: the protocol will still be there when you pick it back up.",
    "g082": "Reading a triage sheet",
    "g083": "All the sheets are built the same way. Here is what a complete sheet looks like:",
    "g084": "Each part, one by one",
    "g085": "Part of the sheet",
    "g086": "What it means",
    "g087": "<b>Severity badge</b>",
    "g088": "Top right, colour-coded. It shows the urgency of the situation at a glance. The strip at the top of the sheet is the same colour.",
    "g089": "The short name of the injury, in large type.",
    "g090": "<b>Area hit</b>",
    "g091": "Where the casualty is wounded: head, torso, left arm, right leg...",
    "g092": "Only appears in Extreme mode. Reminds you whether the casualty was wearing a helmet or plates.",
    "g093": "The description of the injury, to read out loud to the casualty for role-play.",
    "g094": "<b>Treatment protocol</b>",
    "g095": "<b>The most important part</b>: exactly what you have to do.",
    "g096": "Watch out for the countdown",
    "g097": "If the organiser has enabled the hardcore option, some injuries trigger a <b>regular beep</b> and a red <b>ACTIVE HAEMORRHAGE</b> banner.",
    "g098": "You then have a limited time to apply the treatment and press <b>TREATMENT DONE</b>. If the time runs out, the casualty dies: the screen goes black and the beep turns into a continuous tone.",
    "g099": "The severity levels",
    "g100": "Five levels, always the same, with a colour code that is consistent throughout the app.",
    "g101": "Severity",
    "g102": "What it means for the medic",
    "g103": "DEATH",
    "g104": "Nothing to do. The player is dead and returns to the respawn point.",
    "g105": "Life-threatening. These are the injuries that trigger the countdown, if the option is enabled.",
    "g106": "Serious but stable. Take the time to apply the protocol properly.",
    "g107": "MINOR",
    "g108": "Scratches. One bandage and the player is back in play.",
    "g109": "SPECIAL",
    "g110": "A special case, usually tied to body armour. Read the protocol carefully: it depends on whether a helmet or a vest was worn.",
    "g111": "Why some injuries come up more often",
    "g112": "Each card has a <b>quantity</b>, as if several copies of the same card were in the deck. A card with 4 copies will come up twice as often as one with 2. The organiser sets these quantities to set the tone of the game: more scratches, or more life-threatening emergencies.",
    "g113": "The game modes",
    "g114": "The mode decides which card deck is used. You choose it in the <b>Settings</b>, or the organiser imposes it during a game.",
    "g115": "For beginners. Simple treatment: tourniquet, bandage, splint. Ideal for a first game.",
    "g116": "<b>Advanced</b>",
    "g117": "For regulars. Longer protocols, with morphine and epinephrine coming into play.",
    "g118": "<b>Extreme</b>",
    "g119": "The most realistic. You point at the area hit on a silhouette, and the injuries follow from it. See the next chapter.",
    "g120": "An <b>extra</b> deck, for grenades and explosives. It adds a second round button on the home screen.",
    "g121": "The special case of explosions",
    "g122": "The Explosion deck holds blast and shrapnel injuries. You enable it in the Settings, in Advanced or Extreme mode, and an orange <b>EXPLOSION</b> button appears next to the Ballistic button.",
    "g123": "An explosion ignores body armour",
    "g124": "This is deliberate: unlike gunshot injuries, an explosion card can kill a player <b>even if they are wearing a helmet and plates</b>. A blast wave goes straight through. Do not look for a bug &mdash; it is the rule.",
    "g125": "Extreme mode in detail",
    "g126": "This is the most immersive mode, and the only one where <b>you</b> decide the area hit instead of leaving it to chance.",
    "g127": "Press the draw button",
    "g128": "Instead of the sheet, a <b>human silhouette</b> appears.",
    "g129": "Tap the area where the player was hit",
    "g130": "Head, torso, arm or leg. <b>The view is mirrored</b>: the casualty's right arm is on your left on the screen, as if you were facing them.",
    "g131": "Answer the body armour question",
    "g132": "For the head: “Ballistic helmet worn?”. For the torso: “Bulletproof vest worn?”. Look at the casualty and answer honestly.",
    "g133": "The sheet appears",
    "g134": "It only contains injuries consistent with the area <b>and</b> with your answer.",
    "g135": "Why the body armour question changes everything",
    "g136": "The answer really does filter the available cards. A helmeted player cannot draw “Direct shot to the head (no helmet)”:",
    "g137": "Area hit",
    "g138": "Body armour worn",
    "g139": "No body armour",
    "g140": "<b>Head</b>",
    "g141": "Impact on the helmet<br/><font size='8' color='#5d5d58'>Rest for 2 minutes</font>",
    "g142": "Forehead wound, head trauma, <b>or a fatal shot</b>",
    "g143": "Impact on the plate, graze to the flank, broken ribs",
    "g144": "Pneumothorax, internal haemorrhage, <b>or a fatal shot</b>",
    "g145": "<b>Arm / Leg</b>",
    "g146": "<font color='#5d5d58'>Question not asked</font>",
    "g147": "Injuries specific to the limb: a fractured femur cannot come up on an arm.",
    "g148": "The moral of Extreme mode",
    "g149": "Wearing a helmet and plates genuinely saves your life in this mode. It is the best argument for getting your players to kit up properly.",
    "g150": "The settings",
    "g151": "You reach them through the <b>sliders</b> button, top right of the screen. Remember to press <b>CONFIRM</b> at the bottom to keep your changes; <b>CANCEL</b> puts everything back as it was.",
    "g152": "Multiplayer profile",
    "g153": "Your <b>player name</b>. This is the name the organiser will see you under. Set it before joining a game: it is easier for everyone.",
    "g154": "Classic, Advanced, Extreme, or one of your own decks. During a game this setting is locked: the organiser decides.",
    "g155": "Hardcore option: the risk of death",
    "g156": "Once ticked, four settings appear:",
    "g157": "Setting",
    "g158": "<b>Probability</b>",
    "g159": "The chance that an injury triggers the countdown. 40% by default: roughly one critical injury in two.",
    "g160": "<b>Minimum delay</b>",
    "g161": "The shortest time the medic gets. 30 seconds by default.",
    "g162": "<b>Maximum delay</b>",
    "g163": "The longest time. 60 seconds by default. The actual delay is drawn at random between the two, and the medic does not see it.",
    "g164": "<b>Extend to Serious</b>",
    "g165": "By default, only Critical injuries can kill. Tick this to make the game distinctly harder.",
    "g166": "Required equipment",
    "g167": "This list does not track the contents of your med kit as the game goes on. It defines <b>which types of treatment are in play</b>: you untick the equipment you do not have, and the app stops drawing the injuries that require it.",
    "g168": "It is a <b>preparation</b> setting, not a field setting: it is done before the game, and normally by the organiser.",
    "g169": "A player does not remove cards from play",
    "g170": "During a game, your settings are <b>locked</b>: the organiser decides the equipment and the quantities, so that all medics play the same deck. You therefore cannot set aside an injury just because it does not suit you.",
    "g171": "In solo play, on the other hand, you configure your own game freely.",
    "g172": "<b>Example.</b> No medic at the event has a 3-sided seal? The organiser unticks that item before the game: the sucking chest wound and the pneumothorax disappear from the deck for everyone.",
    "g173": "Active cards",
    "g174": "The complete list of the mode's injuries, <b>sorted by severity</b>: death first, then critical, serious, minor and special. For each card:",
    "g175": "the eye opens the <b>catalogue</b> and shows you the card in full;",
    "g176": "the <b>&ndash;</b> and <b>+</b> buttons set its quantity in the deck;",
    "g177": "the <b>percentage</b> on the right shows its chance of coming up. It updates by itself;",
    "g178": "a <b>greyed-out</b> line means the equipment is missing: that card will not come up.",
    "g179": "Setting a card to zero",
    "g180": "Setting the quantity to 0 removes the card from the deck entirely. That is the clean way to set aside an injury you do not like, without touching anything else.",
    "g181": "Building your own card decks",
    "g182": "The <b>pencil</b> button at the top right opens “My decks”. There you can build your own injuries: chemical contamination, radiation, bites, whatever your scenario calls for.",
    "g183": "Create a deck",
    "g184": "Give it a name. Tick <b>Show on the home screen</b> so it gets its own round button.",
    "g185": "Add cards",
    "g186": "For each one: a severity, a title, an area, a treatment protocol.",
    "g187": "Choose the required equipment",
    "g188": "Tap the matching chips. You can create equipment that does not exist in the base list &mdash; “Anti-rad”, “Serum”...",
    "g189": "Choose the button icon",
    "g190": "About thirty pictograms to choose from: bullet, grenade, explosion, biohazard, radiation, zombie, creature, robot, syringe, pills, IV drip... It identifies the deck on the home screen, and follows the deck when you share it or assign it during a game.",
    "g191": "The deck appears on your home screen, ready to use.",
    "g192": "Sharing a deck with someone",
    "g193": "The <b>share</b> button on a deck card produces a long code starting with <b>TMDECK1</b>. Send it by text or messaging; the recipient uses <b>Import a deck</b> and pastes the code. They get all the cards and the associated equipment.",
    "g194": "The deck's “extreme mode” option",
    "g195": "When ticked, your own deck also triggers the silhouette and the body armour question, just like the official Extreme mode.",
    "g196": "During a game, your decks are set aside",
    "g197": "When you join a game, the organiser imposes their configuration: your own decks temporarily disappear and creating new ones is blocked. <b>They are given back to you in full as soon as you leave the game.</b> Nothing is lost.",
    "g198": "Playing together: the organiser",
    "g199": "The organiser creates the game and steers what each player will draw. The <b>multiplayer</b> button is at the top right.",
    "g200": "Open the multiplayer menu",
    "g201": "The first button at the top right, with the two silhouettes.",
    "g202": "Give the game a name",
    "g203": "For example “Exercise Alpha”. That is the name your players will type to join you.",
    "g204": "Enter your player name",
    "g205": "The name you will appear under.",
    "g206": "Leave the link on “Firebase server”",
    "g207": "That is the recommended setting. It works across different networks (one player's 4G and another's WiFi) and lets you close your page without ending the game.",
    "g208": "Press CREATE A GAME",
    "g209": "The <b>HQ</b> opens: that is your dashboard.",
    "g210": "Inviting the players",
    "g211": "The <b>Invite</b> tab shows a <b>QR code</b> and a link. Three ways to get your players in, from the simplest to the most manual:",
    "g212": "they <b>scan the QR code</b> from their app: it is instant;",
    "g213": "you send them the <b>link</b> by messaging, with the <b>Copy</b> button on the link row;",
    "g214": "you give them the <b>game code</b> alone &mdash; the <b>Copy</b> button next to it puts it in the clipboard, handy for reading it out or sending it without the full link;",
    "g215": "they <b>type the code</b> in their Join menu.",
    "g216": "You can put your phone away",
    "g217": "With the Firebase link, the game lives on the server, not in your phone. You can close the app, lock your screen, or even restart your device: when you reopen the app, you find your HQ, your players and your log again.",
    "g218": "That is the major difference from the old peer-to-peer link, where your page had to stay open at all times.",
    "g219": "Deciding what each team will draw",
    "g220": "This is the heart of the organiser's role, in the <b>Decks</b> tab.",
    "g221": "Choose a deck",
    "g222": "Classic, Advanced, Extreme, Explosion, or one of your own decks.",
    "g223": "Choose who receives it",
    "g224": "Everyone, one team only, or one specific player.",
    "g225": "Press ASSIGN THIS DECK",
    "g226": "It appears immediately on the recipients' home screen.",
    "g227": "An assigned deck replaces the mode",
    "g228": "A player who receives “Classic” will draw <b>only</b> from Classic. They keep neither the game's mode, nor the explosion cards, nor their own decks.",
    "g229": "A player you assign <b>nothing</b> to plays the current mode, the one you set in the Editor tab.",
    "g230": "A concrete example",
    "g231": "You want the experienced medics of the Red team to face the heavy stuff, while the beginners of the Blue team learn:",
    "g232": "Assigned deck",
    "g233": "Result",
    "g234": "Blue team",
    "g235": "Simple treatment, gentle learning curve.",
    "g236": "Red team",
    "g237": "Extreme",
    "g238": "Silhouette, body armour, long protocols.",
    "g239": "Playing together: the player",
    "g240": "Much simpler: there is almost nothing for you to do.",
    "g241": "The simplest way: <b>open the organiser's invitation link</b>.",
    "g242": "Open the link you received",
    "g243": "By text, messaging, or by scanning the QR code. It opens in your browser, or straight in the app if it is installed.",
    "g244": "Enter your player name and your team",
    "g245": "The app is already attached to the game: it only asks what name you are playing under and which team you are in.",
    "g246": "Your home screen updates with the decks you have been assigned.",
    "g247": "Without the link",
    "g248": "Open the multiplayer menu",
    "g249": "The button with the two silhouettes, at the top right.",
    "g250": "Press JOIN A GAME",
    "g251": "The section unfolds: scan the organiser's QR code, or type the game code. Pressing again folds it back.",
    "g252": "Enter your player name and your team",
    "g253": "The list of teams is the one created by the organiser.",
    "g254": "What changes once you are in a game",
    "g255": "the top strip shows your <b>team</b> and the <b>game name</b>;",
    "g256": "a <b>LEAVE</b> button appears at the top;",
    "g257": "your <b>settings are locked</b>: the organiser decides the mode, the equipment and the quantities;",
    "g258": "every draw you make appears in the organiser's <b>log</b>.",
    "g259": "If you lose the network",
    "g260": "The app reconnects on its own as soon as the network is back. During the outage you <b>keep your assigned cards</b> and can carry on drawing: only the log and the changes made by the organiser wait for the signal to return.",
    "g261": "The LEAVE button is final",
    "g262": "Leaving the game erases your session identity. If you come back, you will be a new player: the organiser will have to give you your team again and, if applicable, your co-organiser rank. For a simple break, <b>close the app without pressing Leave</b>.",
    "g263": "The HQ, tab by tab",
    "g264": "The HQ is the organiser's dashboard. Six tabs, each with a precise role.",
    "g265": "What it is for",
    "g266": "The game name, the QR code and the link to share. This is where you send your players.",
    "g267": "The list of connected players. For each one: change their team with one tap, make them <b>Admin</b>, or <b>Kick</b> them. Offline players stay listed, greyed out.",
    "g268": "<b>Teams</b>",
    "g269": "Create or delete teams, with their colour. Two minimum. Deleting a team automatically moves its players elsewhere.",
    "g270": "<b>Editor</b>",
    "g271": "Set up each deck <b>before</b> handing it out: quantities, equipment, risk of death. The mode marked <b>IN PLAY</b> is the one used by players with no assignment.",
    "g272": "Assign a deck to everyone, to a team or to a player. The list at the bottom shows what has been handed out, with a bin icon to remove.",
    "g273": "The live log: who joined, who drew which injury, at what time. Downloadable as a text file.",
    "g274": "The co-organiser",
    "g275": "Making a player <b>Admin</b> gives them access to the same HQ as you. They can move players around, hand out decks, create teams. Very handy on a large site where you cannot be everywhere.",
    "g276": "Nobody can promote themselves",
    "g277": "Administrator rank can only be granted by you or by an existing co-organiser, and that rule is enforced <b>by the server</b>. Even a player who knew the app inside out could not grant it to themselves, nor take someone else's identity by copying their player name.",
    "g278": "Closing the game",
    "g279": "The red button at the bottom of the HQ notifies all players and disconnects them. <b>Remember to download your logs first</b> if you want a record of the game.",
    "g280": "In the field: practical advice",
    "g281": "Before the game",
    "g282": "have every medic <b>open the app once with a network connection</b>, at the briefing;",
    "g283": "ask them to <b>install the icon</b> on their home screen;",
    "g284": "have them set their <b>player name</b> before joining;",
    "g285": "create the game and test the connection <b>with one phone</b> before everyone arrives;",
    "g286": "set your quantities in the <b>Editor</b> tab before handing out the decks.",
    "g287": "During the game",
    "g288": "keep the HQ open on the <b>Logs</b> tab to follow the action live;",
    "g289": "if a type of treatment turns out to be unavailable in the field, remove its equipment from the <b>Editor</b> tab: the change applies to all players at once;",
    "g290": "to make things harder mid-game, raise the risk-of-death probability: the change is immediate for every player;",
    "g291": "appoint a <b>co-organiser</b> if the site is large.",
    "g292": "After the game",
    "g293": "<b>download the logs</b> before closing: excellent material for the debrief;",
    "g294": "close the game properly to free up its name.",
    "g295": "The screen stays on while a sheet is displayed, and the permanent connection uses power. Over a full day, plan for a <b>power bank</b> for the organiser and for the busiest medics.",
    "g296": "If something goes wrong",
    "g297": "Symptom",
    "g298": "<b>The app will not open without a network</b>",
    "g299": "It has never been opened with a network on this device. Reconnect once, let it load fully, and then it will work offline.",
    "g300": "<b>“Game not found”</b>",
    "g301": "Check the exact spelling of the name with the organiser. Accents and spaces do not matter, but letters do. The QR code remains the safest route.",
    "g302": "<b>“No card available”</b>",
    "g303": "Either all the cards are at zero, or they are blocked by missing equipment. In solo play, open the Settings and tick some equipment back on. In a game, tell the organiser: only they can change it.",
    "g304": "<b>A player appears twice</b>",
    "g305": "Two players have the same name: the second automatically becomes “Name (2)”. Ask them to change it, or leave it as it is.",
    "g306": "<b>A player stays “offline”</b>",
    "g307": "Their phone has lost the network. They come back on their own. If they really have left, remove them with the Kick button.",
    "g308": "<b>I cannot find my own decks any more</b>",
    "g309": "You are in a game: they are set aside and will be given back when you leave. Nothing is lost.",
    "g310": "<b>The display looks out of date</b>",
    "g311": "Close the app completely and reopen it with a network connection: it updates itself.",
    "g312": "<font color=\"white\" size=\"11\"><b>Good game, and good treatment.</b></font><br/><font color=\"#c49708\" size=\"9\">Bravo Sierra Events // Frontline</font>",
    "g313": "BSE Medical System - User guide",
    "g314": "Bravo Sierra Events",
    "g315": "User guide for the BSE Medical System application",
    "g316": "PDF genere :",
    "g317": "taille     :",
}
