# -*- coding: utf-8 -*-
"""Guide BSE Medical System — textes FRANCAIS (langue de reference).

   Ce fichier ne contient que du texte. La mise en page est dans
   tools-guide.py, qui genere un PDF par langue.
   Le balisage accepte <b>, <br/> et les entites HTML (&eacute;...).
"""
TEXTES = {
    "m08": "Enregistrer",
    "m09": "Une seule carte pour plusieurs membres",
    "m10": "La zone se choisit dans une liste&nbsp;: t&ecirc;te, torse, bras droit, bras gauche, jambe droite, jambe gauche &mdash; mais aussi <b>les deux bras</b>, <b>les deux jambes</b> ou <b>les quatre membres</b>. Une &eacute;raflure aux quatre membres tient alors en <b>une seule carte</b> au lieu de quatre&nbsp;: la zone exacte est tir&eacute;e au sort au moment du diagnostic, et en mode Extr&ecirc;me c'est celle que vous avez touch&eacute;e sur la silhouette. &laquo;&nbsp;Zone personnalis&eacute;e&nbsp;&raquo; reste l&agrave; pour &eacute;crire ce que vous voulez. Trois boutons <b>Protection balistique</b> completent le tableau&nbsp;: la carte peut ne sortir qu'<b>avec</b> le casque ou le gilet, qu'<b>en leur absence</b>, ou dans les deux cas. C'est ainsi qu'on oppose &laquo;&nbsp;impact sur casque&nbsp;&raquo; et &laquo;&nbsp;tir &agrave; la t&ecirc;te&nbsp;&raquo;.",
    "m07": "tout en bas&nbsp;: &agrave; gauche le <b>choix de la langue</b>, &agrave; droite les liens vers <b>Bravo Sierra Events</b> &mdash; site, Discord, Instagram, YouTube et Facebook.",
    "m01": "Torse",
    "m02": "PROTECTION",
    "m03": "BILAN",
    "m04": "Titre",
    "m05": "Protection",
    "m06": "Bilan",
    "chapitre_apres": "",
    "chapitre": "CHAPITRE",
    "g001": "<font size=\"7\" color=\"#8a8a84\">FICHE DE TRIAGE</font>",
    "g002": "<font size=\"8\" color=\"white\"><b> CRITIQUE </b></font>",
    "g003": "H&Eacute;MORRAGIE INTERNE",
    "g004": "ZONE TOUCH&Eacute;E",
    "g005": "Plaques balistiques port&eacute;es : NON",
    "g006": "Blessure perforante &agrave; l'abdomen causant<br/>une importante h&eacute;morragie interne.",
    "g007": "PROTOCOLE DE SOIN",
    "g008": "Bandage + Poche de transfusion<br/>+ &Eacute;pin&eacute;phrine",
    "g009": "BSE MEDICAL SYSTEM  //  GUIDE D'UTILISATION",
    "g010": "Bravo Sierra Events",
    "g011": "BSE MEDICAL SYSTEM",
    "g012": "FRONTLINE  //  FIELD APPLICATION",
    "g013": "<font color=\"white\" size=\"15\"><b>Guide d'utilisation</b></font>",
    "g014": "<font color=\"#9b9b96\" size=\"10.5\">Pour d&eacute;couvrir l'application, sans rien conna&icirc;tre au d&eacute;part</font>",
    "g015": "<font color=\"#c49708\" size=\"9\">https://project-bsm-7d32c.web.app</font>",
    "g016": "&Agrave; quoi sert cette application",
    "g017": "Installer l'application sur votre t&eacute;l&eacute;phone",
    "g018": "Votre premier diagnostic",
    "g019": "Lire une fiche de triage",
    "g020": "Les niveaux de gravit&eacute;",
    "g021": "Les modes de jeu",
    "g022": "Le mode Extr&ecirc;me en d&eacute;tail",
    "g023": "Les r&eacute;glages",
    "g024": "Cr&eacute;er vos propres paquets de cartes",
    "g025": "Jouer &agrave; plusieurs : l'organisateur",
    "g026": "Jouer &agrave; plusieurs : le joueur",
    "g027": "Le QG, onglet par onglet",
    "g028": "Sur le terrain : conseils pratiques",
    "g029": "En cas de probl&egrave;me",
    "g030": "&Agrave; qui s'adresse ce guide",
    "g031": "Vous n'avez jamais ouvert l'application&nbsp;? Vous &ecirc;tes exactement la bonne personne. Ce guide part de z&eacute;ro et n'attend aucune connaissance pr&eacute;alable, ni en airsoft m&eacute;dical, ni en informatique. Lisez les chapitres 1 &agrave; 5 pour jouer d&egrave;s cet apr&egrave;s-midi&nbsp;; le reste vous servira quand vous voudrez organiser une partie.",
    "g032": "&Agrave; quoi sert cette application",
    "g033": "BSE Medical System remplace le jeu de cartes papier que les m&eacute;dics d'airsoft trimballent dans leur poche. Quand un joueur est touch&eacute;, le m&eacute;dic sort son t&eacute;l&eacute;phone, appuie sur un bouton, et l'application tire une blessure au hasard avec le protocole de soin correspondant.",
    "g034": "Fini les cartes mouill&eacute;es, perdues ou m&eacute;lang&eacute;es. Et surtout&nbsp;: l'organisateur peut d&eacute;cider &agrave; distance de ce que chaque &eacute;quipe va tirer.",
    "g035": "Le principe, en quatre temps",
    "g036": "Un joueur est touch&eacute;",
    "g037": "Il se met au sol et appelle un m&eacute;dic.",
    "g038": "Le m&eacute;dic arrive et ouvre l'application",
    "g039": "Il appuie sur le gros bouton rond au centre de l'&eacute;cran.",
    "g040": "L'application tire une blessure",
    "g041": "Une fiche appara&icirc;t&nbsp;: la zone touch&eacute;e, la gravit&eacute;, et les soins &agrave; appliquer.",
    "g042": "Le m&eacute;dic applique le protocole",
    "g043": "Garrot, bandage, attelle... selon ce qu'indique la fiche. Le bless&eacute; repart ensuite.",
    "g044": "Le mat&eacute;riel reste bien r&eacute;el",
    "g045": "L'application ne remplace pas votre trousse. Elle vous dit <b>quoi faire</b>&nbsp;; c'est &agrave; vous de poser le vrai garrot factice et le vrai bandage. Si un type de soin n'est pas disponible sur l'&eacute;v&eacute;nement &mdash; personne n'a de pansement 3 c&ocirc;t&eacute;s, par exemple &mdash; l'organisateur le retire du jeu <b>avant</b> la partie, et les blessures qui l'exigent ne sortent plus.",
    "g046": "Installer l'application sur votre t&eacute;l&eacute;phone",
    "g047": "Il n'y a rien &agrave; t&eacute;l&eacute;charger sur un magasin d'applications. Tout passe par votre navigateur habituel.",
    "g048": "Ouvrez l'adresse dans votre navigateur",
    "g049": "<b>https://project-bsm-7d32c.web.app</b> &mdash; Chrome sur Android, Safari sur iPhone.",
    "g050": "Ajoutez l'application &agrave; votre &eacute;cran d'accueil",
    "g051": "Sur <b>Android</b>&nbsp;: menu &laquo;&nbsp;trois points&nbsp;&raquo; puis &laquo;&nbsp;Installer l'application&nbsp;&raquo; ou &laquo;&nbsp;Ajouter &agrave; l'&eacute;cran d'accueil&nbsp;&raquo;.<br/>Sur <b>iPhone</b>&nbsp;: bouton Partager (le carr&eacute; avec la fl&egrave;che) puis &laquo;&nbsp;Sur l'&eacute;cran d'accueil&nbsp;&raquo;.",
    "g052": "Lancez-la depuis l'ic&ocirc;ne",
    "g053": "Une croix m&eacute;dicale dor&eacute;e sur fond noir appara&icirc;t avec vos autres applications. Elle s'ouvre en plein &eacute;cran, sans barre d'adresse.",
    "g054": "&Agrave; faire au briefing, pas sur le terrain",
    "g055": "Chaque t&eacute;l&eacute;phone doit ouvrir l'application <b>une fois avec du r&eacute;seau</b>. L'application se met alors enti&egrave;rement en m&eacute;moire sur l'appareil.",
    "g056": "Une fois cette premi&egrave;re ouverture faite, elle fonctionne <b>sans aucun r&eacute;seau</b>&nbsp;: vous pouvez tirer des blessures en plein bois, en mode avion. Seul le jeu &agrave; plusieurs demande une connexion.",
    "g057": "Ce que vous voyez en arrivant",
    "g058": "L'&eacute;cran d'accueil s'appelle <b>DIAGNOSTIC M&Eacute;DICAL</b>. On y trouve&nbsp;:",
    "g059": "un ou plusieurs <b>gros boutons ronds</b> au centre&nbsp;: ce sont vos tirages disponibles&nbsp;;",
    "g060": "un bandeau <b>PAQUET ACTIF</b> en bas, qui indique combien de cartes sont en jeu&nbsp;;",
    "g061": "en haut &agrave; droite, trois boutons&nbsp;: <b>multijoueur</b>, <b>mes paquets</b> et <b>r&eacute;glages</b>&nbsp;;",
    "g062": "en haut, un bandeau gris avec votre pseudo et votre &eacute;quipe.",
    "g063": "Votre premier diagnostic",
    "g064": "C'est l'usage principal de l'application, et le plus simple.",
    "g065": "Appuyez sur le bouton rond",
    "g066": "Le plus courant s'appelle <b>BALISTIQUE</b>&nbsp;: c'est une blessure par tir.",
    "g067": "Attendez l'analyse",
    "g068": "Un bilan <b>MARCH</b> d&eacute;file pendant quelques secondes. C'est le temps du diagnostic, profitez-en pour observer le bless&eacute;.",
    "g069": "Lisez la fiche",
    "g070": "Elle indique la gravit&eacute;, la zone touch&eacute;e et le protocole &agrave; appliquer.",
    "g071": "Appliquez les soins, puis appuyez sur &laquo;&nbsp;Nouveau diagnostic&nbsp;&raquo;",
    "g072": "Vous revenez &agrave; l'accueil, pr&ecirc;t pour le bless&eacute; suivant.",
    "g073": "Que veut dire MARCH&nbsp;?",
    "g074": "C'est l'ordre dans lequel un secouriste examine un bless&eacute;, du plus mortel au moins urgent. L'application l'affiche pour vous mettre dans le bain&nbsp;:",
    "g075": "<b>Massive bleeding</b> &mdash; les h&eacute;morragies massives d'abord",
    "g076": "<b>Airways</b> &mdash; les voies respiratoires",
    "g077": "<b>Respiration</b> &mdash; la ventilation",
    "g078": "<b>Circulation</b> &mdash; le pouls, le choc",
    "g079": "<b>Head / Hypothermia</b> &mdash; la t&ecirc;te et le refroidissement",
    "g080": "L'&eacute;cran reste allum&eacute;",
    "g081": "Tant qu'une fiche est affich&eacute;e, le t&eacute;l&eacute;phone ne se verrouille pas. Vous pouvez le poser pour soigner &agrave; deux mains&nbsp;: le protocole sera toujours l&agrave; quand vous le reprendrez.",
    "g082": "Lire une fiche de triage",
    "g083": "Toutes les fiches sont b&acirc;ties de la m&ecirc;me fa&ccedil;on. Voici &agrave; quoi ressemble une fiche compl&egrave;te&nbsp;:",
    "g084": "Chaque partie, une par une",
    "g085": "Zone de la fiche",
    "g086": "Ce que &ccedil;a veut dire",
    "g087": "<b>Badge de gravit&eacute;</b>",
    "g088": "En haut &agrave; droite, color&eacute;. Il donne d'un coup d'&oelig;il l'urgence de la situation. Le liser&eacute; du haut de la fiche a la m&ecirc;me couleur.",
    "g089": "Le nom court de la blessure, en gros caract&egrave;res.",
    "g090": "<b>Zone touch&eacute;e</b>",
    "g091": "O&ugrave; le bless&eacute; est atteint&nbsp;: t&ecirc;te, torse, bras gauche, jambe droite...",
    "g092": "N'appara&icirc;t qu'en mode Extr&ecirc;me. Rappelle si le bless&eacute; portait un casque ou des plaques.",
    "g093": "La description de la blessure, &agrave; lire &agrave; voix haute au bless&eacute; pour le r&ocirc;le-play.",
    "g094": "<b>Protocole de soin</b>",
    "g095": "<b>La partie la plus importante</b>&nbsp;: exactement ce que vous devez faire.",
    "g096": "Attention au compte &agrave; rebours",
    "g097": "Si l'organisateur a activ&eacute; l'option hardcore, certaines blessures d&eacute;clenchent un <b>bip r&eacute;gulier</b> et un bandeau rouge <b>H&Eacute;MORRAGIE ACTIVE</b>.",
    "g098": "Vous avez alors un temps limit&eacute; pour appliquer les soins et appuyer sur <b>SOINS EFFECTU&Eacute;S</b>. Si le temps s'&eacute;coule, le bless&eacute; meurt&nbsp;: l'&eacute;cran devient noir et le bip se transforme en son continu.",
    "g099": "Les niveaux de gravit&eacute;",
    "g100": "Cinq niveaux, toujours les m&ecirc;mes, avec un code couleur constant dans toute l'application.",
    "g101": "Gravit&eacute;",
    "g102": "Ce que cela signifie pour le m&eacute;dic",
    "g103": "D&Eacute;C&Egrave;S",
    "g104": "Rien &agrave; faire. Le joueur est mort, il repart au point de r&eacute;apparition.",
    "g105": "Urgence vitale. C'est sur ces blessures que le compte &agrave; rebours se d&eacute;clenche, si l'option est active.",
    "g106": "S&eacute;rieux mais stable. Prenez le temps de bien appliquer le protocole.",
    "g107": "L&Eacute;G&Egrave;RE",
    "g108": "Bobologie. Un bandage et le joueur repart.",
    "g109": "SP&Eacute;CIAL",
    "g110": "Cas particulier, souvent li&eacute; &agrave; une protection. Lisez bien le protocole&nbsp;: il d&eacute;pend du port du casque ou du gilet.",
    "g111": "Pourquoi certaines blessures sortent plus souvent",
    "g112": "Chaque carte poss&egrave;de une <b>quantit&eacute;</b>, comme s'il y avait plusieurs exemplaires de la m&ecirc;me carte dans le paquet. Une carte en 4 exemplaires sortira deux fois plus souvent qu'une carte en 2 exemplaires. L'organisateur r&egrave;gle ces quantit&eacute;s pour donner le ton de sa partie&nbsp;: plus de bobologie, ou plus d'urgences vitales.",
    "g113": "Les modes de jeu",
    "g114": "Le mode d&eacute;termine quel jeu de cartes est utilis&eacute;. On le choisit dans les <b>R&eacute;glages</b>, ou l'organisateur l'impose en partie.",
    "g115": "Les d&eacute;butants. Soins simples&nbsp;: garrot, bandage, attelle. Id&eacute;al pour une premi&egrave;re partie.",
    "g116": "<b>Avanc&eacute;</b>",
    "g117": "Les habitu&eacute;s. Protocoles plus longs, morphine et &eacute;pin&eacute;phrine entrent en jeu.",
    "g118": "<b>Extr&ecirc;me</b>",
    "g119": "Le plus r&eacute;aliste. Vous d&eacute;signez la zone touch&eacute;e sur une silhouette, et les blessures en d&eacute;coulent. Voir le chapitre suivant.",
    "g120": "Un paquet <b>en plus</b>, pour les grenades et les explosifs. Il ajoute un second bouton rond sur l'accueil.",
    "g121": "Le cas particulier de l'explosion",
    "g122": "Le paquet Explosion contient les blessures par souffle et par &eacute;clats. Il s'active dans les R&eacute;glages, en mode Avanc&eacute; ou Extr&ecirc;me, et fait appara&icirc;tre un bouton <b>EXPLOSION</b> orange &agrave; c&ocirc;t&eacute; du bouton Balistique.",
    "g123": "Une explosion ne respecte pas les protections",
    "g124": "C'est voulu&nbsp;: contrairement aux blessures par tir, une carte explosion peut tuer un joueur <b>m&ecirc;me s'il porte un casque et des plaques</b>. Un souffle traverse la protection. Ne cherchez pas l'erreur, c'est la r&egrave;gle du jeu.",
    "g125": "Le mode Extr&ecirc;me en d&eacute;tail",
    "g126": "C'est le mode le plus immersif, et le seul o&ugrave; <b>vous</b> d&eacute;cidez de la zone touch&eacute;e au lieu de la laisser au hasard.",
    "g127": "Appuyez sur le bouton de tirage",
    "g128": "Au lieu de la fiche, une <b>silhouette humaine</b> appara&icirc;t.",
    "g129": "Touchez la zone o&ugrave; le joueur a &eacute;t&eacute; atteint",
    "g130": "T&ecirc;te, torse, bras ou jambe. <b>La vue est en miroir</b>&nbsp;: le bras droit du bless&eacute; est &agrave; votre gauche sur l'&eacute;cran, comme si vous lui faisiez face.",
    "g131": "R&eacute;pondez &agrave; la question de protection",
    "g132": "Pour la t&ecirc;te&nbsp;: &laquo;&nbsp;Casque balistique port&eacute;&nbsp;?&nbsp;&raquo;. Pour le torse&nbsp;: &laquo;&nbsp;Gilet pare-balles port&eacute;&nbsp;?&nbsp;&raquo;. Regardez le bless&eacute; et r&eacute;pondez honn&ecirc;tement.",
    "g133": "La fiche s'affiche",
    "g134": "Elle ne contient que des blessures coh&eacute;rentes avec la zone <b>et</b> avec votre r&eacute;ponse.",
    "g135": "Pourquoi la question de protection change tout",
    "g136": "La r&eacute;ponse filtre r&eacute;ellement les cartes disponibles. Un joueur casqu&eacute; ne peut pas tirer &laquo;&nbsp;Tir direct &agrave; la t&ecirc;te (sans casque)&nbsp;&raquo;&nbsp;:",
    "g137": "Zone touch&eacute;e",
    "g138": "Protection port&eacute;e",
    "g139": "Sans protection",
    "g140": "<b>T&ecirc;te</b>",
    "g141": "Impact sur casque<br/><font size='8' color='#5d5d58'>Repos 2 minutes</font>",
    "g142": "Plaie au front, traumatisme cr&acirc;nien, <b>ou tir mortel</b>",
    "g143": "Impact sur plaque, &eacute;raflure au flanc, c&ocirc;tes fractur&eacute;es",
    "g144": "Pneumothorax, h&eacute;morragie interne, <b>ou tir vital</b>",
    "g145": "<b>Bras / Jambe</b>",
    "g146": "<font color='#5d5d58'>Question non pos&eacute;e</font>",
    "g147": "Blessures propres au membre&nbsp;: une fracture du f&eacute;mur ne peut pas sortir sur un bras.",
    "g148": "La morale du mode Extr&ecirc;me",
    "g149": "Porter un casque et des plaques vous sauve r&eacute;ellement la vie dans ce mode. C'est le meilleur argument pour convaincre vos joueurs de s'&eacute;quiper correctement.",
    "g150": "Les r&eacute;glages",
    "g151": "On y acc&egrave;de par le bouton <b>curseurs</b>, en haut &agrave; droite de l'&eacute;cran. Pensez &agrave; appuyer sur <b>VALIDER</b> en bas pour conserver vos changements&nbsp;; <b>ANNULER</b> remet tout comme avant.",
    "g152": "Profil multijoueur",
    "g153": "Votre <b>pseudo</b>. C'est le nom sous lequel l'organisateur vous verra. Mettez-le avant de rejoindre une partie&nbsp;: c'est plus simple pour tout le monde.",
    "g154": "Classique, Avanc&eacute;, Extr&ecirc;me, ou l'un de vos paquets personnels. En partie, ce r&eacute;glage est verrouill&eacute;&nbsp;: c'est l'organisateur qui d&eacute;cide.",
    "g155": "Option hardcore : le risque de mort",
    "g156": "Une fois coch&eacute;e, quatre r&eacute;glages apparaissent&nbsp;:",
    "g157": "R&eacute;glage",
    "g158": "<b>Probabilit&eacute;</b>",
    "g159": "Les chances qu'une blessure d&eacute;clenche le compte &agrave; rebours. 40&nbsp;% par d&eacute;faut&nbsp;: environ une blessure critique sur deux.",
    "g160": "<b>D&eacute;lai mini</b>",
    "g161": "Le temps le plus court dont dispose le m&eacute;dic. 30 secondes par d&eacute;faut.",
    "g162": "<b>D&eacute;lai maxi</b>",
    "g163": "Le temps le plus long. 60 secondes par d&eacute;faut. Le d&eacute;lai r&eacute;el est tir&eacute; au hasard entre les deux, et le m&eacute;dic ne le voit pas.",
    "g164": "<b>&Eacute;tendre aux Graves</b>",
    "g165": "Par d&eacute;faut, seules les blessures Critiques peuvent tuer. Cochez pour durcir nettement la partie.",
    "g166": "Mat&eacute;riel requis",
    "g167": "Cette liste ne suit pas le contenu de votre trousse au fil de la partie. Elle d&eacute;finit <b>quels types de soins sont en jeu</b>&nbsp;: on d&eacute;coche le mat&eacute;riel dont on ne dispose pas, et l'application cesse de tirer les blessures qui l'exigent.",
    "g168": "C'est un r&eacute;glage de <b>pr&eacute;paration</b>, pas un r&eacute;glage de terrain&nbsp;: il se fait avant la partie, et normalement par l'organisateur.",
    "g169": "Un joueur ne retire pas de cartes du jeu",
    "g170": "En partie, vos r&eacute;glages sont <b>verrouill&eacute;s</b>&nbsp;: c'est l'organisateur qui d&eacute;cide du mat&eacute;riel et des quantit&eacute;s, pour que tous les m&eacute;dics jouent le m&ecirc;me paquet. Vous ne pouvez donc pas &eacute;carter une blessure parce qu'elle vous arrange mal.",
    "g171": "En solo, en revanche, vous configurez librement votre propre jeu.",
    "g172": "<b>Exemple.</b> Aucun m&eacute;dic de l'&eacute;v&eacute;nement n'a de pansement 3 c&ocirc;t&eacute;s&nbsp;? L'organisateur d&eacute;coche ce mat&eacute;riel avant la partie&nbsp;: la plaie soufflante et le pneumothorax disparaissent du paquet pour tout le monde.",
    "g173": "Cartes actives",
    "g174": "La liste compl&egrave;te des blessures du mode, <b>tri&eacute;es par gravit&eacute;</b>&nbsp;: d&eacute;c&egrave;s d'abord, puis critiques, graves, l&eacute;g&egrave;res et sp&eacute;ciales. Pour chaque carte&nbsp;:",
    "g175": "l'&oelig;il ouvre le <b>catalogue</b> et vous montre la carte en entier&nbsp;;",
    "g176": "les boutons <b>&ndash;</b> et <b>+</b> r&egrave;glent sa quantit&eacute; dans le paquet&nbsp;;",
    "g177": "le <b>pourcentage</b> &agrave; droite indique ses chances de sortir. Il se met &agrave; jour tout seul&nbsp;;",
    "g178": "une ligne <b>gris&eacute;e</b> signifie que le mat&eacute;riel manque&nbsp;: cette carte ne sortira pas.",
    "g179": "R&eacute;gler une carte &agrave; z&eacute;ro",
    "g180": "Mettre la quantit&eacute; &agrave; 0 retire compl&egrave;tement la carte du paquet. C'est la fa&ccedil;on propre d'&eacute;carter une blessure qui ne vous pla&icirc;t pas, sans toucher au reste.",
    "g181": "Cr&eacute;er vos propres paquets de cartes",
    "g182": "Le bouton <b>crayon</b> en haut &agrave; droite ouvre &laquo;&nbsp;Mes paquets&nbsp;&raquo;. Vous pouvez y b&acirc;tir vos propres blessures&nbsp;: contamination chimique, radiations, morsures, ce que votre sc&eacute;nario demande.",
    "g183": "Cr&eacute;er un paquet",
    "g184": "Donnez-lui un nom. Cochez <b>Afficher sur l'accueil</b> pour qu'il ait son propre bouton rond.",
    "g185": "Ajouter des cartes",
    "g186": "Pour chacune&nbsp;: une gravit&eacute;, un titre, une zone, une condition de protection, un protocole de soin.",
    "g187": "Choisir le mat&eacute;riel requis",
    "g188": "Touchez les puces correspondantes. Vous pouvez cr&eacute;er du mat&eacute;riel qui n'existe pas dans la liste de base &mdash; &laquo;&nbsp;Anti-rad&nbsp;&raquo;, &laquo;&nbsp;S&eacute;rum&nbsp;&raquo;...",
    "g189": "Choisir l'ic&ocirc;ne du bouton",
    "g190": "Une trentaine de pictogrammes au choix&nbsp;: balle, grenade, explosion, biohazard, radiation, zombie, cr&eacute;ature, robot, seringue, cachets, perfusion... Elle identifie le paquet sur l'accueil, et suit le paquet quand vous le partagez ou l'attribuez en partie.",
    "g191": "Le paquet appara&icirc;t sur votre accueil, pr&ecirc;t &agrave; l'emploi.",
    "g192": "Partager un paquet avec quelqu'un",
    "g193": "Le bouton <b>partage</b> sur une carte de paquet produit un long code commen&ccedil;ant par <b>TMDECK1</b>. Envoyez-le par SMS ou messagerie&nbsp;; le destinataire utilise <b>Importer un paquet</b> et colle le code. Il re&ccedil;oit toutes les cartes et le mat&eacute;riel associ&eacute;.",
    "g194": "L'option &laquo;&nbsp;mode extr&ecirc;me&nbsp;&raquo; du paquet",
    "g195": "Coch&eacute;e, votre paquet personnel d&eacute;clenche lui aussi la silhouette et la question de protection, comme le mode Extr&ecirc;me officiel.",
    "g196": "Pendant une partie, vos paquets sont mis de c&ocirc;t&eacute;",
    "g197": "Quand vous rejoignez une partie, l'organisateur impose sa configuration&nbsp;: vos paquets personnels disparaissent temporairement et la cr&eacute;ation est bloqu&eacute;e. <b>Ils vous sont rendus int&eacute;gralement d&egrave;s que vous quittez la partie.</b> Rien n'est perdu.",
    "g198": "Jouer &agrave; plusieurs : l'organisateur",
    "g199": "L'organisateur cr&eacute;e la partie et pilote ce que chaque joueur va tirer. Le bouton <b>multijoueur</b> se trouve en haut &agrave; droite.",
    "g200": "Ouvrez le menu multijoueur",
    "g201": "Le premier bouton en haut &agrave; droite, avec les deux silhouettes.",
    "g202": "Donnez un nom &agrave; la partie",
    "g203": "Par exemple &laquo;&nbsp;Exercice Alpha&nbsp;&raquo;. C'est ce nom que vos joueurs taperont pour vous rejoindre.",
    "g204": "Indiquez votre pseudo",
    "g205": "Le nom sous lequel vous appara&icirc;trez.",
    "g206": "Laissez la liaison sur &laquo;&nbsp;Serveur Firebase&nbsp;&raquo;",
    "g207": "C'est le r&eacute;glage recommand&eacute;. Il fonctionne entre r&eacute;seaux diff&eacute;rents (la 4G d'un joueur et le WiFi d'un autre) et vous permet de fermer votre page sans couper la partie.",
    "g208": "Appuyez sur CR&Eacute;ER UNE PARTIE",
    "g209": "Le <b>QG</b> s'ouvre&nbsp;: c'est votre tableau de bord.",
    "g210": "Inviter les joueurs",
    "g211": "L'onglet <b>Invitation</b> affiche un <b>QR code</b> et un lien. Trois fa&ccedil;ons de faire venir vos joueurs, de la plus simple &agrave; la plus manuelle&nbsp;:",
    "g212": "ils <b>scannent le QR code</b> depuis leur application&nbsp;: c'est imm&eacute;diat&nbsp;;",
    "g213": "vous leur envoyez le <b>lien</b> par messagerie, avec le bouton <b>Copier</b> de la ligne du lien&nbsp;;",
    "g214": "vous leur donnez le <b>code de la partie</b> seul &mdash; le bouton <b>Copier</b> plac&eacute; &agrave; c&ocirc;t&eacute; le met dans le presse-papiers, pratique pour le dicter ou l'envoyer sans le lien complet&nbsp;;",
    "g215": "ils <b>tapent le code</b> dans leur menu Rejoindre.",
    "g216": "Vous pouvez fermer votre t&eacute;l&eacute;phone",
    "g217": "Avec la liaison Firebase, la partie vit sur le serveur, pas dans votre t&eacute;l&eacute;phone. Vous pouvez fermer l'application, verrouiller votre &eacute;cran, ou m&ecirc;me red&eacute;marrer votre appareil&nbsp;: en rouvrant l'application, vous retrouvez votre QG, vos joueurs et votre journal.",
    "g218": "C'est la diff&eacute;rence majeure avec l'ancienne liaison pair-&agrave;-pair, o&ugrave; votre page devait rester ouverte en permanence.",
    "g219": "D&eacute;cider ce que chaque &eacute;quipe va tirer",
    "g220": "C'est le c&oelig;ur du r&ocirc;le d'organisateur, dans l'onglet <b>Paquets</b>.",
    "g221": "Choisissez un paquet",
    "g222": "Classique, Avanc&eacute;, Extr&ecirc;me, Explosion, ou l'un de vos paquets personnels.",
    "g223": "Choisissez qui le re&ccedil;oit",
    "g224": "Tout le monde, une &eacute;quipe seulement, ou un joueur pr&eacute;cis.",
    "g225": "Appuyez sur AJOUTER CE PAQUET",
    "g226": "Il appara&icirc;t imm&eacute;diatement sur l'accueil des destinataires.",
    "g227": "Le paquet attribu&eacute; remplace le mode",
    "g228": "Un joueur qui re&ccedil;oit &laquo;&nbsp;Classique&nbsp;&raquo; ne tirera <b>que</b> du Classique. Il ne garde ni le mode de la partie, ni les cartes explosion, ni ses paquets personnels.",
    "g229": "Un joueur &agrave; qui vous n'attribuez <b>rien</b> joue le mode en cours, celui que vous avez d&eacute;fini dans l'onglet &Eacute;diteur.",
    "g230": "Exemple concret",
    "g231": "Vous voulez que les m&eacute;dics exp&eacute;riment&eacute;s de l'&eacute;quipe Rouge affrontent du lourd, pendant que les d&eacute;butants de l'&eacute;quipe Bleue apprennent&nbsp;:",
    "g232": "Paquet attribu&eacute;",
    "g233": "R&eacute;sultat",
    "g234": "&Eacute;quipe Bleue",
    "g235": "Soins simples, apprentissage en douceur.",
    "g236": "&Eacute;quipe Rouge",
    "g237": "Extr&ecirc;me",
    "g238": "Silhouette, protections, protocoles longs.",
    "g239": "Jouer &agrave; plusieurs : le joueur",
    "g240": "Beaucoup plus simple&nbsp;: vous n'avez presque rien &agrave; faire.",
    "g241": "La fa&ccedil;on la plus simple&nbsp;: <b>ouvrir le lien d'invitation</b> de l'organisateur.",
    "g242": "Ouvrez le lien re&ccedil;u",
    "g243": "Par SMS, messagerie, ou en scannant le QR code. Il s'ouvre dans votre navigateur, ou directement dans l'application si elle est install&eacute;e.",
    "g244": "Indiquez votre pseudo et votre &eacute;quipe",
    "g245": "L'application est d&eacute;j&agrave; rattach&eacute;e &agrave; la partie&nbsp;: elle vous demande seulement sous quel nom vous jouez et dans quelle &eacute;quipe.",
    "g246": "Votre accueil se met &agrave; jour avec les paquets qu'on vous a attribu&eacute;s.",
    "g247": "Sans le lien",
    "g248": "Ouvrez le menu multijoueur",
    "g249": "Le bouton avec les deux silhouettes, en haut &agrave; droite.",
    "g250": "Appuyez sur REJOINDRE UNE PARTIE",
    "g251": "La section se d&eacute;plie&nbsp;: scannez le QR code de l'organisateur, ou tapez le code de la partie. Un nouvel appui la replie.",
    "g252": "Indiquez votre pseudo et votre &eacute;quipe",
    "g253": "La liste des &eacute;quipes est celle cr&eacute;&eacute;e par l'organisateur.",
    "g254": "Ce qui change une fois en partie",
    "g255": "le bandeau du haut affiche votre <b>&eacute;quipe</b> et le <b>nom de la partie</b>&nbsp;;",
    "g256": "un bouton <b>SORTIR</b> appara&icirc;t en haut&nbsp;;",
    "g257": "vos <b>r&eacute;glages sont verrouill&eacute;s</b>&nbsp;: c'est l'organisateur qui d&eacute;cide du mode, du mat&eacute;riel et des quantit&eacute;s&nbsp;;",
    "g258": "chacun de vos tirages appara&icirc;t dans le <b>journal</b> de l'organisateur.",
    "g259": "Si vous perdez le r&eacute;seau",
    "g260": "L'application se reconnecte toute seule d&egrave;s que le r&eacute;seau revient. Pendant la coupure, vous <b>conservez vos cartes attribu&eacute;es</b> et pouvez continuer &agrave; tirer&nbsp;: seuls le journal et les changements d&eacute;cid&eacute;s par l'organisateur attendront le retour du signal.",
    "g261": "Le bouton SORTIR est d&eacute;finitif",
    "g262": "Quitter la partie efface votre identit&eacute; de session. Si vous revenez, vous serez un nouveau joueur&nbsp;: l'organisateur devra vous redonner votre &eacute;quipe et, le cas &eacute;ch&eacute;ant, votre grade de co-organisateur. Pour une simple pause, <b>fermez l'application sans appuyer sur Sortir</b>.",
    "g263": "Le QG, onglet par onglet",
    "g264": "Le QG est le tableau de bord de l'organisateur. Six onglets, chacun avec un r&ocirc;le pr&eacute;cis.",
    "g265": "&Agrave; quoi il sert",
    "g266": "Le nom de la partie, le QR code et le lien &agrave; partager. C'est l&agrave; que vous envoyez vos joueurs.",
    "g267": "La liste des connect&eacute;s. Pour chacun&nbsp;: changer son &eacute;quipe d'un appui, le passer <b>Admin</b>, ou le <b>Kick</b>. Les joueurs hors ligne restent affich&eacute;s en gris&eacute;.",
    "g268": "<b>&Eacute;quipes</b>",
    "g269": "Cr&eacute;er ou supprimer des &eacute;quipes, avec leur couleur. Minimum deux. Supprimer une &eacute;quipe replace automatiquement ses joueurs ailleurs.",
    "g270": "<b>&Eacute;diteur</b>",
    "g271": "R&eacute;gler chaque paquet <b>avant</b> de le distribuer&nbsp;: quantit&eacute;s, mat&eacute;riel, risque de mort. Le mode marqu&eacute; <b>JOU&Eacute;</b> est celui des joueurs sans attribution.",
    "g272": "Attribuer un paquet &agrave; tout le monde, &agrave; une &eacute;quipe ou &agrave; un joueur. La liste du bas montre ce qui est distribu&eacute;, avec une corbeille pour retirer.",
    "g273": "Le journal en temps r&eacute;el&nbsp;: qui a rejoint, qui a tir&eacute; quelle blessure, &agrave; quelle heure et dans quelle <b>&eacute;quipe</b>. T&eacute;l&eacute;chargeable en fichier texte.",
    "g274": "Le co-organisateur",
    "g275": "Passer un joueur <b>Admin</b> lui donne acc&egrave;s au m&ecirc;me QG que vous. Il peut d&eacute;placer des joueurs, distribuer des paquets, cr&eacute;er des &eacute;quipes. Tr&egrave;s pratique sur un grand terrain o&ugrave; vous ne pouvez pas &ecirc;tre partout.",
    "g276": "Personne ne peut se promouvoir tout seul",
    "g277": "Le grade d'administrateur ne peut &ecirc;tre donn&eacute; que par vous ou par un co-organisateur existant, et cette r&egrave;gle est appliqu&eacute;e <b>par le serveur</b>. M&ecirc;me un joueur qui conna&icirc;trait parfaitement l'application ne peut pas se l'attribuer, ni prendre l'identit&eacute; de quelqu'un d'autre en copiant son pseudo.",
    "g278": "Cl&ocirc;turer la partie",
    "g279": "Le bouton rouge en bas du QG pr&eacute;vient tous les joueurs et les d&eacute;connecte. <b>Pensez &agrave; t&eacute;l&eacute;charger vos logs avant</b> si vous voulez garder une trace de la partie.",
    "g280": "Sur le terrain : conseils pratiques",
    "g281": "Avant la partie",
    "g282": "faites <b>ouvrir l'application une fois avec du r&eacute;seau</b> &agrave; tous les m&eacute;dics, au briefing&nbsp;;",
    "g283": "demandez-leur d'<b>installer l'ic&ocirc;ne</b> sur leur &eacute;cran d'accueil&nbsp;;",
    "g284": "faites-leur r&eacute;gler leur <b>pseudo</b> avant de rejoindre&nbsp;;",
    "g285": "cr&eacute;ez la partie et testez la connexion <b>avec un t&eacute;l&eacute;phone</b> avant l'arriv&eacute;e de tout le monde&nbsp;;",
    "g286": "r&eacute;glez vos quantit&eacute;s dans l'onglet <b>&Eacute;diteur</b> avant de distribuer les paquets.",
    "g287": "Pendant la partie",
    "g288": "gardez le QG ouvert sur l'onglet <b>Logs</b> pour suivre l'activit&eacute; en direct&nbsp;;",
    "g289": "si un type de soin s'av&egrave;re introuvable sur le terrain, retirez son mat&eacute;riel depuis l'onglet <b>&Eacute;diteur</b>&nbsp;: le changement s'applique aussit&ocirc;t &agrave; tous les joueurs&nbsp;;",
    "g290": "pour durcir en cours de partie, augmentez la probabilit&eacute; du risque de mort&nbsp;: le changement est imm&eacute;diat chez tous les joueurs&nbsp;;",
    "g291": "d&eacute;signez un <b>co-organisateur</b> si le terrain est grand.",
    "g292": "Apr&egrave;s la partie",
    "g293": "<b>t&eacute;l&eacute;chargez les logs</b> avant de cl&ocirc;turer&nbsp;: excellent support de d&eacute;briefing&nbsp;;",
    "g294": "cl&ocirc;turez proprement pour lib&eacute;rer le nom de la partie.",
    "g295": "L'&eacute;cran reste allum&eacute; pendant l'affichage d'une fiche, et la connexion permanente consomme. Sur une journ&eacute;e compl&egrave;te, pr&eacute;voyez une <b>batterie externe</b> pour l'organisateur et pour les m&eacute;dics les plus sollicit&eacute;s.",
    "g296": "En cas de probl&egrave;me",
    "g297": "Sympt&ocirc;me",
    "g298": "<b>L'application ne s'ouvre pas hors r&eacute;seau</b>",
    "g299": "Elle n'a jamais &eacute;t&eacute; ouverte avec du r&eacute;seau sur cet appareil. Reconnectez-vous une fois, laissez-la charger enti&egrave;rement, puis elle fonctionnera hors ligne.",
    "g300": "<b>&laquo;&nbsp;Partie introuvable&nbsp;&raquo;</b>",
    "g301": "V&eacute;rifiez l'orthographe exacte du nom aupr&egrave;s de l'organisateur. Les accents et les espaces n'ont pas d'importance, mais les lettres si. Le plus s&ucirc;r reste le QR code.",
    "g302": "<b>&laquo;&nbsp;Aucune carte disponible&nbsp;&raquo;</b>",
    "g303": "Toutes les cartes sont soit &agrave; z&eacute;ro, soit bloqu&eacute;es par du mat&eacute;riel manquant. En solo, ouvrez les R&eacute;glages et recochez du mat&eacute;riel. En partie, signalez-le &agrave; l'organisateur&nbsp;: lui seul peut y toucher.",
    "g304": "<b>Un joueur appara&icirc;t en double</b>",
    "g305": "Deux joueurs ont le m&ecirc;me pseudo&nbsp;: le second devient automatiquement &laquo;&nbsp;Nom (2)&nbsp;&raquo;. Demandez-lui de changer de pseudo, ou laissez comme &ccedil;a.",
    "g306": "<b>Un joueur reste &laquo;&nbsp;hors ligne&nbsp;&raquo;</b>",
    "g307": "Son t&eacute;l&eacute;phone a perdu le r&eacute;seau. Il revient tout seul. S'il est vraiment parti, retirez-le avec le bouton Kick.",
    "g308": "<b>Je ne retrouve plus mes paquets perso</b>",
    "g309": "Vous &ecirc;tes en partie&nbsp;: ils sont mis de c&ocirc;t&eacute; et vous seront rendus en quittant. Rien n'est perdu.",
    "g310": "<b>L'affichage semble ancien</b>",
    "g311": "Fermez compl&egrave;tement l'application et rouvrez-la avec du r&eacute;seau&nbsp;: elle se met &agrave; jour toute seule.",
    "g312": "<font color=\"white\" size=\"11\"><b>Bon jeu, et bons soins.</b></font><br/><font color=\"#c49708\" size=\"9\">Bravo Sierra Events // Frontline</font>",
    "g313": "BSE Medical System - Guide d'utilisation",
    "g314": "Bravo Sierra Events",
    "g315": "Guide d'utilisation de l'application BSE Medical System",
    "g316": "PDF genere :",
    "g317": "taille     :",
}
