# -*- coding: utf-8 -*-
"""Guide BSE Medical System — textes ESPAGNOLS.

   Meme jeu de cles que guide-fr.py, qui est la reference.
   Le balisage <b>, <br/> et <font> doit etre conserve tel quel.
"""
TEXTES = {
    "m08": "Guardar",
    "m09": "Una sola carta para varios miembros",
    "m10": "La zona se elige en una lista: cabeza, torso, brazo derecho, brazo izquierdo, pierna derecha, pierna izquierda &mdash; pero tambi&eacute;n <b>los dos brazos</b>, <b>las dos piernas</b> o <b>los cuatro miembros</b>. Un rasgu&ntilde;o en los cuatro miembros cabe entonces en <b>una sola carta</b> en vez de cuatro: la zona exacta se saca al azar en el momento del diagn&oacute;stico y, en modo Extremo, es la que has se&ntilde;alado en la silueta. “Zona personalizada” sigue ah&iacute; para escribir lo que quieras. Tres botones <b>Protecci&oacute;n bal&iacute;stica</b> completan el cuadro: la carta puede salir solo <b>con</b> el casco o el chaleco, solo <b>sin</b> ellos, o en ambos casos. As&iacute; se opone “impacto en el casco” a “disparo en la cabeza”.",
    "m07": "abajo del todo: a la izquierda la <b>elecci&oacute;n del idioma</b>, a la derecha los enlaces a <b>Bravo Sierra Events</b> &mdash; web, Discord, Instagram, YouTube y Facebook.",
    "m01": "Torso",
    "m02": "PROTECCIÓN",
    "m03": "EVALUACIÓN",
    "m04": "Título",
    "m05": "Protección",
    "m06": "Evaluación",
    "chapitre_apres": "",
    "chapitre": "CAPÍTULO",
    "g001": "<font size=\"7\" color=\"#8a8a84\">FICHA DE TRIAJE</font>",
    "g002": "<font size=\"8\" color=\"white\"><b> CRÍTICA </b></font>",
    "g003": "HEMORRAGIA INTERNA",
    "g004": "ZONA ALCANZADA",
    "g005": "Placas balísticas puestas: NO",
    "g006": "Herida perforante en el abdomen que provoca<br/>una fuerte hemorragia interna.",
    "g007": "PROTOCOLO DE CUIDADOS",
    "g008": "Vendaje + Bolsa de sangre<br/>+ Adrenalina",
    "g009": "BSE MEDICAL SYSTEM  //  GUÍA DE USO",
    "g010": "Bravo Sierra Events",
    "g011": "BSE MEDICAL SYSTEM",
    "g012": "FRONTLINE  //  FIELD APPLICATION",
    "g013": "<font color=\"white\" size=\"15\"><b>Guía de uso</b></font>",
    "g014": "<font color=\"#9b9b96\" size=\"10.5\">Para descubrir la aplicación sin saber nada de entrada</font>",
    "g015": "<font color=\"#c49708\" size=\"9\">https://project-bsm-7d32c.web.app</font>",
    "g016": "Para qué sirve esta aplicación",
    "g017": "Instalar la aplicación en el móvil",
    "g018": "Tu primer diagnóstico",
    "g019": "Leer una ficha de triaje",
    "g020": "Los niveles de gravedad",
    "g021": "Los modos de juego",
    "g022": "El modo Extremo en detalle",
    "g023": "Los ajustes",
    "g024": "Crear tus propios mazos de cartas",
    "g025": "Jugar entre varios: el organizador",
    "g026": "Jugar entre varios: el jugador",
    "g027": "El CG, pestaña a pestaña",
    "g028": "Sobre el terreno: consejos prácticos",
    "g029": "Si algo va mal",
    "g030": "A quién va dirigida esta guía",
    "g031": "¿Nunca has abierto la aplicación? Eres exactamente la persona indicada. Esta guía parte de cero y no espera ningún conocimiento previo, ni de airsoft médico ni de informática. Lee los capítulos 1 a 5 para jugar esta misma tarde; el resto te servirá cuando quieras organizar una partida.",
    "g032": "Para qué sirve esta aplicación",
    "g033": "BSE Medical System sustituye la baraja de cartas de papel que los médicos de airsoft llevan en el bolsillo. Cuando alcanzan a un jugador, el médico saca el móvil, pulsa un botón y la aplicación saca una herida al azar con su protocolo de cuidados.",
    "g034": "Se acabaron las cartas mojadas, perdidas o desordenadas. Y sobre todo: el organizador puede decidir a distancia qué robará cada equipo.",
    "g035": "El principio, en cuatro tiempos",
    "g036": "Alcanzan a un jugador",
    "g037": "Se tira al suelo y llama a un médico.",
    "g038": "El médico llega y abre la aplicación",
    "g039": "Pulsa el botón redondo grande del centro de la pantalla.",
    "g040": "La aplicación saca una herida",
    "g041": "Aparece una ficha: la zona alcanzada, la gravedad y los cuidados que hay que aplicar.",
    "g042": "El médico aplica el protocolo",
    "g043": "Torniquete, vendaje, férula... según lo que indique la ficha. El herido vuelve luego al juego.",
    "g044": "El material sigue siendo real",
    "g045": "La aplicación no sustituye tu botiquín. Te dice <b>qué hacer</b>; poner el torniquete de atrezo y el vendaje de verdad es cosa tuya. Si un tipo de cuidado no está disponible en el evento &mdash; nadie tiene apósito de 3 lados, por ejemplo &mdash; el organizador lo retira del juego <b>antes</b> de la partida, y las heridas que lo exigen dejan de salir.",
    "g046": "Instalar la aplicación en el móvil",
    "g047": "No hay nada que descargar de una tienda de aplicaciones. Todo pasa por tu navegador de siempre.",
    "g048": "Abre la dirección en tu navegador",
    "g049": "<b>https://project-bsm-7d32c.web.app</b> &mdash; Chrome en Android, Safari en iPhone.",
    "g050": "Añade la aplicación a la pantalla de inicio",
    "g051": "En <b>Android</b>: menú de los “tres puntos” y luego “Instalar aplicación” o “Añadir a la pantalla de inicio”.<br/>En <b>iPhone</b>: botón Compartir (el cuadrado con la flecha) y luego “Añadir a pantalla de inicio”.",
    "g052": "Ábrela desde el icono",
    "g053": "Aparece una cruz médica dorada sobre fondo negro junto a tus otras aplicaciones. Se abre a pantalla completa, sin barra de direcciones.",
    "g054": "Hazlo en el briefing, no sobre el terreno",
    "g055": "Cada móvil debe abrir la aplicación <b>una vez con cobertura</b>. La aplicación se guarda entonces por completo en el aparato.",
    "g056": "Una vez hecha esa primera apertura, funciona <b>sin ninguna cobertura</b>: puedes sacar heridas en medio del bosque, en modo avión. Solo el juego entre varios necesita conexión.",
    "g057": "Lo que ves al llegar",
    "g058": "La pantalla de inicio se llama <b>DIAGNÓSTICO MÉDICO</b>. En ella encuentras:",
    "g059": "uno o varios <b>botones redondos grandes</b> en el centro: son tus tiradas disponibles;",
    "g060": "una franja <b>MAZO ACTIVO</b> abajo, que indica cuántas cartas hay en juego;",
    "g061": "arriba a la derecha, tres botones: <b>multijugador</b>, <b>mis mazos</b> y <b>ajustes</b>;",
    "g062": "arriba, una franja gris con tu nombre de jugador y tu equipo.",
    "g063": "Tu primer diagnóstico",
    "g064": "Es el uso principal de la aplicación, y el más sencillo.",
    "g065": "Pulsa el botón redondo",
    "g066": "El más habitual se llama <b>BALÍSTICA</b>: es una herida por disparo.",
    "g067": "Espera el análisis",
    "g068": "Una evaluación <b>MARCH</b> pasa durante unos segundos. Es el tiempo del diagnóstico; aprovéchalo para observar al herido.",
    "g069": "Lee la ficha",
    "g070": "Indica la gravedad, la zona alcanzada y el protocolo que hay que aplicar.",
    "g071": "Aplica los cuidados y pulsa “Nuevo diagnóstico”",
    "g072": "Vuelves al inicio, listo para el siguiente herido.",
    "g073": "¿Qué significa MARCH?",
    "g074": "Es el orden en el que un socorrista examina a un herido, de lo más mortal a lo menos urgente. La aplicación lo muestra para meterte en situación:",
    "g075": "<b>Massive bleeding</b> &mdash; primero las hemorragias masivas",
    "g076": "<b>Airways</b> &mdash; las vías respiratorias",
    "g077": "<b>Respiration</b> &mdash; la ventilación",
    "g078": "<b>Circulation</b> &mdash; el pulso, el shock",
    "g079": "<b>Head / Hypothermia</b> &mdash; la cabeza y el enfriamiento",
    "g080": "La pantalla se queda encendida",
    "g081": "Mientras haya una ficha en pantalla, el móvil no se bloquea. Puedes dejarlo para curar con las dos manos: el protocolo seguirá ahí cuando lo vuelvas a coger.",
    "g082": "Leer una ficha de triaje",
    "g083": "Todas las fichas están construidas igual. Así es una ficha completa:",
    "g084": "Cada parte, una a una",
    "g085": "Zona de la ficha",
    "g086": "Qué significa",
    "g087": "<b>Distintivo de gravedad</b>",
    "g088": "Arriba a la derecha, en color. Da de un vistazo la urgencia de la situación. El filete superior de la ficha tiene el mismo color.",
    "g089": "El nombre corto de la herida, en letra grande.",
    "g090": "<b>Zona alcanzada</b>",
    "g091": "Dónde está herido: cabeza, torso, brazo izquierdo, pierna derecha...",
    "g092": "Solo aparece en modo Extremo. Recuerda si el herido llevaba casco o placas.",
    "g093": "La descripción de la herida, para leérsela en voz alta al herido en el rol.",
    "g094": "<b>Protocolo de cuidados</b>",
    "g095": "<b>La parte más importante</b>: exactamente lo que debes hacer.",
    "g096": "Cuidado con la cuenta atrás",
    "g097": "Si el organizador ha activado la opción hardcore, algunas heridas disparan un <b>pitido regular</b> y una franja roja <b>HEMORRAGIA ACTIVA</b>.",
    "g098": "Tienes entonces un tiempo limitado para aplicar los cuidados y pulsar <b>CUIDADOS REALIZADOS</b>. Si se agota el tiempo, el herido muere: la pantalla se pone negra y el pitido se vuelve continuo.",
    "g099": "Los niveles de gravedad",
    "g100": "Cinco niveles, siempre los mismos, con un código de color constante en toda la aplicación.",
    "g101": "Gravedad",
    "g102": "Qué significa para el médico",
    "g103": "MUERTE",
    "g104": "Nada que hacer. El jugador ha muerto y vuelve al punto de reaparición.",
    "g105": "Urgencia vital. Es en estas heridas donde se dispara la cuenta atrás, si la opción está activa.",
    "g106": "Serio pero estable. Tómate el tiempo de aplicar bien el protocolo.",
    "g107": "LEVE",
    "g108": "Poca cosa. Un vendaje y el jugador se va.",
    "g109": "ESPECIAL",
    "g110": "Caso particular, casi siempre ligado a una protección. Lee bien el protocolo: depende de si se llevaba casco o chaleco.",
    "g111": "Por qué algunas heridas salen más a menudo",
    "g112": "Cada carta tiene una <b>cantidad</b>, como si hubiera varios ejemplares de la misma carta en el mazo. Una carta con 4 ejemplares saldrá el doble de veces que una con 2. El organizador ajusta esas cantidades para dar el tono a su partida: más heridas leves, o más urgencias vitales.",
    "g113": "Los modos de juego",
    "g114": "El modo determina qué baraja se usa. Se elige en los <b>Ajustes</b>, o lo impone el organizador en partida.",
    "g115": "Para principiantes. Cuidados sencillos: torniquete, vendaje, férula. Ideal para una primera partida.",
    "g116": "<b>Avanzado</b>",
    "g117": "Para los habituales. Protocolos más largos, entran en juego la morfina y la adrenalina.",
    "g118": "<b>Extremo</b>",
    "g119": "El más realista. Señalas la zona alcanzada sobre una silueta, y las heridas salen de ahí. Ver el capítulo siguiente.",
    "g120": "Un mazo <b>adicional</b>, para granadas y explosivos. Añade un segundo botón redondo en el inicio.",
    "g121": "El caso particular de la explosión",
    "g122": "El mazo Explosión contiene las heridas por onda expansiva y por metralla. Se activa en los Ajustes, en modo Avanzado o Extremo, y hace aparecer un botón <b>EXPLOSIÓN</b> naranja junto al botón Balística.",
    "g123": "Una explosión no respeta las protecciones",
    "g124": "Es deliberado: a diferencia de las heridas por disparo, una carta de explosión puede matar a un jugador <b>aunque lleve casco y placas</b>. Una onda expansiva atraviesa la protección. No busques el error: es la regla del juego.",
    "g125": "El modo Extremo en detalle",
    "g126": "Es el modo más inmersivo, y el único en el que <b>tú</b> decides la zona alcanzada en vez de dejarla al azar.",
    "g127": "Pulsa el botón de tirada",
    "g128": "En lugar de la ficha, aparece una <b>silueta humana</b>.",
    "g129": "Toca la zona donde han alcanzado al jugador",
    "g130": "Cabeza, torso, brazo o pierna. <b>La vista está en espejo</b>: el brazo derecho del herido está a tu izquierda en la pantalla, como si estuvieras frente a él.",
    "g131": "Responde a la pregunta de protección",
    "g132": "Para la cabeza: “¿Casco balístico puesto?”. Para el torso: “¿Chaleco antibalas puesto?”. Mira al herido y responde con honestidad.",
    "g133": "Aparece la ficha",
    "g134": "Solo contiene heridas coherentes con la zona <b>y</b> con tu respuesta.",
    "g135": "Por qué la pregunta de protección lo cambia todo",
    "g136": "La respuesta filtra realmente las cartas disponibles. Un jugador con casco no puede sacar “Disparo directo a la cabeza (sin casco)”:",
    "g137": "Zona alcanzada",
    "g138": "Protección puesta",
    "g139": "Sin protección",
    "g140": "<b>Cabeza</b>",
    "g141": "Impacto en el casco<br/><font size='8' color='#5d5d58'>Reposo de 2 minutos</font>",
    "g142": "Herida en la frente, traumatismo craneal, <b>o disparo mortal</b>",
    "g143": "Impacto en la placa, rasguño en el costado, costillas fracturadas",
    "g144": "Neumotórax, hemorragia interna, <b>o disparo vital</b>",
    "g145": "<b>Brazo / Pierna</b>",
    "g146": "<font color='#5d5d58'>No se hace la pregunta</font>",
    "g147": "Heridas propias del miembro: una fractura de fémur no puede salir en un brazo.",
    "g148": "La moraleja del modo Extremo",
    "g149": "Llevar casco y placas te salva realmente la vida en este modo. Es el mejor argumento para convencer a tus jugadores de equiparse bien.",
    "g150": "Los ajustes",
    "g151": "Se llega a ellos por el botón de los <b>deslizadores</b>, arriba a la derecha de la pantalla. Acuérdate de pulsar <b>VALIDAR</b> abajo para conservar tus cambios; <b>CANCELAR</b> lo deja todo como estaba.",
    "g152": "Perfil multijugador",
    "g153": "Tu <b>nombre de jugador</b>. Es el nombre con el que te verá el organizador. Ponlo antes de unirte a una partida: es más sencillo para todos.",
    "g154": "Clásico, Avanzado, Extremo o uno de tus mazos propios. En partida este ajuste está bloqueado: decide el organizador.",
    "g155": "Opción hardcore: el riesgo de muerte",
    "g156": "Una vez marcada, aparecen cuatro ajustes:",
    "g157": "Ajuste",
    "g158": "<b>Probabilidad</b>",
    "g159": "Las opciones de que una herida dispare la cuenta atrás. 40% por defecto: aproximadamente una herida crítica de cada dos.",
    "g160": "<b>Tiempo mínimo</b>",
    "g161": "El tiempo más corto del que dispone el médico. 30 segundos por defecto.",
    "g162": "<b>Tiempo máximo</b>",
    "g163": "El tiempo más largo. 60 segundos por defecto. El tiempo real se saca al azar entre los dos, y el médico no lo ve.",
    "g164": "<b>Extender a las Graves</b>",
    "g165": "Por defecto, solo las heridas Críticas pueden matar. Márcalo para endurecer claramente la partida.",
    "g166": "Material necesario",
    "g167": "Esta lista no sigue el contenido de tu botiquín a lo largo de la partida. Define <b>qué tipos de cuidados están en juego</b>: se desmarca el material del que no se dispone, y la aplicación deja de sacar las heridas que lo exigen.",
    "g168": "Es un ajuste de <b>preparación</b>, no de terreno: se hace antes de la partida, y normalmente lo hace el organizador.",
    "g169": "Un jugador no retira cartas del juego",
    "g170": "En partida, tus ajustes están <b>bloqueados</b>: el organizador decide el material y las cantidades, para que todos los médicos jueguen el mismo mazo. Así que no puedes apartar una herida porque no te venga bien.",
    "g171": "En solitario, en cambio, configuras libremente tu propio juego.",
    "g172": "<b>Ejemplo.</b> ¿Ningún médico del evento tiene apósito de 3 lados? El organizador desmarca ese material antes de la partida: la herida torácica aspirante y el neumotórax desaparecen del mazo para todo el mundo.",
    "g173": "Cartas activas",
    "g174": "La lista completa de las heridas del modo, <b>ordenadas por gravedad</b>: muerte primero, luego críticas, graves, leves y especiales. Para cada carta:",
    "g175": "el ojo abre el <b>catálogo</b> y te enseña la carta entera;",
    "g176": "los botones <b>&ndash;</b> y <b>+</b> ajustan su cantidad en el mazo;",
    "g177": "el <b>porcentaje</b> de la derecha indica sus opciones de salir. Se actualiza solo;",
    "g178": "una línea <b>en gris</b> significa que falta el material: esa carta no saldrá.",
    "g179": "Poner una carta a cero",
    "g180": "Poner la cantidad a 0 retira la carta del mazo por completo. Es la forma limpia de apartar una herida que no te gusta, sin tocar el resto.",
    "g181": "Crear tus propios mazos de cartas",
    "g182": "El botón del <b>lápiz</b>, arriba a la derecha, abre “Mis mazos”. Ahí puedes construir tus propias heridas: contaminación química, radiación, mordeduras, lo que pida tu escenario.",
    "g183": "Crear un mazo",
    "g184": "Ponle un nombre. Marca <b>Mostrar en la pantalla de inicio</b> para que tenga su propio botón redondo.",
    "g185": "Añadir cartas",
    "g186": "Para cada una: una gravedad, un t&iacute;tulo, una zona, una condici&oacute;n de protecci&oacute;n, un protocolo de cuidados.",
    "g187": "Elegir el material necesario",
    "g188": "Toca las fichas correspondientes. Puedes crear material que no existe en la lista básica &mdash; “Anti-rad”, “Suero”...",
    "g189": "Elegir el icono del botón",
    "g190": "Una treintena de pictogramas a elegir: bala, granada, explosión, riesgo biológico, radiación, zombi, criatura, robot, jeringa, pastillas, perfusión... Identifica el mazo en el inicio, y lo acompaña cuando lo compartes o lo asignas en partida.",
    "g191": "El mazo aparece en tu inicio, listo para usar.",
    "g192": "Compartir un mazo con alguien",
    "g193": "El botón <b>compartir</b> de una tarjeta de mazo genera un código largo que empieza por <b>TMDECK1</b>. Mándalo por SMS o mensajería; el destinatario usa <b>Importar un mazo</b> y pega el código. Recibe todas las cartas y el material asociado.",
    "g194": "La opción “modo extremo” del mazo",
    "g195": "Marcada, tu mazo propio también dispara la silueta y la pregunta de protección, igual que el modo Extremo oficial.",
    "g196": "Durante una partida, tus mazos se apartan",
    "g197": "Cuando te unes a una partida, el organizador impone su configuración: tus mazos propios desaparecen temporalmente y la creación queda bloqueada. <b>Te los devuelven íntegros en cuanto sales de la partida.</b> No se pierde nada.",
    "g198": "Jugar entre varios: el organizador",
    "g199": "El organizador crea la partida y dirige lo que va a robar cada jugador. El botón <b>multijugador</b> está arriba a la derecha.",
    "g200": "Abre el menú multijugador",
    "g201": "El primer botón de arriba a la derecha, con las dos siluetas.",
    "g202": "Ponle un nombre a la partida",
    "g203": "Por ejemplo “Ejercicio Alfa”. Es el nombre que teclearán tus jugadores para unirse.",
    "g204": "Indica tu nombre de jugador",
    "g205": "El nombre con el que aparecerás.",
    "g206": "Deja el enlace en “Servidor Firebase”",
    "g207": "Es el ajuste recomendado. Funciona entre redes distintas (el 4G de un jugador y el WiFi de otro) y te permite cerrar tu página sin cortar la partida.",
    "g208": "Pulsa CREAR UNA PARTIDA",
    "g209": "Se abre el <b>CG</b>: es tu panel de control.",
    "g210": "Invitar a los jugadores",
    "g211": "La pestaña <b>Invitación</b> muestra un <b>código QR</b> y un enlace. Tres formas de traer a tus jugadores, de la más sencilla a la más manual:",
    "g212": "<b>escanean el código QR</b> desde su aplicación: es inmediato;",
    "g213": "les mandas el <b>enlace</b> por mensajería, con el botón <b>Copiar</b> de la línea del enlace;",
    "g214": "les das solo el <b>código de la partida</b> &mdash; el botón <b>Copiar</b> de al lado lo pone en el portapapeles, práctico para dictarlo o mandarlo sin el enlace completo;",
    "g215": "<b>teclean el código</b> en su menú Unirse.",
    "g216": "Puedes guardar el móvil",
    "g217": "Con el enlace Firebase, la partida vive en el servidor, no en tu móvil. Puedes cerrar la aplicación, bloquear la pantalla o incluso reiniciar el aparato: al volver a abrirla, recuperas tu CG, tus jugadores y tu registro.",
    "g218": "Es la diferencia principal con el antiguo enlace punto a punto, en el que tu página debía permanecer abierta todo el rato.",
    "g219": "Decidir qué va a robar cada equipo",
    "g220": "Es el corazón del papel de organizador, en la pestaña <b>Mazos</b>.",
    "g221": "Elige un mazo",
    "g222": "Clásico, Avanzado, Extremo, Explosión o uno de tus mazos propios.",
    "g223": "Elige quién lo recibe",
    "g224": "Todo el mundo, solo un equipo, o un jugador concreto.",
    "g225": "Pulsa ASIGNAR ESTE MAZO",
    "g226": "Aparece de inmediato en el inicio de los destinatarios.",
    "g227": "El mazo asignado sustituye al modo",
    "g228": "Un jugador que recibe “Clásico” robará <b>solo</b> del Clásico. No conserva ni el modo de la partida, ni las cartas de explosión, ni sus mazos propios.",
    "g229": "Un jugador al que <b>no</b> le asignas nada juega el modo en curso, el que has definido en la pestaña Editor.",
    "g230": "Ejemplo concreto",
    "g231": "Quieres que los médicos experimentados del equipo Rojo se enfrenten a lo gordo, mientras los principiantes del equipo Azul aprenden:",
    "g232": "Mazo asignado",
    "g233": "Resultado",
    "g234": "Equipo Azul",
    "g235": "Cuidados sencillos, aprendizaje suave.",
    "g236": "Equipo Rojo",
    "g237": "Extremo",
    "g238": "Silueta, protecciones, protocolos largos.",
    "g239": "Jugar entre varios: el jugador",
    "g240": "Mucho más sencillo: casi no tienes que hacer nada.",
    "g241": "La forma más sencilla: <b>abrir el enlace de invitación</b> del organizador.",
    "g242": "Abre el enlace recibido",
    "g243": "Por SMS, mensajería, o escaneando el código QR. Se abre en tu navegador, o directamente en la aplicación si está instalada.",
    "g244": "Indica tu nombre de jugador y tu equipo",
    "g245": "La aplicación ya está conectada a la partida: solo te pregunta con qué nombre juegas y en qué equipo.",
    "g246": "Tu inicio se actualiza con los mazos que te han asignado.",
    "g247": "Sin el enlace",
    "g248": "Abre el menú multijugador",
    "g249": "El botón con las dos siluetas, arriba a la derecha.",
    "g250": "Pulsa UNIRSE A UNA PARTIDA",
    "g251": "La sección se despliega: escanea el código QR del organizador, o teclea el código de la partida. Otra pulsación la repliega.",
    "g252": "Indica tu nombre de jugador y tu equipo",
    "g253": "La lista de equipos es la creada por el organizador.",
    "g254": "Lo que cambia una vez en partida",
    "g255": "la franja superior muestra tu <b>equipo</b> y el <b>nombre de la partida</b>;",
    "g256": "aparece arriba un botón <b>SALIR</b>;",
    "g257": "tus <b>ajustes quedan bloqueados</b>: el organizador decide el modo, el material y las cantidades;",
    "g258": "cada una de tus tiradas aparece en el <b>registro</b> del organizador.",
    "g259": "Si pierdes la cobertura",
    "g260": "La aplicación se reconecta sola en cuanto vuelve la cobertura. Durante el corte <b>conservas tus cartas asignadas</b> y puedes seguir robando: solo el registro y los cambios decididos por el organizador esperarán a que vuelva la señal.",
    "g261": "El botón SALIR es definitivo",
    "g262": "Salir de la partida borra tu identidad de sesión. Si vuelves, serás un jugador nuevo: el organizador tendrá que devolverte tu equipo y, si procede, tu rango de coorganizador. Para una simple pausa, <b>cierra la aplicación sin pulsar Salir</b>.",
    "g263": "El CG, pestaña a pestaña",
    "g264": "El CG es el panel de control del organizador. Seis pestañas, cada una con un papel concreto.",
    "g265": "Para qué sirve",
    "g266": "El nombre de la partida, el código QR y el enlace que compartir. Es donde mandas a tus jugadores.",
    "g267": "La lista de los conectados. Para cada uno: cambiarle de equipo con una pulsación, hacerlo <b>Admin</b>, o <b>Expulsarlo</b>. Los jugadores desconectados siguen apareciendo en gris.",
    "g268": "<b>Equipos</b>",
    "g269": "Crear o eliminar equipos, con su color. Mínimo dos. Eliminar un equipo recoloca automáticamente a sus jugadores en otro sitio.",
    "g270": "<b>Editor</b>",
    "g271": "Ajustar cada mazo <b>antes</b> de repartirlo: cantidades, material, riesgo de muerte. El modo marcado <b>EN JUEGO</b> es el de los jugadores sin asignación.",
    "g272": "Asignar un mazo a todo el mundo, a un equipo o a un jugador. La lista de abajo muestra lo repartido, con una papelera para quitarlo.",
    "g273": "El registro en tiempo real: qui&eacute;n se ha unido, qui&eacute;n ha robado qu&eacute; herida, a qu&eacute; hora y en qu&eacute; <b>equipo</b>. Descargable en archivo de texto.",
    "g274": "El coorganizador",
    "g275": "Hacer <b>Admin</b> a un jugador le da acceso al mismo CG que a ti. Puede mover jugadores, repartir mazos, crear equipos. Muy práctico en un terreno grande donde no puedes estar en todas partes.",
    "g276": "Nadie puede ascenderse solo",
    "g277": "El rango de administrador solo puede darlo tú o un coorganizador ya existente, y esa regla la aplica <b>el servidor</b>. Ni siquiera un jugador que conociera la aplicación a la perfección puede dárselo a sí mismo, ni suplantar a otro copiando su nombre de jugador.",
    "g278": "Cerrar la partida",
    "g279": "El botón rojo del fondo del CG avisa a todos los jugadores y los desconecta. <b>Acuérdate de descargar tus registros antes</b> si quieres guardar constancia de la partida.",
    "g280": "Sobre el terreno: consejos prácticos",
    "g281": "Antes de la partida",
    "g282": "haz que todos los médicos <b>abran la aplicación una vez con cobertura</b>, en el briefing;",
    "g283": "pídeles que <b>instalen el icono</b> en su pantalla de inicio;",
    "g284": "haz que pongan su <b>nombre de jugador</b> antes de unirse;",
    "g285": "crea la partida y prueba la conexión <b>con un móvil</b> antes de que llegue todo el mundo;",
    "g286": "ajusta tus cantidades en la pestaña <b>Editor</b> antes de repartir los mazos.",
    "g287": "Durante la partida",
    "g288": "mantén el CG abierto en la pestaña <b>Registro</b> para seguir la actividad en directo;",
    "g289": "si un tipo de cuidado resulta imposible de encontrar sobre el terreno, retira su material desde la pestaña <b>Editor</b>: el cambio se aplica al instante a todos los jugadores;",
    "g290": "para endurecer la partida sobre la marcha, sube la probabilidad del riesgo de muerte: el cambio es inmediato para todos;",
    "g291": "nombra a un <b>coorganizador</b> si el terreno es grande.",
    "g292": "Después de la partida",
    "g293": "<b>descarga los registros</b> antes de cerrar: excelente material de debriefing;",
    "g294": "cierra limpiamente para liberar el nombre de la partida.",
    "g295": "La pantalla se queda encendida mientras hay una ficha, y la conexión permanente consume. Para una jornada completa, prevé una <b>batería externa</b> para el organizador y para los médicos más solicitados.",
    "g296": "Si algo va mal",
    "g297": "Síntoma",
    "g298": "<b>La aplicación no se abre sin cobertura</b>",
    "g299": "Nunca se ha abierto con cobertura en este aparato. Reconéctate una vez, deja que cargue del todo, y luego funcionará sin conexión.",
    "g300": "<b>“Partida no encontrada”</b>",
    "g301": "Comprueba la ortografía exacta del nombre con el organizador. Los acentos y los espacios no importan, pero las letras sí. Lo más seguro sigue siendo el código QR.",
    "g302": "<b>“Ninguna carta disponible”</b>",
    "g303": "O todas las cartas están a cero, o están bloqueadas por material que falta. En solitario, abre los Ajustes y vuelve a marcar material. En partida, avisa al organizador: solo él puede tocarlo.",
    "g304": "<b>Un jugador aparece dos veces</b>",
    "g305": "Dos jugadores tienen el mismo nombre: el segundo pasa automáticamente a “Nombre (2)”. Pídele que lo cambie, o déjalo así.",
    "g306": "<b>Un jugador se queda “sin conexión”</b>",
    "g307": "Su móvil ha perdido la cobertura. Vuelve solo. Si de verdad se ha ido, quítalo con el botón Expulsar.",
    "g308": "<b>Ya no encuentro mis mazos propios</b>",
    "g309": "Estás en partida: están apartados y te los devolverán al salir. No se pierde nada.",
    "g310": "<b>La pantalla parece antigua</b>",
    "g311": "Cierra la aplicación del todo y vuelve a abrirla con cobertura: se actualiza sola.",
    "g312": "<font color=\"white\" size=\"11\"><b>Buen juego, y buenos cuidados.</b></font><br/><font color=\"#c49708\" size=\"9\">Bravo Sierra Events // Frontline</font>",
    "g313": "BSE Medical System - Guía de uso",
    "g314": "Bravo Sierra Events",
    "g315": "Guía de uso de la aplicación BSE Medical System",
    "g316": "PDF genere :",
    "g317": "taille     :",
}
