# -*- coding: utf-8 -*-
"""Guide BSE Medical System — textes ITALIENS.

   Meme jeu de cles que guide-fr.py, qui est la reference.
   Le balisage <b>, <br/> et <font> doit etre conserve tel quel.
"""
TEXTES = {
    "m08": "Salvare",
    "m09": "Una sola carta per pi&ugrave; arti",
    "m10": "La zona si sceglie da un elenco: testa, torso, braccio destro, braccio sinistro, gamba destra, gamba sinistra &mdash; ma anche <b>entrambe le braccia</b>, <b>entrambe le gambe</b> o <b>tutti e quattro gli arti</b>. Un'escoriazione ai quattro arti sta allora in <b>una sola carta</b> invece di quattro: la zona esatta viene estratta a caso al momento della diagnosi e, in modalit&agrave; Estrema, &egrave; quella toccata sulla sagoma. “Zona personalizzata” resta per scrivere quello che vuoi. Tre pulsanti <b>Protezione balistica</b> completano il quadro: la carta pu&ograve; uscire solo <b>con</b> l'elmetto o il giubbotto, solo <b>senza</b> di essi, o in entrambi i casi. &Egrave; cos&igrave; che si contrappone “impatto sull'elmetto” a “colpo alla testa”.",
    "m07": "in fondo: a sinistra la <b>scelta della lingua</b>, a destra i collegamenti a <b>Bravo Sierra Events</b> &mdash; sito, Discord, Instagram, YouTube e Facebook.",
    "m01": "Torso",
    "m02": "PROTEZIONE",
    "m03": "QUADRO CLINICO",
    "m04": "Titolo",
    "m05": "Protezione",
    "m06": "Quadro clinico",
    "chapitre_apres": "",
    "chapitre": "CAPITOLO",
    "g001": "<font size=\"7\" color=\"#8a8a84\">SCHEDA DI TRIAGE</font>",
    "g002": "<font size=\"8\" color=\"white\"><b> CRITICA </b></font>",
    "g003": "EMORRAGIA INTERNA",
    "g004": "ZONA COLPITA",
    "g005": "Piastre balistiche indossate: NO",
    "g006": "Ferita perforante all'addome che provoca<br/>una forte emorragia interna.",
    "g007": "PROTOCOLLO DI CURA",
    "g008": "Bendaggio + Sacca di sangue<br/>+ Adrenalina",
    "g009": "BSE MEDICAL SYSTEM  //  GUIDA ALL'USO",
    "g010": "Bravo Sierra Events",
    "g011": "BSE MEDICAL SYSTEM",
    "g012": "FRONTLINE  //  FIELD APPLICATION",
    "g013": "<font color=\"white\" size=\"15\"><b>Guida all'uso</b></font>",
    "g014": "<font color=\"#9b9b96\" size=\"10.5\">Per scoprire l'applicazione, senza sapere nulla in partenza</font>",
    "g015": "<font color=\"#c49708\" size=\"9\">https://project-bsm-7d32c.web.app</font>",
    "g016": "A cosa serve questa applicazione",
    "g017": "Installare l'applicazione sul telefono",
    "g018": "La tua prima diagnosi",
    "g019": "Leggere una scheda di triage",
    "g020": "I livelli di gravità",
    "g021": "Le modalità di gioco",
    "g022": "La modalità Estrema nel dettaglio",
    "g023": "Le impostazioni",
    "g024": "Creare i tuoi mazzi di carte",
    "g025": "Giocare in più persone: l'organizzatore",
    "g026": "Giocare in più persone: il giocatore",
    "g027": "Il QG, scheda per scheda",
    "g028": "Sul campo: consigli pratici",
    "g029": "In caso di problemi",
    "g030": "A chi si rivolge questa guida",
    "g031": "Non hai mai aperto l'applicazione? Sei esattamente la persona giusta. Questa guida parte da zero e non richiede alcuna conoscenza pregressa, né di airsoft medico né di informatica. Leggi i capitoli da 1 a 5 per giocare già questo pomeriggio; il resto ti servirà quando vorrai organizzare una partita.",
    "g032": "A cosa serve questa applicazione",
    "g033": "BSE Medical System sostituisce il mazzo di carte di carta che i medici da softair si portano in tasca. Quando un giocatore viene colpito, il medico tira fuori il telefono, preme un pulsante e l'applicazione pesca una ferita a caso con il protocollo di cura corrispondente.",
    "g034": "Basta carte bagnate, perse o mescolate. E soprattutto: l'organizzatore può decidere a distanza cosa pescherà ogni squadra.",
    "g035": "Il principio, in quattro tempi",
    "g036": "Un giocatore viene colpito",
    "g037": "Si mette a terra e chiama un medico.",
    "g038": "Il medico arriva e apre l'applicazione",
    "g039": "Preme il grande pulsante rotondo al centro dello schermo.",
    "g040": "L'applicazione pesca una ferita",
    "g041": "Appare una scheda: la zona colpita, la gravità e le cure da applicare.",
    "g042": "Il medico applica il protocollo",
    "g043": "Laccio emostatico, bendaggio, stecca... a seconda della scheda. Il ferito torna poi in gioco.",
    "g044": "Il materiale resta ben reale",
    "g045": "L'applicazione non sostituisce la tua borsa. Ti dice <b>cosa fare</b>; mettere il vero laccio finto e il vero bendaggio tocca a te. Se un tipo di cura non è disponibile all'evento &mdash; nessuno ha una medicazione a 3 lati, per esempio &mdash; l'organizzatore lo toglie dal gioco <b>prima</b> della partita, e le ferite che lo richiedono smettono di uscire.",
    "g046": "Installare l'applicazione sul telefono",
    "g047": "Non c'è nulla da scaricare da un negozio di applicazioni. Passa tutto dal tuo browser di sempre.",
    "g048": "Apri l'indirizzo nel browser",
    "g049": "<b>https://project-bsm-7d32c.web.app</b> &mdash; Chrome su Android, Safari su iPhone.",
    "g050": "Aggiungi l'applicazione alla schermata iniziale",
    "g051": "Su <b>Android</b>: menu “tre puntini”, poi “Installa app” o “Aggiungi a schermata Home”.<br/>Su <b>iPhone</b>: pulsante Condividi (il quadrato con la freccia), poi “Aggiungi a Home”.",
    "g052": "Avviala dall'icona",
    "g053": "Una croce medica dorata su fondo nero appare insieme alle tue altre applicazioni. Si apre a schermo intero, senza barra degli indirizzi.",
    "g054": "Da fare al briefing, non sul campo",
    "g055": "Ogni telefono deve aprire l'applicazione <b>una volta con la rete</b>. L'applicazione si memorizza allora per intero sul dispositivo.",
    "g056": "Fatta quella prima apertura, funziona <b>senza alcuna rete</b>: puoi pescare ferite in mezzo al bosco, in modalità aereo. Solo il gioco in più persone richiede una connessione.",
    "g057": "Cosa vedi appena arrivi",
    "g058": "La schermata iniziale si chiama <b>DIAGNOSI MEDICA</b>. Ci trovi:",
    "g059": "uno o più <b>grandi pulsanti rotondi</b> al centro: sono le pescate disponibili;",
    "g060": "una fascia <b>MAZZO ATTIVO</b> in basso, che indica quante carte sono in gioco;",
    "g061": "in alto a destra, tre pulsanti: <b>multigiocatore</b>, <b>i miei mazzi</b> e <b>impostazioni</b>;",
    "g062": "in alto, una fascia grigia con il tuo nome giocatore e la tua squadra.",
    "g063": "La tua prima diagnosi",
    "g064": "È l'uso principale dell'applicazione, e il più semplice.",
    "g065": "Premi il pulsante rotondo",
    "g066": "Il più comune si chiama <b>BALISTICA</b>: è una ferita da colpo d'arma.",
    "g067": "Attendi l'analisi",
    "g068": "Una valutazione <b>MARCH</b> scorre per qualche secondo. È il tempo della diagnosi: approfittane per osservare il ferito.",
    "g069": "Leggi la scheda",
    "g070": "Indica la gravità, la zona colpita e il protocollo da applicare.",
    "g071": "Applica le cure, poi premi “Nuova diagnosi”",
    "g072": "Torni alla schermata iniziale, pronto per il ferito successivo.",
    "g073": "Cosa vuol dire MARCH?",
    "g074": "È l'ordine con cui un soccorritore esamina un ferito, dal più mortale al meno urgente. L'applicazione lo mostra per metterti nel clima:",
    "g075": "<b>Massive bleeding</b> &mdash; prima le emorragie massive",
    "g076": "<b>Airways</b> &mdash; le vie respiratorie",
    "g077": "<b>Respiration</b> &mdash; la ventilazione",
    "g078": "<b>Circulation</b> &mdash; il polso, lo shock",
    "g079": "<b>Head / Hypothermia</b> &mdash; la testa e il raffreddamento",
    "g080": "Lo schermo resta acceso",
    "g081": "Finché una scheda è visualizzata, il telefono non si blocca. Puoi posarlo per curare a due mani: il protocollo sarà ancora lì quando lo riprenderai.",
    "g082": "Leggere una scheda di triage",
    "g083": "Tutte le schede sono costruite allo stesso modo. Ecco com'è fatta una scheda completa:",
    "g084": "Ogni parte, una per una",
    "g085": "Zona della scheda",
    "g086": "Cosa significa",
    "g087": "<b>Distintivo di gravità</b>",
    "g088": "In alto a destra, colorato. Dà a colpo d'occhio l'urgenza della situazione. Il filetto in cima alla scheda ha lo stesso colore.",
    "g089": "Il nome breve della ferita, a caratteri grandi.",
    "g090": "<b>Zona colpita</b>",
    "g091": "Dove il ferito è colpito: testa, torso, braccio sinistro, gamba destra...",
    "g092": "Appare solo in modalità Estrema. Ricorda se il ferito indossava un elmetto o delle piastre.",
    "g093": "La descrizione della ferita, da leggere ad alta voce al ferito per il gioco di ruolo.",
    "g094": "<b>Protocollo di cura</b>",
    "g095": "<b>La parte più importante</b>: esattamente ciò che devi fare.",
    "g096": "Attenzione al conto alla rovescia",
    "g097": "Se l'organizzatore ha attivato l'opzione hardcore, alcune ferite fanno partire un <b>bip regolare</b> e una fascia rossa <b>EMORRAGIA IN CORSO</b>.",
    "g098": "Hai allora un tempo limitato per applicare le cure e premere <b>CURE EFFETTUATE</b>. Se il tempo scade, il ferito muore: lo schermo diventa nero e il bip si trasforma in un suono continuo.",
    "g099": "I livelli di gravità",
    "g100": "Cinque livelli, sempre gli stessi, con un codice colore costante in tutta l'applicazione.",
    "g101": "Gravità",
    "g102": "Cosa significa per il medico",
    "g103": "MORTE",
    "g104": "Niente da fare. Il giocatore è morto e torna al punto di rientro.",
    "g105": "Urgenza vitale. È su queste ferite che parte il conto alla rovescia, se l'opzione è attiva.",
    "g106": "Serio ma stabile. Prenditi il tempo di applicare bene il protocollo.",
    "g107": "LIEVE",
    "g108": "Poca cosa. Un bendaggio e il giocatore riparte.",
    "g109": "SPECIALE",
    "g110": "Caso particolare, spesso legato a una protezione. Leggi bene il protocollo: dipende dall'uso dell'elmetto o del giubbotto.",
    "g111": "Perché alcune ferite escono più spesso",
    "g112": "Ogni carta ha una <b>quantità</b>, come se ci fossero più copie della stessa carta nel mazzo. Una carta in 4 copie uscirà il doppio delle volte rispetto a una in 2 copie. L'organizzatore regola queste quantità per dare il tono alla sua partita: più ferite lievi, o più urgenze vitali.",
    "g113": "Le modalità di gioco",
    "g114": "La modalità determina quale mazzo viene usato. Si sceglie nelle <b>Impostazioni</b>, oppure l'organizzatore la impone in partita.",
    "g115": "Per i principianti. Cure semplici: laccio emostatico, bendaggio, stecca. Ideale per una prima partita.",
    "g116": "<b>Avanzato</b>",
    "g117": "Per gli abituali. Protocolli più lunghi, entrano in gioco morfina e adrenalina.",
    "g118": "<b>Estremo</b>",
    "g119": "Il più realistico. Indichi la zona colpita su una sagoma, e le ferite ne derivano. Vedi il capitolo seguente.",
    "g120": "Un mazzo <b>in più</b>, per granate ed esplosivi. Aggiunge un secondo pulsante rotondo sulla schermata iniziale.",
    "g121": "Il caso particolare dell'esplosione",
    "g122": "Il mazzo Esplosione contiene le ferite da onda d'urto e da schegge. Si attiva nelle Impostazioni, in modalità Avanzato o Estremo, e fa apparire un pulsante <b>ESPLOSIONE</b> arancione accanto al pulsante Balistica.",
    "g123": "Un'esplosione non rispetta le protezioni",
    "g124": "È voluto: a differenza delle ferite da arma da fuoco, una carta esplosione può uccidere un giocatore <b>anche se indossa elmetto e piastre</b>. Un'onda d'urto attraversa la protezione. Non cercare l'errore: è la regola del gioco.",
    "g125": "La modalità Estrema nel dettaglio",
    "g126": "È la modalità più immersiva, e l'unica in cui <b>sei tu</b> a decidere la zona colpita invece di lasciarla al caso.",
    "g127": "Premi il pulsante di pescata",
    "g128": "Al posto della scheda appare una <b>sagoma umana</b>.",
    "g129": "Tocca la zona in cui il giocatore è stato colpito",
    "g130": "Testa, torso, braccio o gamba. <b>La vista è a specchio</b>: il braccio destro del ferito è alla tua sinistra sullo schermo, come se gli fossi di fronte.",
    "g131": "Rispondi alla domanda sulla protezione",
    "g132": "Per la testa: “Elmetto balistico indossato?”. Per il torso: “Giubbotto antiproiettile indossato?”. Guarda il ferito e rispondi onestamente.",
    "g133": "La scheda appare",
    "g134": "Contiene solo ferite coerenti con la zona <b>e</b> con la tua risposta.",
    "g135": "Perché la domanda sulla protezione cambia tutto",
    "g136": "La risposta filtra davvero le carte disponibili. Un giocatore con l'elmetto non può pescare “Colpo diretto alla testa (senza elmetto)”:",
    "g137": "Zona colpita",
    "g138": "Protezione indossata",
    "g139": "Senza protezione",
    "g140": "<b>Testa</b>",
    "g141": "Impatto sull'elmetto<br/><font size='8' color='#5d5d58'>Riposo di 2 minuti</font>",
    "g142": "Ferita alla fronte, trauma cranico, <b>oppure colpo mortale</b>",
    "g143": "Impatto sulla piastra, escoriazione al fianco, costole fratturate",
    "g144": "Pneumotorace, emorragia interna, <b>oppure colpo vitale</b>",
    "g145": "<b>Braccio / Gamba</b>",
    "g146": "<font color='#5d5d58'>Domanda non posta</font>",
    "g147": "Ferite proprie dell'arto: una frattura del femore non può uscire su un braccio.",
    "g148": "La morale della modalità Estrema",
    "g149": "Indossare elmetto e piastre ti salva davvero la vita in questa modalità. È l'argomento migliore per convincere i tuoi giocatori a equipaggiarsi bene.",
    "g150": "Le impostazioni",
    "g151": "Ci si arriva dal pulsante dei <b>cursori</b>, in alto a destra dello schermo. Ricorda di premere <b>CONFERMA</b> in basso per tenere le tue modifiche; <b>ANNULLA</b> rimette tutto com'era.",
    "g152": "Profilo multigiocatore",
    "g153": "Il tuo <b>nome giocatore</b>. È il nome con cui ti vedrà l'organizzatore. Mettilo prima di entrare in una partita: è più semplice per tutti.",
    "g154": "Classico, Avanzato, Estremo, o uno dei tuoi mazzi personali. In partita questa impostazione è bloccata: decide l'organizzatore.",
    "g155": "Opzione hardcore: il rischio di morte",
    "g156": "Una volta spuntata, appaiono quattro impostazioni:",
    "g157": "Impostazione",
    "g158": "<b>Probabilità</b>",
    "g159": "Le probabilità che una ferita faccia partire il conto alla rovescia. 40% di base: circa una ferita critica su due.",
    "g160": "<b>Tempo minimo</b>",
    "g161": "Il tempo più breve a disposizione del medico. 30 secondi di base.",
    "g162": "<b>Tempo massimo</b>",
    "g163": "Il tempo più lungo. 60 secondi di base. Il tempo reale viene estratto a caso tra i due, e il medico non lo vede.",
    "g164": "<b>Estendi alle Gravi</b>",
    "g165": "Di base solo le ferite Critiche possono uccidere. Spunta per rendere la partita nettamente più dura.",
    "g166": "Materiale necessario",
    "g167": "Questo elenco non segue il contenuto della tua borsa durante la partita. Definisce <b>quali tipi di cura sono in gioco</b>: si toglie la spunta al materiale che non si ha, e l'applicazione smette di pescare le ferite che lo richiedono.",
    "g168": "È un'impostazione di <b>preparazione</b>, non di campo: si fa prima della partita, e normalmente la fa l'organizzatore.",
    "g169": "Un giocatore non toglie carte dal gioco",
    "g170": "In partita le tue impostazioni sono <b>bloccate</b>: l'organizzatore decide materiale e quantità, perché tutti i medici giochino lo stesso mazzo. Non puoi quindi scartare una ferita solo perché ti scomoda.",
    "g171": "In solitario, invece, configuri liberamente il tuo gioco.",
    "g172": "<b>Esempio.</b> Nessun medico dell'evento ha una medicazione a 3 lati? L'organizzatore toglie la spunta a quel materiale prima della partita: la ferita toracica soffiante e lo pneumotorace spariscono dal mazzo per tutti.",
    "g173": "Carte attive",
    "g174": "L'elenco completo delle ferite della modalità, <b>ordinate per gravità</b>: morte per prima, poi critiche, gravi, lievi e speciali. Per ogni carta:",
    "g175": "l'occhio apre il <b>catalogo</b> e ti mostra la carta per intero;",
    "g176": "i pulsanti <b>&ndash;</b> e <b>+</b> regolano la sua quantità nel mazzo;",
    "g177": "la <b>percentuale</b> a destra indica le sue probabilità di uscire. Si aggiorna da sola;",
    "g178": "una riga <b>in grigio</b> significa che manca il materiale: quella carta non uscirà.",
    "g179": "Portare una carta a zero",
    "g180": "Mettere la quantità a 0 toglie completamente la carta dal mazzo. È il modo pulito di scartare una ferita che non ti piace, senza toccare il resto.",
    "g181": "Creare i tuoi mazzi di carte",
    "g182": "Il pulsante <b>matita</b> in alto a destra apre “I miei mazzi”. Lì puoi costruire le tue ferite: contaminazione chimica, radiazioni, morsi, quello che chiede il tuo scenario.",
    "g183": "Creare un mazzo",
    "g184": "Dagli un nome. Spunta <b>Mostra sulla schermata iniziale</b> perché abbia il suo pulsante rotondo.",
    "g185": "Aggiungere carte",
    "g186": "Per ciascuna: una gravit&agrave;, un titolo, una zona, una condizione di protezione, un protocollo di cura.",
    "g187": "Scegliere il materiale necessario",
    "g188": "Tocca le pastiglie corrispondenti. Puoi creare materiale che non esiste nell'elenco di base &mdash; “Anti-rad”, “Siero”...",
    "g189": "Scegliere l'icona del pulsante",
    "g190": "Una trentina di pittogrammi a scelta: proiettile, granata, esplosione, rischio biologico, radiazione, zombie, creatura, robot, siringa, pastiglie, flebo... Identifica il mazzo sulla schermata iniziale, e lo segue quando lo condividi o lo assegni in partita.",
    "g191": "Il mazzo appare sulla tua schermata iniziale, pronto all'uso.",
    "g192": "Condividere un mazzo con qualcuno",
    "g193": "Il pulsante <b>condividi</b> su una scheda di mazzo produce un lungo codice che comincia con <b>TMDECK1</b>. Mandalo per SMS o messaggistica; il destinatario usa <b>Importa un mazzo</b> e incolla il codice. Riceve tutte le carte e il materiale associato.",
    "g194": "L'opzione “modalità estrema” del mazzo",
    "g195": "Spuntata, anche il tuo mazzo personale fa partire la sagoma e la domanda sulla protezione, come la modalità Estrema ufficiale.",
    "g196": "Durante una partita i tuoi mazzi vengono messi da parte",
    "g197": "Quando entri in una partita, l'organizzatore impone la sua configurazione: i tuoi mazzi personali spariscono temporaneamente e la creazione è bloccata. <b>Ti vengono restituiti per intero appena lasci la partita.</b> Non si perde nulla.",
    "g198": "Giocare in più persone: l'organizzatore",
    "g199": "L'organizzatore crea la partita e decide cosa pescherà ogni giocatore. Il pulsante <b>multigiocatore</b> è in alto a destra.",
    "g200": "Apri il menu multigiocatore",
    "g201": "Il primo pulsante in alto a destra, con le due sagome.",
    "g202": "Dai un nome alla partita",
    "g203": "Per esempio “Esercitazione Alfa”. È il nome che i tuoi giocatori digiteranno per raggiungerti.",
    "g204": "Indica il tuo nome giocatore",
    "g205": "Il nome con cui apparirai.",
    "g206": "Lascia il collegamento su “Server Firebase”",
    "g207": "È l'impostazione consigliata. Funziona tra reti diverse (il 4G di un giocatore e il WiFi di un altro) e ti permette di chiudere la tua pagina senza interrompere la partita.",
    "g208": "Premi CREA UNA PARTITA",
    "g209": "Si apre il <b>QG</b>: è il tuo pannello di controllo.",
    "g210": "Invitare i giocatori",
    "g211": "La scheda <b>Invito</b> mostra un <b>codice QR</b> e un link. Tre modi per far entrare i tuoi giocatori, dal più semplice al più manuale:",
    "g212": "<b>scansionano il codice QR</b> dalla loro applicazione: è immediato;",
    "g213": "mandi loro il <b>link</b> per messaggistica, con il pulsante <b>Copia</b> della riga del link;",
    "g214": "dai loro solo il <b>codice della partita</b> &mdash; il pulsante <b>Copia</b> accanto lo mette negli appunti, comodo per dettarlo o mandarlo senza il link completo;",
    "g215": "<b>digitano il codice</b> nel loro menu Unisciti.",
    "g216": "Puoi mettere via il telefono",
    "g217": "Con il collegamento Firebase, la partita vive sul server, non nel tuo telefono. Puoi chiudere l'applicazione, bloccare lo schermo, o perfino riavviare il dispositivo: riaprendo l'applicazione ritrovi il tuo QG, i tuoi giocatori e il tuo registro.",
    "g218": "È la differenza principale rispetto al vecchio collegamento peer-to-peer, in cui la tua pagina doveva restare sempre aperta.",
    "g219": "Decidere cosa pescherà ogni squadra",
    "g220": "È il cuore del ruolo di organizzatore, nella scheda <b>Mazzi</b>.",
    "g221": "Scegli un mazzo",
    "g222": "Classico, Avanzato, Estremo, Esplosione, o uno dei tuoi mazzi personali.",
    "g223": "Scegli chi lo riceve",
    "g224": "Tutti, una sola squadra, o un giocatore preciso.",
    "g225": "Premi ASSEGNA QUESTO MAZZO",
    "g226": "Appare subito sulla schermata iniziale dei destinatari.",
    "g227": "Il mazzo assegnato sostituisce la modalità",
    "g228": "Un giocatore che riceve “Classico” pescherà <b>solo</b> dal Classico. Non conserva né la modalità della partita, né le carte esplosione, né i suoi mazzi personali.",
    "g229": "Un giocatore a cui <b>non</b> assegni nulla gioca la modalità in corso, quella che hai definito nella scheda Editor.",
    "g230": "Esempio concreto",
    "g231": "Vuoi che i medici esperti della squadra Rossa affrontino il pesante, mentre i principianti della squadra Blu imparano:",
    "g232": "Mazzo assegnato",
    "g233": "Risultato",
    "g234": "Squadra Blu",
    "g235": "Cure semplici, apprendimento graduale.",
    "g236": "Squadra Rossa",
    "g237": "Estremo",
    "g238": "Sagoma, protezioni, protocolli lunghi.",
    "g239": "Giocare in più persone: il giocatore",
    "g240": "Molto più semplice: non devi fare quasi nulla.",
    "g241": "Il modo più semplice: <b>aprire il link d'invito</b> dell'organizzatore.",
    "g242": "Apri il link ricevuto",
    "g243": "Per SMS, messaggistica, o scansionando il codice QR. Si apre nel tuo browser, o direttamente nell'applicazione se è installata.",
    "g244": "Indica il tuo nome giocatore e la tua squadra",
    "g245": "L'applicazione è già collegata alla partita: ti chiede soltanto con quale nome giochi e in quale squadra.",
    "g246": "La tua schermata iniziale si aggiorna con i mazzi che ti sono stati assegnati.",
    "g247": "Senza il link",
    "g248": "Apri il menu multigiocatore",
    "g249": "Il pulsante con le due sagome, in alto a destra.",
    "g250": "Premi UNISCITI A UNA PARTITA",
    "g251": "La sezione si apre: scansiona il codice QR dell'organizzatore, o digita il codice della partita. Un'altra pressione la richiude.",
    "g252": "Indica il tuo nome giocatore e la tua squadra",
    "g253": "L'elenco delle squadre è quello creato dall'organizzatore.",
    "g254": "Cosa cambia una volta in partita",
    "g255": "la fascia in alto mostra la tua <b>squadra</b> e il <b>nome della partita</b>;",
    "g256": "appare in alto un pulsante <b>ESCI</b>;",
    "g257": "le tue <b>impostazioni sono bloccate</b>: l'organizzatore decide modalità, materiale e quantità;",
    "g258": "ogni tua pescata appare nel <b>registro</b> dell'organizzatore.",
    "g259": "Se perdi la rete",
    "g260": "L'applicazione si riconnette da sola appena la rete torna. Durante l'interruzione <b>conservi le tue carte assegnate</b> e puoi continuare a pescare: solo il registro e le modifiche decise dall'organizzatore aspetteranno il ritorno del segnale.",
    "g261": "Il pulsante ESCI è definitivo",
    "g262": "Lasciare la partita cancella la tua identità di sessione. Se torni, sarai un nuovo giocatore: l'organizzatore dovrà ridarti la tua squadra e, se del caso, il tuo grado di co-organizzatore. Per una semplice pausa, <b>chiudi l'applicazione senza premere Esci</b>.",
    "g263": "Il QG, scheda per scheda",
    "g264": "Il QG è il pannello di controllo dell'organizzatore. Sei schede, ciascuna con un ruolo preciso.",
    "g265": "A cosa serve",
    "g266": "Il nome della partita, il codice QR e il link da condividere. È qui che mandi i tuoi giocatori.",
    "g267": "L'elenco dei connessi. Per ciascuno: cambiargli squadra con una pressione, renderlo <b>Admin</b>, o <b>Espellerlo</b>. I giocatori offline restano visibili in grigio.",
    "g268": "<b>Squadre</b>",
    "g269": "Creare o eliminare squadre, con il loro colore. Minimo due. Eliminare una squadra ricolloca automaticamente i suoi giocatori altrove.",
    "g270": "<b>Editor</b>",
    "g271": "Regolare ogni mazzo <b>prima</b> di distribuirlo: quantità, materiale, rischio di morte. La modalità segnata <b>IN GIOCO</b> è quella dei giocatori senza assegnazione.",
    "g272": "Assegnare un mazzo a tutti, a una squadra o a un giocatore. L'elenco in basso mostra ciò che è stato distribuito, con un cestino per togliere.",
    "g273": "Il registro in tempo reale: chi si &egrave; unito, chi ha pescato quale ferita, a che ora e in quale <b>squadra</b>. Scaricabile come file di testo.",
    "g274": "Il co-organizzatore",
    "g275": "Rendere un giocatore <b>Admin</b> gli dà accesso al tuo stesso QG. Può spostare giocatori, distribuire mazzi, creare squadre. Molto comodo su un campo grande dove non puoi essere ovunque.",
    "g276": "Nessuno può promuoversi da solo",
    "g277": "Il grado di amministratore può essere dato solo da te o da un co-organizzatore già esistente, e questa regola è applicata <b>dal server</b>. Nemmeno un giocatore che conoscesse l'applicazione alla perfezione può attribuirselo, né prendere l'identità di un altro copiandone il nome giocatore.",
    "g278": "Chiudere la partita",
    "g279": "Il pulsante rosso in fondo al QG avvisa tutti i giocatori e li disconnette. <b>Ricorda di scaricare i tuoi registri prima</b> se vuoi tenere traccia della partita.",
    "g280": "Sul campo: consigli pratici",
    "g281": "Prima della partita",
    "g282": "fai <b>aprire l'applicazione una volta con la rete</b> a tutti i medici, al briefing;",
    "g283": "chiedi loro di <b>installare l'icona</b> sulla schermata iniziale;",
    "g284": "fai impostare loro il <b>nome giocatore</b> prima di entrare;",
    "g285": "crea la partita e prova la connessione <b>con un telefono</b> prima che arrivino tutti;",
    "g286": "regola le tue quantità nella scheda <b>Editor</b> prima di distribuire i mazzi.",
    "g287": "Durante la partita",
    "g288": "tieni il QG aperto sulla scheda <b>Registro</b> per seguire l'attività in diretta;",
    "g289": "se un tipo di cura risulta introvabile sul campo, togli il suo materiale dalla scheda <b>Editor</b>: la modifica si applica subito a tutti i giocatori;",
    "g290": "per indurire a partita in corso, alza la probabilità del rischio di morte: la modifica è immediata per tutti i giocatori;",
    "g291": "nomina un <b>co-organizzatore</b> se il campo è grande.",
    "g292": "Dopo la partita",
    "g293": "<b>scarica i registri</b> prima di chiudere: ottimo supporto per il debriefing;",
    "g294": "chiudi in modo pulito per liberare il nome della partita.",
    "g295": "Lo schermo resta acceso mentre una scheda è visualizzata, e la connessione permanente consuma. Su una giornata intera, prevedi una <b>batteria esterna</b> per l'organizzatore e per i medici più impegnati.",
    "g296": "In caso di problemi",
    "g297": "Sintomo",
    "g298": "<b>L'applicazione non si apre senza rete</b>",
    "g299": "Non è mai stata aperta con la rete su questo dispositivo. Riconnettiti una volta, lasciala caricare per intero, e poi funzionerà offline.",
    "g300": "<b>“Partita non trovata”</b>",
    "g301": "Verifica l'ortografia esatta del nome con l'organizzatore. Accenti e spazi non contano, le lettere sì. La via più sicura resta il codice QR.",
    "g302": "<b>“Nessuna carta disponibile”</b>",
    "g303": "O tutte le carte sono a zero, o sono bloccate da materiale mancante. In solitario, apri le Impostazioni e rimetti la spunta a del materiale. In partita, segnalalo all'organizzatore: solo lui può intervenire.",
    "g304": "<b>Un giocatore appare due volte</b>",
    "g305": "Due giocatori hanno lo stesso nome: il secondo diventa automaticamente “Nome (2)”. Chiedigli di cambiarlo, oppure lascia così.",
    "g306": "<b>Un giocatore resta “offline”</b>",
    "g307": "Il suo telefono ha perso la rete. Torna da solo. Se se n'è andato davvero, toglilo con il pulsante Espelli.",
    "g308": "<b>Non trovo più i miei mazzi personali</b>",
    "g309": "Sei in partita: sono messi da parte e ti verranno restituiti uscendo. Non si perde nulla.",
    "g310": "<b>La visualizzazione sembra vecchia</b>",
    "g311": "Chiudi completamente l'applicazione e riaprila con la rete: si aggiorna da sola.",
    "g312": "<font color=\"white\" size=\"11\"><b>Buon gioco, e buone cure.</b></font><br/><font color=\"#c49708\" size=\"9\">Bravo Sierra Events // Frontline</font>",
    "g313": "BSE Medical System - Guida all'uso",
    "g314": "Bravo Sierra Events",
    "g315": "Guida all'uso dell'applicazione BSE Medical System",
    "g316": "PDF genere :",
    "g317": "taille     :",
}
