/* BSE MEDICAL SYSTEM — 中文（简体）
   Les tables zone/grav/mat/membre/titre/soin/bilan sont indexees par le
   texte FRANCAIS d'origine, qui reste la cle interne des cartes. */
window.BSE_I18N.zh = {
ui: {
    'hdr.multijoueur': '多人游戏',
    'hdr.quitter': '退出对局',
    'hdr.sortir': '退出',
    'hdr.paquets': '我的牌组',
    'hdr.reglages': '设置',
    'hdr.bseLien': 'Bravo Sierra Events — 打开网站',
    'hdr.bseAria': '打开 Bravo Sierra Events 网站',
    'social.discord': 'Bravo Sierra Events 的 Discord',
    'social.instagram': 'Bravo Sierra Events 的 Instagram',
    'social.youtube': 'Bravo Sierra Events 的 YouTube',
    'social.facebook': 'Bravo Sierra Events 的 Facebook',
    'statut.solo': '单人',
    'statut.organisateur': '组织者',
    'statut.coadmin': '副管理员',
    'statut.reconnexion': '{nom} · 正在重新连接对局…',
    'paquet.balistique': '弹道',
    'paquet.explosion': '爆炸',

    'jeu.titre': '医疗判定',
    'jeu.sous': '点击开始判定',
    'jeu.paquetActif': '当前牌组',
    'jeu.chargement': '载入中...',
    'jeu.cartes': '{n} 张牌',

    'march.titre': 'MARCH 评估',
    'march.m': '大出血',
    'march.a': '气道',
    'march.r': '呼吸',
    'march.c': '循环',
    'march.h': '头部 / 低体温',
    'march.analyse': '评估进行中…',

    'sil.titre': '击中哪个部位？',
    'sil.sous': '点击被击中的身体部位',
    'sil.miroir': '（镜像视角：他的右臂在你的左边）',

    'fiche.mort': '阵亡',
    'fiche.mortSous': '时间耗尽 — 致命出血',
    'fiche.fermer': '关闭档案',
    'fiche.label': '检伤分类单',
    'fiche.zone': '受伤部位',
    'fiche.bilan': '伤情',
    'fiche.protocole': '救治流程',
    'fiche.hemorragie': '出血未止 — 危及生命',
    'fiche.nouveau': '新的判定',
    'fiche.soigner': '已完成救治（救活）',
    'fiche.stabilise': '伤员已稳定！',
    'fiche.protPortee': '已穿戴防弹护具：{reponse}',
    'fiche.avecProtection': '（穿戴防护）',

    'btn.annuler': '取消',
    'btn.valider': '确认',
    'btn.fermer': '关闭',
    'btn.retour': '返回',
    'btn.copier': '复制',
    'btn.ouvrir': '打开',
    'btn.oui': '是',
    'btn.non': '否',

    'qg.titre': '指挥部',
    'qg.partie': '对局',
    'qg.enLigne': '在线',
    'qg.ongletInvitation': '邀请',
    'qg.ongletJoueurs': '玩家',
    'qg.ongletEquipes': '队伍',
    'qg.ongletEditeur': '编辑器',
    'qg.ongletPaquets': '牌组',
    'qg.ongletLogs': '日志',
    'qg.codeAide': '对局代码 — 念给玩家听',
    'qg.lienAide': '连接链接（分享或二维码）',
    'qg.qrGeneration': '生成中...',
    'qg.qrAide': '玩家扫描二维码，或在「加入」菜单中输入对局名称。',
    'qg.joueurs': '玩家',
    'qg.equipes': '本局队伍',
    'qg.nomEquipePh': '队伍名称',
    'qg.couleurEquipePh': '#十六进制颜色',
    'qg.ajouterEquipe': '+ 队伍',
    'qg.editeur': '牌组编辑器',
    'qg.editeurAide': '在分发之前，调整所有牌组的数量、器材和死亡风险。',
    'qg.paquetsAttribues': '已分配的牌组',
    'qg.paquetsAide1': '选择每位玩家抽牌的来源：经典、进阶、极限、爆炸，或你自己的牌组。分配的牌组会<b>取代</b>该玩家的游戏模式 — 他只会看到这一个，数量按编辑器中的设置。',
    'qg.paquetsAide2': '没有任何分配的玩家，使用编辑器中设定的<b>当前模式</b>。',
    'qg.toutLeMonde': '所有人',
    'qg.uneEquipe': '仅一个队伍',
    'qg.unJoueur': '仅一名玩家',
    'qg.ajouterPaquet': '分配此牌组',
    'qg.journal': '实时日志',
    'qg.journalAide': '玩家的事件会带上其队伍的名称和颜色。',
    'qg.telechargerLogs': '下载日志（.txt）',
    'qg.effacerAffichage': '清空显示',
    'qg.cloturer': '结束对局（断开所有玩家）',
    'qg.retourSession': '返回主页（保留会话）',

    'reg.titre': '系统设置',
    'reg.profil': '多人游戏资料',
    'reg.pseudo': '你的玩家名',
    'reg.pseudoPh': '例：Doc',
    'reg.mode': '游戏模式',
    'reg.hardcore': '硬核选项',
    'reg.activerMort': '启用死亡风险',
    'reg.proba': '概率',
    'reg.probaSous': '针对符合条件的伤情',
    'reg.delaiMin': '最短时限',
    'reg.delaiMinSous': '死亡前',
    'reg.delaiMax': '最长时限',
    'reg.etendreGraves': '扩展到重伤',
    'reg.explosion': '爆炸',
    'reg.activerExplosion': '启用爆炸牌',
    'reg.materiel': '所需器材',
    'reg.cartesActives': '启用的牌',
    'reg.catalogue': '牌库',
    'reg.oeilAide': '每行的眼睛图标会打开该模式的牌库并定位到这张牌。',
    'reg.aide': '帮助',
    'reg.aideTexte': '完整使用指南，可在战前简报时阅读。打开一次后即可离线查看。',
    'reg.guide': '使用指南（PDF）',

    'lang.titre': '语言',
    'lang.choisir': '选择语言',

    'bld.titre': '我的牌组',
    'bld.sous': '创建你自己的牌组，并显示在主页上。',
    'bld.creer': '+ 创建牌组',
    'bld.importer': '导入牌组',
    'bld.edition': '编辑牌组',
    'bld.nom': '牌组名称',
    'bld.nomPh': '例：化学伤害',
    'bld.afficherAccueil': '显示在主页',
    'bld.modeExtreme': '极限模式',
    'bld.modeExtremeSous': '（人形图：受伤部位 + 防护）',
    'bld.icone': '按钮图标',
    'bld.iconeAide': '它用于在主页以及你分配到的玩家那里识别这个牌组。',
    'bld.cartes': '牌',
    'bld.ajouterCarte': '+ 添加一张牌',
    'bld.enregistrer': '保存',
    'bld.supprimerPaquet': '删除牌组',

    'ce.titreEcran': '牌',
    'ce.gravite': '严重程度',
    'ce.titre': '标题',
    'ce.titrePh': '例：骨折',
    'ce.zone': '受伤部位',
    'ce.zonePh': '例：手臂',
    'zoneOpt.tete': '头部',
    'zoneOpt.torse': '躯干',
    'zoneOpt.teteTorse': '头部或躯干',
    'zoneOpt.brasD': '右臂',
    'zoneOpt.brasG': '左臂',
    'zoneOpt.bras': '双臂',
    'zoneOpt.jambeD': '右腿',
    'zoneOpt.jambeG': '左腿',
    'zoneOpt.jambes': '双腿',
    'zoneOpt.membres': '四肢',
    'zoneOpt.libre': '自定义部位…',
    'zoneOpt.aideGroupe': '一张牌就够了：具体部位随机抽取；在极限模式下，则是人形图上被点中的部位。',
    'zoneOpt.aideLibre': '自由填写部位。它会原样显示，且在极限模式下这张牌可能出现在任意部位。',
    'ce.protection': '防弹护具',
    'prot.peuImporte': '不限',
    'prot.avec': '穿戴防护',
    'prot.sans': '未穿戴防护',
    'prot.aide': '仅在极限模式下生效，且只作用于头部和躯干：那里才会询问头盔或背心。若命中四肢，这张牌无论如何都会出现。',
    'ce.protocole': '流程 / 效果',
    'ce.protocolePh': '例：夹板 + 吗啡',
    'ce.matos': '所需器材',
    'ce.matosAide': '点击标签即可选中。在此添加的器材只会出现在这个牌组中（✕ 可移除）。',
    'ce.nouveauMatosPh': '新器材（例：抗辐射剂）',
    'ce.valider': '确认这张牌',

    'mod.apercu': '预览',
    'multi.titre': '多人游戏菜单',
    'multi.nomPartie': '对局名称（主机）',
    'multi.nomPartiePh': '例：Alpha 演习',
    'multi.pseudoHote': '主机名称',
    'multi.pseudoHotePh': '例：Orga',
    'multi.liaison': '设备之间的连接',
    'multi.firebase': 'Firebase 服务器（推荐）',
    'multi.peer': '点对点（旧版）',
    'multi.aideFirebase': '经由服务器：可跨不同网络使用（4G / WiFi），你也可以关闭自己的页面而不中断对局。',
    'multi.aidePeer': '设备之间直接连接。通常需要 TURN 中继，而且你的页面必须保持打开。',
    'multi.creer': '创建对局（主机）',
    'multi.rejoindre': '加入对局',
    'multi.scanner': '扫描二维码',
    'multi.codePh': '对局名称或链接',
    'multi.connexion': '连接',
    'multi.testerReseau': '测试网络',
    'multi.turn': '网络中继（TURN）— 可选',
    'multi.turnAide': '如果测试显示 ❌ TURN，且你的玩家在其他网络上（4G、其他 WiFi），就需要它。在 <b>metered.ca</b> 上创建免费账号（每月 50 GB），添加一个「TURN server」，并把凭据粘贴到这里。它们会通过邀请链接 / 二维码自动传给玩家。',
    'multi.turnUrlPh': 'URL（例：turn:standard.relay.metered.ca:443）',
    'multi.turnUserPh': '用户名',
    'multi.turnPassPh': '密码 / 凭据',
    'multi.turnSave': '保存中继',
    'multi.statut': '连接中...',

    'join.titre': '加入对局',
    'join.etabli': '连接已建立。',
    'join.pseudo': '你的玩家名',
    'join.equipe': '你的队伍',

    'prot.question': '是否穿戴防弹护具？',
    'prot.casque': '是否佩戴防弹头盔？',
    'prot.gilet': '是否穿着防弹背心？',

    'share.titre': '分享牌组',

    'leave.titre': '退出对局？',
    'leave.texte': '你将离开多人会话并返回主菜单。',
    'leave.oui': '是，退出',

    'mode.classique': '经典',
    'mode.avance': '进阶',
    'mode.extreme': '极限',
    'mode.explosion': '爆炸',
    'mode.perso': '自定义',
    'mode.plusExplosion': ' + 爆炸',
    'reg.modeClassique': '经典',
    'reg.modeAvance': '进阶',
    'reg.modeExtreme': '极限（人形图）',
    'reg.custom': '{nom}（自定义）',
    'reg.aucunMateriel': '此模式或此选择不需要任何器材。',
    'reg.voirCarte': '查看这张牌',
    'reg.packExplosion': '爆炸牌包',
    'reg.verrouille': '设置已被主机锁定',

    'cat.titre': '牌库 — {mode}',
    'cat.sectionMode': '模式',
    'cat.sectionPerso': '自定义牌组',
    'cat.sectionExplosion': '爆炸',
    'cat.protPortee': '穿戴防护',
    'cat.sansProt': '未穿戴防护',
    'cat.matos': '器材：',
    'cat.aucuneCarte': '此模式没有任何牌。',
    'carte.membreAleatoire': '随机肢体',

    'btn.modifier': '编辑',
    'btn.partager': '分享',
    'btn.supprimer': '删除',

    'bld.nouveauPaquet': '新牌组',
    'bld.sansNom': '未命名牌组',
    'bld.sansTitre': '无标题',
    'bld.masque': '已隐藏',
    'bld.surAccueil': '显示于主页',
    'bld.aucunPaquet': '目前还没有自定义牌组。',
    'bld.aucunPaquetAide': '点击「+ 创建牌组」开始。',
    'bld.aucuneCarte': '这个牌组里没有牌。',
    'bld.aucuneCarteAide': '点击「+ 添加一张牌」。',
    'bld.nMateriel': '{n} 件器材',
    'bld.enPartieTitre': '对局进行中。',
    'bld.enPartieTexte': '你正在使用组织者分配的牌组。你自己的牌组被暂时收起，退出对局后会立刻归还。',
    'bld.bloqueEnPartie': '对局进行中无法操作：配置来自组织者，你的牌组会被清除。\n\n退出对局即可找回并修改你自己的牌组。',
    'bld.confirmSupprCarte': '删除牌「{nom}」？',
    'bld.confirmSupprPaquet': '删除牌组「{nom}」及其所有牌？',
    'ce.donnezTitre': '请给这张牌起个标题。',
    'ce.confirmRetirerMatos': '从这个牌组移除「{nom}」？使用它的牌也会一并移除。',

    'share.exportTitre': '分享「{nom}」',
    'share.exportAide': '把这个代码发给另一位玩家（短信、WhatsApp、邮件…）。他在「我的牌组」里通过「导入牌组」导入。',
    'share.copierCode': '复制代码',
    'share.importAide': '把收到的分享代码粘贴到这里（以 TMDECK1 开头）。',
    'share.importer': '导入',
    'share.codeCopie': '代码已复制！',
    'share.codeInvalide': '代码无效或不完整。请确认是否完整复制。',
    'share.paquetImporte': '导入的牌组',
    'share.importeOk': '牌组「{nom}」已导入（{n} 张牌）！',

    'icone.cartes': '牌',
    'icone.blesse': '伤员',
    'icone.souffle': '冲击波',
    'icone.balle': '子弹',
    'icone.reticule': '准星',
    'icone.lame': '刀刃',
    'icone.grenade': '手雷',
    'icone.bombe': '炸弹',
    'icone.explosion': '爆炸',
    'icone.feu': '火',
    'icone.decharge': '电击',
    'icone.froid': '寒冷',
    'icone.biohazard': '生物危害',
    'icone.radiation': '辐射',
    'icone.toxique': '毒性',
    'icone.masqueGaz': '防毒面具',
    'icone.zombie': '丧尸',
    'icone.creature': '异形',
    'icone.robot': '机器人',
    'icone.crane': '骷髅',
    'icone.seringue': '注射器',
    'icone.cachets': '药片',
    'icone.perfusion': '输液',
    'icone.pouls': '脉搏',
    'icone.fracture': '骨折',
    'icone.trousse': '急救包',
    'icone.protection': '防护',

    'qg.ligneMode': '模式：{nom}',
    'qg.lignePerso': '自定义：{nom}',
    'qg.joue': '使用中',
    'qg.minEquipes': '（至少 2 支队伍）',
    'qg.horsLigne': '离线',
    'qg.reviendra': '将自动回来…',
    'qg.retirer': '移除',
    'qg.admin': '管理员',
    'qg.kick': '踢出',
    'qg.retirerPaquet': '移除这个牌组',
    'qg.cibleEquipe': '队伍 {nom}',
    'qg.cibleJoueur': '玩家 {nom}',
    'qg.aucunPaquetDistribue': '没有分配任何牌组。',
    'qg.aucunPaquetDistribueAide': '玩家只有「弹道」抽牌。',
    'qg.paquetVide': '在当前配置下，这个牌组是空的。',
    'qg.dejaAttribueCible': '「{nom}」已经分配给这个对象了。',
    'qg.dejaAttribueTous': '「{nom}」已经分配给所有人了：再给某个队伍或玩家没有意义。',
    'qg.indiquezNomEquipe': '请填写队伍名称。',
    'qg.deuxEquipesMini': '至少需要两支队伍。',
    'qg.choisirEquipe': '请选择一支队伍。',
    'qg.choisirJoueur': '请选择一位（已连接的）玩家。',
    'qg.aucunLog': '没有可下载的日志。',
    'qg.logEntete': '对局日志',
    'qg.logExporte': '导出于',
    'qg.confirmCloture': '结束对局？所有玩家都会收到通知并被断开。',
    'qg.confirmClotureTous': '为所有人结束对局？',
    'qg.qrIndisponible': '二维码不可用。',
    'qg.qrIndisponibleAide': '请分享链接或对局名称。',
    'qg.qrAlt': '邀请二维码',

    'log.partieOuverte': '对局已开启：{code}',
    'log.aRejoint': '{nom} 已加入',
    'log.sEstReconnecte': '{nom} 已重新连接',
    'log.quitteLaPartie': '{nom} 退出了对局',
    'log.joueurDeconnecte': '{nom} 已断开（等待重连）',
    'log.pseudoDejaPris': '名称「{demande}」已被占用：该玩家改为「{retenu}」',
    'log.sessionDemarree': '主机会话已启动：{code}',
    'log.sessionReprise': '会话已恢复：{code}',
    'log.configModifiee': '{nom}（副管理员）修改了配置',
    'log.ajoutRefuse': '分配被拒绝（{nom}）：{raison}',
    'log.tirage': '{nom} · 抽牌：{carte}［{gravite}］· {source}',
    'log.coadmin': '{nom} · 副管理员：{valeur}',
    'log.retireDeLaPartie': '已移出对局：{nom}',
    'log.partieCloturee': '对局已结束。',
    'log.partieClotureePar': '对局被 {nom}（副管理员）结束。',
    'qg.logEquipeAjoutee': '已添加队伍：{nom}',
    'qg.logEquipeSupprimee': '队伍已删除，玩家已重新分配。',
    'qg.logPaquetDistribue': '牌组已分配：{nom} → {cible}',
    'qg.logRemplaceParTous': '{nom}：{n} 项定向分配已被「所有人」取代',

    'multi.joueur': '玩家',
    'multi.orga': 'Orga',
    'multi.ouverture': '正在开启对局...',
    'multi.ouvertureImpossible': '无法开启。',
    'multi.creation': '正在创建对局...',
    'multi.reprise': '正在恢复对局...',
    'multi.recherche': '正在查找对局...',
    'multi.connexionReseau': '正在建立网络连接...',
    'multi.recuperation': '正在获取数据...',
    'join.partieNommee': '对局「{nom}」',

    'net.testEnCours': '测试进行中（约 15 秒）...',
    'net.ligneSignalisation': '信令（PeerJS 服务器）',
    'net.ligneStun': 'STUN — 可直接连接',
    'net.ligneTurn': 'TURN — 直连被阻断时的中继',
    'net.aucunRelais': '（未配置中继）',
    'net.relaisEnregistre': '中继已保存。后续连接将使用它，并通过链接 / 二维码传给玩家。',
    'net.relaisEfface': '中继已清除。',
    'net.verdictOk': '一切正常：即使跨不同网络（4G ↔ 路由器），连接也应该没问题。',
    'net.verdictSansTurn': '没有 TURN 中继：跨网络时，或路由器隔离设备时，连接可能失败。请在下方配置中继（网络中继），它会通过二维码传给玩家。',
    'net.verdictStunBloque': '互联网正常但 STUN 被阻断：几乎总是浏览器在阻止 WebRTC 的 UDP。<br>• <b>Opera / Opera GX</b>：关闭内置 VPN，然后在设置中搜索「WebRTC」并选择「不经代理使用 UDP」。<br>• 否则：VPN、杀毒软件或防火墙。用 Chrome 或 Edge 测试确认。<br>• 配置好的 TURN 中继也会走 TCP 443，通常能绕过这种阻断。',
    'net.verdictWebrtcOff': '此浏览器完全禁用了 WebRTC（没有任何网络候选）。请检查浏览器的隐私设置，或换一个浏览器。',
    'net.verdictPasDeSignalisation': '无法连接信令服务器：请检查网络连接。',

    'msg.paquetIndisponible': '这个牌组已不再可用。',
    'msg.aucunPaquetMode': '此模式没有牌组。请检查设置或自定义牌组。',
    'msg.aucuneCarteMateriel': '没有可用的牌。请确认你拥有所需器材（设置）。',
    'msg.aucuneCarteZone': '该部位{etat}没有可用的牌。\n\n请在设置中检查数量和可用器材。',
    'msg.avecProtection': '（穿戴防护）',
    'msg.sansProtection': '（未穿戴防护）',
    'msg.lienCopie': '邀请链接已复制。',
    'msg.codeCopie': '对局代码已复制：',
    'msg.partiePasOuverte': '对局尚未开启。',
    'msg.scannerIndisponible': '二维码扫描不可用（库未加载 — 请检查网络连接）。',
    'msg.peerIndisponible': '多人游戏不可用（PeerJS 库未加载 — 请检查网络连接）。',
    'msg.firebaseIndisponible': 'Firebase 多人游戏不可用（缺少库）。',
    'msg.droitsOrga': '修改被拒绝：你没有这场对局的组织者权限。',
    'msg.devenuCoOrga': '你已成为副组织者：可通过右上角的多人游戏按钮进入对局指挥部。',
    'msg.gradeRetire': '管理员权限已被取消。',
    'msg.retireDeLaPartie': '你已被移出对局。',
    'msg.exclu': '你已被踢出对局。',
    'msg.orgaACloture': '组织者已结束对局。',
    'msg.partieTerminee': '对局已结束。',
    'msg.nomPartiePris': '已有同名对局且属于他人。请换一个名称。',
    'msg.nomPartieDejaPris': '这个对局名称已被使用（或旧会话尚未过期）。请等一分钟或换个名称。',
    'msg.partieIntrouvable': '找不到对局。请向组织者核对名称。',
    'msg.partieIntrouvableHote': '找不到这场对局。请确认主机没有关闭网页或取消对局。',
    'msg.partieCloturee': '这场对局已结束。',
    'msg.erreurPeer': 'PeerJS 错误',
    'msg.repriseImpossible': '暂时无法恢复对局「{nom}」（{raison}）。下次回到本页时会再试一次，或用相同名称重新创建对局以找回你的玩家。',
    'msg.dejaHote': '此设备上你已在主持一场对局。请先在主机界面退出旧对局，才能以玩家身份加入另一场。',
    'msg.indiquezNomPartie': '请填写对局名称或扫描二维码。',
    'msg.indiquezPseudo': '请填写玩家名：组织者会以这个名字在对局中看到你。',
    'msg.delaiDepasse': '超时：无法与主机建立连接。请确认他的页面已打开，然后在多人游戏菜单中运行「测试网络」：若 TURN 失败，主机需要配置一个中继（「网络中继」）— 它会通过其二维码自动传递。',
    'msg.hoteIntrouvable': '连接失败：找不到主机或网络不稳定。',
    'msg.connexionImpossible': '连接失败。',
    'msg.connexionPerdue': '连接已断开。请重新加入对局。',
    'msg.connexionPerdueHote': '与主机的连接已断开。',
    'msg.reconnexionImpossible': '无法重新连接：对局似乎已结束，或主机无法访问。',
    'msg.connecte': '已连接到对局！',
    'msg.pseudoRemplace': '该名称在对局中已被占用。你显示为：{nom}',
    'msg.changementEquipe': '队伍变更'
},
zone: {
    'Membres': '四肢',
    'Tête ou Torse': '头部或躯干',
    'Torse': '躯干',
    'Tête': '头部',
    'Bras': '手臂',
    'Jambe': '腿部',
    'Jambes': '双腿',
    'Torse et bras': '躯干与手臂'
},
grav: {
    'DÉCÈS': '死亡',
    'Critique': '危重',
    'Grave': '重伤',
    'Légère': '轻伤',
    'Spécial': '特殊'
},
membre: {
    'Bras Gauche': '左臂',
    'Bras Droit': '右臂',
    'Jambe Gauche': '左腿',
    'Jambe Droite': '右腿'
},
mat: {
    'Garrot': '止血带',
    'Bandage': '绷带',
    'Poche de transfusion': '输血袋',
    'Attelle': '夹板',
    'Morphine': '吗啡',
    'Épinéphrine': '肾上腺素',
    'Pansement 3 côtés': '三边封闭敷料'
},
titre: {
    'DCD': '阵亡',
    'Inconscient': '昏迷',
    'Hémorragie': '大出血',
    'Saignement': '出血',
    'Fracture': '骨折',
    'Éraflure': '擦伤',
    'Choc Casque': '头盔中弹',
    'Choc Gilet': '背心中弹',
    'Plaie soufflante': '开放性气胸',
    'Saignement grave': '严重出血',
    'Prot. Balistique': '防弹护具',
    'Choc Balistique': '弹道冲击',
    'Impact sur casque': '击中头盔',
    'Plaie au front': '前额裂伤',
    'Traumatisme crânien': '颅脑损伤',
    'Tir à la tête': '头部中弹',
    'Impact sur plaque': '击中防弹插板',
    'Éraflure au flanc': '侧腹擦伤',
    'Côtes fracturées': '肋骨骨折',
    'Pneumothorax': '气胸',
    'Hémorragie interne': '内出血',
    'Tir vital': '要害中弹',
    'Balle dans l\'avant-bras': '前臂中弹',
    'Fracture de l\'avant-bras': '前臂骨折',
    'Artère brachiale': '肱动脉',
    'Balle au mollet': '小腿中弹',
    'Fracture du fémur': '股骨骨折',
    'Fracture de la rotule': '髌骨骨折',
    'Artère fémorale': '股动脉',
    'DCD (Blast)': '阵亡（冲击波）',
    'Plaie Soufflante': '开放性气胸',
    'Hémorragie Massive': '大量出血',
    'Saignement Grave': '严重出血',
    'Fracture Ouverte': '开放性骨折',
    'Éraflure (Éclat)': '擦伤（弹片）',
    'Souffle (Blast)': '冲击波',
    'Éraflure au visage': '面部擦伤',
    'Éclats au bras': '手臂弹片伤',
    'Criblage d\'éclats': '弹片密集伤',
    'Souffle d\'explosion': '爆炸冲击波'
},
soin: {
    'Respawn direct': '直接复活',
    '30s massage + Poche': '心肺复苏 30 秒 + 输血袋',
    'Garrot + Poche': '止血带 + 输血袋',
    'Bandage + Poche': '绷带 + 输血袋',
    'Attelle': '夹板',
    'Bandage': '绷带',
    'Si Protégé : Sonné (Médic aide à relever). Sinon : Bandage ([MEMBRE_ALEATOIRE])': '若有防护：眩晕（医疗兵扶起）。否则：绷带（[MEMBRE_ALEATOIRE]）',
    'Bandage + Massage + Épi + Poche': '绷带 + 心肺复苏 + 肾上腺素 + 输血袋',
    'Pnsmt 3 côtés + Morphine + Poche': '三边封闭敷料 + 吗啡 + 输血袋',
    'Garrot + Bandage + Morphine + Poche': '止血带 + 绷带 + 吗啡 + 输血袋',
    'Bandage + Morphine': '绷带 + 吗啡',
    'Bandage + Attelle + Morphine': '绷带 + 夹板 + 吗啡',
    'Tête — protégé : rien, sinon Éraflure (Bandage). Torse — protégé : Hématome (Morphine), sinon Bandage': '头部 — 有防护：无伤；否则擦伤（绷带）。躯干 — 有防护：血肿（吗啡）；否则绷带',
    'Protégé : Sonné (le médic aide à relever). Sinon : DCD': '有防护：眩晕（医疗兵扶起）。否则：阵亡',
    'Repos 2 minutes': '休息 2 分钟',
    'Bandage + Épinéphrine + Morphine': '绷带 + 肾上腺素 + 吗啡',
    'Repos 1 minute': '休息 1 分钟',
    'Bandage compressif + Morphine': '加压绷带 + 吗啡',
    'Pansement 3 côtés + Morphine': '三边封闭敷料 + 吗啡',
    'Bandage + Poche de transfusion + Épinéphrine': '绷带 + 输血袋 + 肾上腺素',
    'Attelle + Bandage': '夹板 + 绷带',
    'Garrot + Bandage + Poche de transfusion': '止血带 + 绷带 + 输血袋',
    'Attelle + Bandage + Morphine': '夹板 + 绷带 + 吗啡',
    'Attelle + Morphine': '夹板 + 吗啡',
    'Garrot + Poche de transfusion + Épinéphrine': '止血带 + 输血袋 + 肾上腺素',
    'Bandage + 30s Massage + Épi + Poche': '绷带 + 心肺复苏 30 秒 + 肾上腺素 + 输血袋',
    '2x Bandages + Morphine': '绷带 ×2 + 吗啡',
    'Garrot + Pansement 3 côtés + Poche de transfusion + Épinéphrine': '止血带 + 三边封闭敷料 + 输血袋 + 肾上腺素',
    'Casque porté : aucune blessure.\nSinon : Éraflure → Bandage': '戴头盔：无伤。\n否则：擦伤 → 绷带',
    'Gilet porté : Hématome → Morphine.\nSinon : Bandage': '穿背心：血肿 → 吗啡。\n否则：绷带',
    'Casque porté : Sonné → le médic aide à relever.\nSinon : DCD': '戴头盔：眩晕 → 医疗兵扶起。\n否则：阵亡',
    'Gilet porté : Sonné → le médic aide à relever.\nSinon : DCD': '穿背心：眩晕 → 医疗兵扶起。\n否则：阵亡'
},
bilan: {
    'Impact direct sur le casque lourd.': '重型头盔被直接击中。',
    'Plaie ouverte et profonde au front.': '前额深部开放性伤口。',
    'Traumatisme crânien sévère.': '严重颅脑损伤。',
    'Tir direct à la tête (sans port du casque).': '头部被直接击中（未戴头盔）。',
    'Impact encaissé par la plaque balistique du porte-plaques.': '冲击被战术背心的防弹插板挡下。',
    'Éraflure sur le flanc, hors de la zone couverte par les plaques balistiques.': '侧腹擦伤，位于防弹插板覆盖范围之外。',
    'Fracture de plusieurs côtes par impact lourd.': '重击导致多根肋骨骨折。',
    'Pneumothorax suite à une balle perforante latérale.': '侧向穿透弹造成气胸。',
    'Blessure perforante à l\'abdomen causant une importante hémorragie interne.': '腹部穿透伤，造成大量内出血。',
    'Tir direct au niveau du cœur ou de la colonne vertébrale (sans port de plaques balistiques).': '心脏或脊柱部位被直接击中（未穿防弹插板）。',
    'Balle logée dans les tissus mous de l\'avant-bras.': '子弹卡在前臂软组织内。',
    'Fracture de l\'os de l\'avant-bras (radius / cubitus).': '前臂骨折（桡骨 / 尺骨）。',
    'Sectionnement de l\'artère brachiale.': '肱动脉被切断。',
    'Balle logée dans le muscle du mollet.': '子弹卡在小腿肌肉内。',
    'Fracture du fémur.': '股骨骨折。',
    'Fracture de la rotule du genou.': '膝部髌骨骨折。',
    'Sectionnement de l\'artère fémorale.': '股动脉被切断。',
    'Éraflure superficielle due à un éclat sur la joue ou le lobe de l\'oreille.': '弹片在脸颊或耳垂造成的表浅擦伤。',
    'Multiples plaies par éclats de grenade sur le bras.': '手臂多处手雷弹片伤。',
    'Criblage d\'éclats de shrapnel sur l\'ensemble des deux jambes.': '双腿布满弹片伤。',
    'Traumatisme contondant lourd au torse et sectionnement artériel à un bras suite à une explosion à proximité.': '近距离爆炸造成躯干严重钝性伤，并切断一侧手臂动脉。'
}
};
