/* BSE MEDICAL SYSTEM — ESPAÑOL
   Les tables zone/grav/mat/membre/titre/soin/bilan sont indexees par le
   texte FRANCAIS d'origine, qui reste la cle interne des cartes. */
window.BSE_I18N.es = {
ui: {
    'hdr.multijoueur': 'Multijugador',
    'hdr.quitter': 'Salir de la partida',
    'hdr.sortir': 'Salir',
    'hdr.paquets': 'Mis mazos',
    'hdr.reglages': 'Ajustes',
    'hdr.bseLien': 'Bravo Sierra Events — abrir el sitio web',
    'hdr.bseAria': 'Abrir el sitio web de Bravo Sierra Events',
    'statut.solo': 'Solo',
    'statut.organisateur': 'Organizador',
    'statut.coadmin': 'Coadmin',
    'statut.reconnexion': '{nom} · Reconectando a la partida…',
    'paquet.balistique': 'Balística',
    'paquet.explosion': 'Explosión',

    'jeu.titre': 'Diagnóstico médico',
    'jeu.sous': 'Toca para lanzar el diagnóstico',
    'jeu.paquetActif': 'Mazo activo',
    'jeu.chargement': 'Cargando...',
    'jeu.cartes': '{n} cartas',

    'march.titre': 'Evaluación MARCH',
    'march.m': 'Hemorragia masiva',
    'march.a': 'Vía aérea',
    'march.r': 'Respiración',
    'march.c': 'Circulación',
    'march.h': 'Cabeza / Hipotermia',
    'march.analyse': 'Evaluación en curso…',

    'sil.titre': '¿Qué zona ha sido alcanzada?',
    'sil.sous': 'Toca la parte del cuerpo afectada',
    'sil.miroir': '(vista en espejo: su brazo derecho está a tu izquierda)',

    'fiche.mort': 'Muerto en combate',
    'fiche.mortSous': 'Tiempo agotado — hemorragia mortal',
    'fiche.fermer': 'Cerrar el expediente',
    'fiche.label': 'Ficha de triaje',
    'fiche.zone': 'Zona alcanzada',
    'fiche.bilan': 'Evaluación',
    'fiche.protocole': 'Protocolo de cuidados',
    'fiche.hemorragie': 'Hemorragia activa — urgencia vital',
    'fiche.nouveau': 'Nuevo diagnóstico',
    'fiche.soigner': 'Cuidados realizados (salvar)',
    'fiche.stabilise': '¡PACIENTE ESTABILIZADO!',
    'fiche.protPortee': 'Protección balística puesta: {reponse}',
    'fiche.avecProtection': ' con protección puesta',

    'btn.annuler': 'Cancelar',
    'btn.valider': 'Confirmar',
    'btn.fermer': 'Cerrar',
    'btn.retour': 'Volver',
    'btn.copier': 'Copiar',
    'btn.ouvrir': 'Abrir',
    'btn.oui': 'Sí',
    'btn.non': 'No',

    'qg.titre': 'CG',
    'qg.partie': 'Partida',
    'qg.enLigne': 'En línea',
    'qg.ongletInvitation': 'Invitación',
    'qg.ongletJoueurs': 'Jugadores',
    'qg.ongletEquipes': 'Equipos',
    'qg.ongletEditeur': 'Editor',
    'qg.ongletPaquets': 'Mazos',
    'qg.ongletLogs': 'Registro',
    'qg.codeAide': 'Código de la partida — dícteselo a los jugadores',
    'qg.lienAide': 'Enlace de conexión (compartir o QR)',
    'qg.qrGeneration': 'Generando...',
    'qg.qrAide': 'Los jugadores escanean el código QR o escriben el nombre de la partida en el menú Unirse.',
    'qg.joueurs': 'JUGADORES',
    'qg.equipes': 'EQUIPOS DE LA PARTIDA',
    'qg.nomEquipePh': 'Nombre del equipo',
    'qg.couleurEquipePh': '#hex color',
    'qg.ajouterEquipe': '+ EQUIPO',
    'qg.editeur': 'EDITOR DE MAZOS',
    'qg.editeurAide': 'Ajusta las cantidades, el material y el riesgo de muerte de todos tus mazos antes de repartirlos.',
    'qg.paquetsAttribues': 'MAZOS ASIGNADOS',
    'qg.paquetsAide1': 'Elige de qué robará cada jugador: Clásico, Avanzado, Extremo, Explosión o uno de tus mazos propios. El mazo asignado <b>sustituye</b> el modo de juego del destinatario — solo verá ese, con las cantidades fijadas en el Editor.',
    'qg.paquetsAide2': 'Un jugador sin ninguna asignación juega el <b>modo actual</b> definido en el Editor.',
    'qg.toutLeMonde': 'Todo el mundo',
    'qg.uneEquipe': 'Solo un equipo',
    'qg.unJoueur': 'Solo un jugador',
    'qg.ajouterPaquet': 'Asignar este mazo',
    'qg.journal': 'REGISTRO EN DIRECTO',
    'qg.journalAide': 'Los eventos de un jugador aparecen en el color de su equipo.',
    'qg.telechargerLogs': 'Descargar el registro (.txt)',
    'qg.effacerAffichage': 'Borrar la pantalla',
    'qg.cloturer': 'Cerrar la partida (expulsar a los jugadores)',
    'qg.retourSession': 'Volver al inicio (mantener la sesión)',

    'reg.titre': 'Ajustes del sistema',
    'reg.profil': 'Perfil multijugador',
    'reg.pseudo': 'Tu nombre de jugador',
    'reg.pseudoPh': 'Ej.: Doc',
    'reg.mode': 'Modo de juego',
    'reg.hardcore': 'Opción hardcore',
    'reg.activerMort': 'Activar el riesgo de muerte',
    'reg.proba': 'Probabilidad',
    'reg.probaSous': 'sobre una herida elegible',
    'reg.delaiMin': 'Tiempo mínimo',
    'reg.delaiMinSous': 'antes de la muerte',
    'reg.delaiMax': 'Tiempo máximo',
    'reg.etendreGraves': 'Extender a las heridas Graves',
    'reg.explosion': 'Explosión',
    'reg.activerExplosion': 'Activar las cartas de explosión',
    'reg.materiel': 'Material necesario',
    'reg.cartesActives': 'Cartas activas',
    'reg.catalogue': 'Catálogo',
    'reg.oeilAide': 'El ojo de cada línea abre el catálogo del modo en la carta correspondiente.',
    'reg.aide': 'Ayuda',
    'reg.aideTexte': 'La guía de uso completa, para leer en el briefing. Sigue disponible sin conexión una vez abierta.',
    'reg.guide': 'Guía de uso (PDF)',

    'lang.titre': 'Idioma',
    'lang.choisir': 'Elegir el idioma',

    'bld.titre': 'Mis mazos',
    'bld.sous': 'Crea tus propios mazos de cartas y muéstralos en la pantalla de inicio.',
    'bld.creer': '+ Crear un mazo',
    'bld.importer': 'Importar un mazo',
    'bld.edition': 'Editar el mazo',
    'bld.nom': 'Nombre del mazo',
    'bld.nomPh': 'Ej.: Heridas químicas',
    'bld.afficherAccueil': 'Mostrar en la pantalla de inicio',
    'bld.modeExtreme': 'Modo extremo',
    'bld.modeExtremeSous': '(silueta: zona alcanzada + protección)',
    'bld.icone': 'Icono del botón',
    'bld.iconeAide': 'Identifica el mazo en la pantalla de inicio y en la de los jugadores a los que se lo asignas.',
    'bld.cartes': 'Cartas',
    'bld.ajouterCarte': '+ Añadir una carta',
    'bld.enregistrer': 'Guardar',
    'bld.supprimerPaquet': 'Eliminar el mazo',

    'ce.titreEcran': 'Carta',
    'ce.gravite': 'Gravedad',
    'ce.titre': 'Título',
    'ce.titrePh': 'Ej.: Fractura',
    'ce.zone': 'Zona alcanzada',
    'ce.zonePh': 'Ej.: Brazo',
    'ce.protocole': 'Protocolo / efecto',
    'ce.protocolePh': 'Ej.: Férula + Morfina',
    'ce.matos': 'Material necesario',
    'ce.matosAide': 'Toca una ficha para seleccionarla. El material añadido aquí solo se ofrece en este mazo (✕ para quitarlo).',
    'ce.nouveauMatosPh': 'Material nuevo (ej.: Anti-rad)',
    'ce.valider': 'Confirmar la carta',

    'mod.apercu': 'Vista previa',
    'multi.titre': 'Menú multijugador',
    'multi.nomPartie': 'Nombre de la partida (anfitrión)',
    'multi.nomPartiePh': 'Ej.: Ejercicio Alfa',
    'multi.pseudoHote': 'Nombre del anfitrión',
    'multi.pseudoHotePh': 'Ej.: Orga',
    'multi.liaison': 'Enlace entre dispositivos',
    'multi.firebase': 'Servidor Firebase (recomendado)',
    'multi.peer': 'Punto a punto (antiguo)',
    'multi.aideFirebase': 'Pasa por el servidor: funciona entre redes distintas (4G / WiFi), y puedes cerrar tu página sin cortar la partida.',
    'multi.aidePeer': 'Conexión directa entre dispositivos. Suele necesitar un relé TURN, y tu página debe permanecer abierta.',
    'multi.creer': 'Crear una partida (anfitrión)',
    'multi.rejoindre': 'Unirse a una partida',
    'multi.scanner': 'Escanear el código QR',
    'multi.codePh': 'Nombre de la partida o enlace',
    'multi.connexion': 'Conectar',
    'multi.testerReseau': 'Probar la red',
    'multi.turn': 'Relé de red (TURN) — opcional',
    'multi.turnAide': 'Necesario si la prueba indica ❌ TURN y tus jugadores están en otras redes (4G, otro WiFi). Crea una cuenta gratuita en <b>metered.ca</b> (50 GB/mes), añade un «TURN server» y pega aquí sus credenciales. Se transmiten automáticamente a los jugadores mediante el enlace / código QR de invitación.',
    'multi.turnUrlPh': 'URL (ej.: turn:standard.relay.metered.ca:443)',
    'multi.turnUserPh': 'Usuario',
    'multi.turnPassPh': 'Contraseña / credencial',
    'multi.turnSave': 'Guardar el relé',
    'multi.statut': 'Conectando...',

    'join.titre': 'Unirse a la partida',
    'join.etabli': 'Conexión establecida.',
    'join.pseudo': 'Tu nombre de jugador',
    'join.equipe': 'Tu equipo',

    'prot.question': '¿Protección balística puesta?',
    'prot.casque': '¿Casco balístico puesto?',
    'prot.gilet': '¿Chaleco antibalas puesto?',

    'share.titre': 'Compartir el mazo',

    'leave.titre': '¿Salir de la partida?',
    'leave.texte': 'Saldrás de la sesión multijugador y volverás al menú principal.',
    'leave.oui': 'Sí, salir',

    'mode.classique': 'Clásico',
    'mode.avance': 'Avanzado',
    'mode.extreme': 'Extremo',
    'mode.explosion': 'Explosión',
    'mode.perso': 'Propio',
    'mode.plusExplosion': ' + explosión',
    'reg.modeClassique': 'CLÁSICO',
    'reg.modeAvance': 'AVANZADO',
    'reg.modeExtreme': 'EXTREMO (silueta)',
    'reg.custom': '{nom} (Propio)',
    'reg.aucunMateriel': 'No se necesita material para este modo o esta selección.',
    'reg.voirCarte': 'Ver la carta',
    'reg.packExplosion': 'Pack explosión',
    'reg.verrouille': 'Ajustes bloqueados por el anfitrión',

    'cat.titre': 'Catálogo — {mode}',
    'cat.sectionMode': 'Modo',
    'cat.sectionPerso': 'Mazo propio',
    'cat.sectionExplosion': 'Explosión',
    'cat.protPortee': 'protección puesta',
    'cat.sansProt': 'sin protección',
    'cat.matos': 'Material:',
    'cat.aucuneCarte': 'No hay cartas para este modo.',
    'carte.membreAleatoire': 'miembro al azar',

    'btn.modifier': 'Modificar',
    'btn.partager': 'Compartir',
    'btn.supprimer': 'Eliminar',

    'bld.nouveauPaquet': 'Mazo nuevo',
    'bld.sansNom': 'Mazo sin nombre',
    'bld.sansTitre': 'Sin título',
    'bld.masque': 'Oculto',
    'bld.surAccueil': 'En la pantalla de inicio',
    'bld.aucunPaquet': 'Todavía no hay ningún mazo propio.',
    'bld.aucunPaquetAide': 'Pulsa «+ CREAR UN MAZO» para empezar.',
    'bld.aucuneCarte': 'No hay cartas en este mazo.',
    'bld.aucuneCarteAide': 'Pulsa «+ AÑADIR UNA CARTA».',
    'bld.nMateriel': '{n} material(es)',
    'bld.enPartieTitre': 'Partida en curso.',
    'bld.enPartieTexte': 'Estás jugando los mazos asignados por el organizador. Tus mazos propios están apartados y se te devolverán en cuanto salgas de la partida.',
    'bld.bloqueEnPartie': 'Imposible durante una partida: la configuración viene del organizador y tu mazo se borraría.\n\nSal de la partida para recuperar y modificar tus mazos propios.',
    'bld.confirmSupprCarte': '¿Eliminar la carta «{nom}»?',
    'bld.confirmSupprPaquet': '¿Eliminar el mazo «{nom}» y todas sus cartas?',
    'ce.donnezTitre': 'Ponle un título a la carta.',
    'ce.confirmRetirerMatos': '¿Quitar «{nom}» de este mazo? También se quitará de las cartas que lo usan.',

    'share.exportTitre': 'Compartir «{nom}»',
    'share.exportAide': 'Envía este código a otro jugador (SMS, WhatsApp, correo...). Lo importará mediante «IMPORTAR UN MAZO» en Mis mazos.',
    'share.copierCode': 'COPIAR EL CÓDIGO',
    'share.importAide': 'Pega aquí el código de compartición recibido (empieza por TMDECK1).',
    'share.importer': 'IMPORTAR',
    'share.codeCopie': '¡Código copiado!',
    'share.codeInvalide': 'Código no válido o incompleto. Comprueba que se copió entero.',
    'share.paquetImporte': 'Mazo importado',
    'share.importeOk': '¡Mazo «{nom}» importado ({n} cartas)!',

    'icone.cartes': 'Cartas',
    'icone.blesse': 'Herido',
    'icone.souffle': 'Onda expansiva',
    'icone.balle': 'Bala',
    'icone.reticule': 'Retícula',
    'icone.lame': 'Hoja',
    'icone.grenade': 'Granada',
    'icone.bombe': 'Bomba',
    'icone.explosion': 'Explosión',
    'icone.feu': 'Fuego',
    'icone.decharge': 'Descarga',
    'icone.froid': 'Frío',
    'icone.biohazard': 'Riesgo biológico',
    'icone.radiation': 'Radiación',
    'icone.toxique': 'Tóxico',
    'icone.masqueGaz': 'Máscara antigás',
    'icone.zombie': 'Zombi',
    'icone.creature': 'Criatura',
    'icone.robot': 'Robot',
    'icone.crane': 'Calavera',
    'icone.seringue': 'Jeringa',
    'icone.cachets': 'Pastillas',
    'icone.perfusion': 'Perfusión',
    'icone.pouls': 'Pulso',
    'icone.fracture': 'Fractura',
    'icone.trousse': 'Botiquín',
    'icone.protection': 'Protección',

    'qg.ligneMode': 'Modo: {nom}',
    'qg.lignePerso': 'Propio: {nom}',
    'qg.joue': 'EN JUEGO',
    'qg.minEquipes': '(mín. 2 equipos)',
    'qg.horsLigne': 'sin conexión',
    'qg.reviendra': 'Volverá automáticamente…',
    'qg.retirer': 'Quitar',
    'qg.admin': 'Admin',
    'qg.kick': 'Expulsar',
    'qg.retirerPaquet': 'Quitar este mazo',
    'qg.cibleEquipe': 'Equipo {nom}',
    'qg.cibleJoueur': 'Jugador {nom}',
    'qg.aucunPaquetDistribue': 'Ningún mazo asignado.',
    'qg.aucunPaquetDistribueAide': 'Los jugadores solo tienen la tirada Balística.',
    'qg.paquetVide': 'Este mazo está vacío con la configuración actual.',
    'qg.dejaAttribueCible': '«{nom}» ya está asignado a este destinatario.',
    'qg.dejaAttribueTous': '«{nom}» ya está asignado a todo el mundo: no sirve de nada dárselo otra vez a un equipo o a un jugador.',
    'qg.indiquezNomEquipe': 'Indica un nombre de equipo.',
    'qg.deuxEquipesMini': 'Hacen falta al menos dos equipos.',
    'qg.choisirEquipe': 'Elige un equipo.',
    'qg.choisirJoueur': 'Elige un jugador (conectado).',
    'qg.aucunLog': 'No hay registro que descargar.',
    'qg.logEntete': 'registro de la partida',
    'qg.logExporte': 'Exportado el',
    'qg.confirmCloture': '¿Cerrar la partida? Se avisará y se desconectará a todos los jugadores.',
    'qg.confirmClotureTous': '¿Cerrar la partida para todo el mundo?',
    'qg.qrIndisponible': 'QR no disponible.',
    'qg.qrIndisponibleAide': 'Comparte el enlace o el nombre de la partida.',
    'qg.qrAlt': 'Código QR de invitación',

    'log.partieOuverte': 'Partida abierta: {code}',
    'log.aRejoint': '{nom} se ha unido',
    'log.sEstReconnecte': '{nom} se ha reconectado',
    'log.quitteLaPartie': '{nom} sale de la partida',
    'log.joueurDeconnecte': '{nom} desconectado (esperando reconexión)',
    'log.pseudoDejaPris': 'Nombre «{demande}» ya en uso: este jugador pasa a ser «{retenu}»',
    'log.sessionDemarree': 'Sesión de anfitrión iniciada: {code}',
    'log.sessionReprise': 'Sesión reanudada: {code}',
    'log.configModifiee': '{nom} (coadmin) ha modificado la configuración',
    'log.ajoutRefuse': 'Asignación rechazada ({nom}): {raison}',
    'log.tirage': '{nom} · tirada: {carte} [{gravite}] · {source}',
    'log.coadmin': '{nom} · coadmin: {valeur}',
    'log.retireDeLaPartie': 'Retirado de la partida: {nom}',
    'log.partieCloturee': 'Partida cerrada.',
    'log.partieClotureePar': 'Partida cerrada por {nom} (coadmin).',
    'qg.logEquipeAjoutee': 'Equipo añadido: {nom}',
    'qg.logEquipeSupprimee': 'Equipo eliminado, jugadores reasignados.',
    'qg.logPaquetDistribue': 'Mazo asignado: {nom} → {cible}',
    'qg.logRemplaceParTous': '{nom}: {n} asignación(es) dirigida(s) sustituida(s) por «todo el mundo»',

    'multi.joueur': 'Jugador',
    'multi.orga': 'Orga',
    'multi.ouverture': 'Abriendo la partida...',
    'multi.ouvertureImpossible': 'No se ha podido abrir.',
    'multi.creation': 'Creando la partida...',
    'multi.reprise': 'Reanudando la partida...',
    'multi.recherche': 'Buscando la partida...',
    'multi.connexionReseau': 'Conexión de red en curso...',
    'multi.recuperation': 'Recuperando los datos...',
    'join.partieNommee': 'Partida «{nom}»',

    'net.testEnCours': 'Prueba en curso (~15 s)...',
    'net.ligneSignalisation': 'Señalización (servidor PeerJS)',
    'net.ligneStun': 'STUN — conexión directa posible',
    'net.ligneTurn': 'TURN — relé si la directa está bloqueada',
    'net.aucunRelais': '(ningún relé configurado)',
    'net.relaisEnregistre': 'Relé guardado. Se usará en las próximas conexiones y se transmitirá a los jugadores mediante el enlace / código QR.',
    'net.relaisEfface': 'Relé borrado.',
    'net.verdictOk': 'Todo funciona: la conexión debería aguantar, incluso entre redes distintas (4G ↔ router).',
    'net.verdictSansTurn': 'Sin relé TURN: la conexión puede fallar entre redes distintas o si el router aísla sus dispositivos. Configura un relé más abajo (Relé de red); se transmitirá a los jugadores mediante el código QR.',
    'net.verdictStunBloque': 'STUN está bloqueado aunque Internet funciona: casi siempre es el NAVEGADOR el que bloquea el UDP de WebRTC.<br>• <b>Opera / Opera GX</b>: desactiva la VPN integrada y busca «WebRTC» en los ajustes, luego elige «Usar UDP sin proxy».<br>• Si no: VPN, antivirus o cortafuegos. Prueba en Chrome o Edge para confirmarlo.<br>• Un relé TURN configurado también pasa por TCP 443 y suele sortear este bloqueo.',
    'net.verdictWebrtcOff': 'WebRTC está completamente desactivado en este navegador (ningún candidato de red). Revisa los ajustes de privacidad del navegador o prueba con otro.',
    'net.verdictPasDeSignalisation': 'Servidor de señalización inaccesible: comprueba el acceso a Internet.',

    'msg.paquetIndisponible': 'Este mazo ya no está disponible.',
    'msg.aucunPaquetMode': 'No hay mazo de cartas para este modo. Revisa los ajustes o el mazo propio.',
    'msg.aucuneCarteMateriel': 'No hay ninguna carta disponible. Comprueba que tienes el material necesario (Ajustes).',
    'msg.aucuneCarteZone': 'No hay ninguna carta disponible para esta zona{etat}.\n\nRevisa las cantidades y el material disponible en los Ajustes.',
    'msg.avecProtection': ' con protección puesta',
    'msg.sansProtection': ' sin protección',
    'msg.lienCopie': 'Enlace de invitación copiado.',
    'msg.codeCopie': 'Código de la partida copiado:',
    'msg.partiePasOuverte': 'La partida todavía no está abierta.',
    'msg.scannerIndisponible': 'Escáner QR no disponible (biblioteca no cargada — comprueba la conexión a Internet).',
    'msg.peerIndisponible': 'Multijugador no disponible (biblioteca PeerJS no cargada — comprueba la conexión a Internet).',
    'msg.firebaseIndisponible': 'El multijugador Firebase no está disponible (falta la biblioteca).',
    'msg.droitsOrga': 'Modificación rechazada: no tienes permisos de organizador en esta partida.',
    'msg.devenuCoOrga': 'Eres coorganizador: el CG de la partida está accesible desde el botón multijugador, arriba a la derecha.',
    'msg.gradeRetire': 'Permisos de admin retirados.',
    'msg.retireDeLaPartie': 'Has sido retirado de la partida.',
    'msg.exclu': 'Has sido expulsado de la partida.',
    'msg.orgaACloture': 'El organizador ha cerrado la partida.',
    'msg.partieTerminee': 'La partida ha terminado.',
    'msg.nomPartiePris': 'Ya hay una partida con ese nombre y pertenece a otra persona. Elige otro nombre.',
    'msg.nomPartieDejaPris': 'Ese nombre de partida ya está en uso (o la sesión anterior aún no ha caducado). Espera un minuto o cambia de nombre.',
    'msg.partieIntrouvable': 'Partida no encontrada. Comprueba el nombre con el organizador.',
    'msg.partieIntrouvableHote': 'No se encuentra la partida. Comprueba que el anfitrión no haya cerrado su página web ni cancelado la partida.',
    'msg.partieCloturee': 'Esta partida está cerrada.',
    'msg.erreurPeer': 'Error de PeerJS',
    'msg.repriseImpossible': 'De momento no se puede reanudar la partida «{nom}» ({raison}). Se reintentará la próxima vez que vuelvas a la página, o vuelve a crear la partida con el mismo nombre para recuperar a tus jugadores.',
    'msg.dejaHote': 'Ya estás alojando una partida en este dispositivo. Sal de la partida anterior desde la pantalla de anfitrión para poder unirte a otra como jugador.',
    'msg.indiquezNomPartie': 'Indica el nombre de la partida o escanea el código QR.',
    'msg.indiquezPseudo': 'Indica un nombre de jugador: así es como te verá el organizador en la partida.',
    'msg.delaiDepasse': 'Tiempo agotado: no se ha podido establecer el enlace con el anfitrión. Comprueba que su página esté abierta y lanza «Probar la red» en el menú multijugador: si TURN falla, el anfitrión debe configurar un relé («Relé de red») — se transmitirá automáticamente por su código QR.',
    'msg.hoteIntrouvable': 'Conexión imposible: anfitrión no encontrado o red inestable.',
    'msg.connexionImpossible': 'Conexión imposible.',
    'msg.connexionPerdue': 'Conexión perdida. Vuelve a intentar unirte a la partida.',
    'msg.connexionPerdueHote': 'Se ha perdido la conexión con el anfitrión.',
    'msg.reconnexionImpossible': 'Reconexión imposible: la partida parece terminada o el anfitrión inaccesible.',
    'msg.connecte': '¡Conectado a la partida!',
    'msg.pseudoRemplace': 'Ese nombre ya estaba ocupado en la partida. Apareces como: {nom}',
    'msg.changementEquipe': 'Cambio de equipo'
},
zone: {
    'Tête ou Torse': 'Cabeza o Torso',
    'Torse': 'Torso',
    'Tête': 'Cabeza',
    'Bras': 'Brazo',
    'Jambe': 'Pierna',
    'Jambes': 'Piernas',
    'Torse et bras': 'Torso y brazo'
},
grav: {
    'DÉCÈS': 'MUERTE',
    'Critique': 'Crítica',
    'Grave': 'Grave',
    'Légère': 'Leve',
    'Spécial': 'Especial'
},
membre: {
    'Bras Gauche': 'Brazo izquierdo',
    'Bras Droit': 'Brazo derecho',
    'Jambe Gauche': 'Pierna izquierda',
    'Jambe Droite': 'Pierna derecha'
},
mat: {
    'Garrot': 'Torniquete',
    'Bandage': 'Vendaje',
    'Poche de transfusion': 'Bolsa de sangre',
    'Attelle': 'Férula',
    'Morphine': 'Morfina',
    'Épinéphrine': 'Adrenalina',
    'Pansement 3 côtés': 'Apósito de 3 lados'
},
titre: {
    'DCD': 'MUERTO',
    'Inconscient': 'Inconsciente',
    'Hémorragie': 'Hemorragia',
    'Saignement': 'Sangrado',
    'Fracture': 'Fractura',
    'Éraflure': 'Rasguño',
    'Choc Casque': 'Impacto en el casco',
    'Choc Gilet': 'Impacto en el chaleco',
    'Plaie soufflante': 'Herida torácica aspirante',
    'Saignement grave': 'Sangrado grave',
    'Prot. Balistique': 'Prot. balística',
    'Choc Balistique': 'Choque balístico',
    'Impact sur casque': 'Impacto en el casco',
    'Plaie au front': 'Herida en la frente',
    'Traumatisme crânien': 'Traumatismo craneal',
    'Tir à la tête': 'Disparo en la cabeza',
    'Impact sur plaque': 'Impacto en la placa',
    'Éraflure au flanc': 'Rasguño en el costado',
    'Côtes fracturées': 'Costillas fracturadas',
    'Pneumothorax': 'Neumotórax',
    'Hémorragie interne': 'Hemorragia interna',
    'Tir vital': 'Disparo vital',
    'Balle dans l\'avant-bras': 'Bala en el antebrazo',
    'Fracture de l\'avant-bras': 'Fractura de antebrazo',
    'Artère brachiale': 'Arteria braquial',
    'Balle au mollet': 'Bala en la pantorrilla',
    'Fracture du fémur': 'Fractura de fémur',
    'Fracture de la rotule': 'Fractura de rótula',
    'Artère fémorale': 'Arteria femoral',
    'DCD (Blast)': 'MUERTO (onda expansiva)',
    'Plaie Soufflante': 'Herida torácica aspirante',
    'Hémorragie Massive': 'Hemorragia masiva',
    'Saignement Grave': 'Sangrado grave',
    'Fracture Ouverte': 'Fractura abierta',
    'Éraflure (Éclat)': 'Rasguño (metralla)',
    'Souffle (Blast)': 'Onda expansiva',
    'Éraflure au visage': 'Rasguño en la cara',
    'Éclats au bras': 'Metralla en el brazo',
    'Criblage d\'éclats': 'Acribillado por metralla',
    'Souffle d\'explosion': 'Onda de explosión'
},
soin: {
    'Respawn direct': 'Reaparición directa',
    '30s massage + Poche': '30 s de masaje + Bolsa de sangre',
    'Garrot + Poche': 'Torniquete + Bolsa de sangre',
    'Bandage + Poche': 'Vendaje + Bolsa de sangre',
    'Attelle': 'Férula',
    'Bandage': 'Vendaje',
    'Si Protégé : Sonné (Médic aide à relever). Sinon : Bandage ([MEMBRE_ALEATOIRE])': 'Si está protegido: Aturdido (el médico ayuda a levantarse). Si no: Vendaje ([MEMBRE_ALEATOIRE])',
    'Bandage + Massage + Épi + Poche': 'Vendaje + Masaje + Adrenalina + Bolsa de sangre',
    'Pnsmt 3 côtés + Morphine + Poche': 'Apósito 3 lados + Morfina + Bolsa de sangre',
    'Garrot + Bandage + Morphine + Poche': 'Torniquete + Vendaje + Morfina + Bolsa de sangre',
    'Bandage + Morphine': 'Vendaje + Morfina',
    'Bandage + Attelle + Morphine': 'Vendaje + Férula + Morfina',
    'Tête — protégé : rien, sinon Éraflure (Bandage). Torse — protégé : Hématome (Morphine), sinon Bandage': 'Cabeza — protegida: nada, si no Rasguño (Vendaje). Torso — protegido: Hematoma (Morfina), si no Vendaje',
    'Protégé : Sonné (le médic aide à relever). Sinon : DCD': 'Protegido: Aturdido (el médico ayuda a levantarse). Si no: Muerto',
    'Repos 2 minutes': 'Reposo de 2 minutos',
    'Bandage + Épinéphrine + Morphine': 'Vendaje + Adrenalina + Morfina',
    'Repos 1 minute': 'Reposo de 1 minuto',
    'Bandage compressif + Morphine': 'Vendaje compresivo + Morfina',
    'Pansement 3 côtés + Morphine': 'Apósito de 3 lados + Morfina',
    'Bandage + Poche de transfusion + Épinéphrine': 'Vendaje + Bolsa de sangre + Adrenalina',
    'Attelle + Bandage': 'Férula + Vendaje',
    'Garrot + Bandage + Poche de transfusion': 'Torniquete + Vendaje + Bolsa de sangre',
    'Attelle + Bandage + Morphine': 'Férula + Vendaje + Morfina',
    'Attelle + Morphine': 'Férula + Morfina',
    'Garrot + Poche de transfusion + Épinéphrine': 'Torniquete + Bolsa de sangre + Adrenalina',
    'Bandage + 30s Massage + Épi + Poche': 'Vendaje + 30 s de masaje + Adrenalina + Bolsa de sangre',
    '2x Bandages + Morphine': '2x Vendajes + Morfina',
    'Garrot + Pansement 3 côtés + Poche de transfusion + Épinéphrine': 'Torniquete + Apósito de 3 lados + Bolsa de sangre + Adrenalina',
    'Casque porté : aucune blessure.\nSinon : Éraflure → Bandage': 'Casco puesto: ninguna herida.\nSi no: Rasguño → Vendaje',
    'Gilet porté : Hématome → Morphine.\nSinon : Bandage': 'Chaleco puesto: Hematoma → Morfina.\nSi no: Vendaje',
    'Casque porté : Sonné → le médic aide à relever.\nSinon : DCD': 'Casco puesto: Aturdido → el médico ayuda a levantarse.\nSi no: Muerto',
    'Gilet porté : Sonné → le médic aide à relever.\nSinon : DCD': 'Chaleco puesto: Aturdido → el médico ayuda a levantarse.\nSi no: Muerto'
},
bilan: {
    'Impact direct sur le casque lourd.': 'Impacto directo en el casco pesado.',
    'Plaie ouverte et profonde au front.': 'Herida abierta y profunda en la frente.',
    'Traumatisme crânien sévère.': 'Traumatismo craneal grave.',
    'Tir direct à la tête (sans port du casque).': 'Disparo directo en la cabeza (sin casco).',
    'Impact encaissé par la plaque balistique du porte-plaques.': 'Impacto absorbido por la placa balística del portaplacas.',
    'Éraflure sur le flanc, hors de la zone couverte par les plaques balistiques.': 'Rasguño en el costado, fuera de la zona cubierta por las placas balísticas.',
    'Fracture de plusieurs côtes par impact lourd.': 'Fractura de varias costillas por un impacto fuerte.',
    'Pneumothorax suite à une balle perforante latérale.': 'Neumotórax tras una bala perforante lateral.',
    'Blessure perforante à l\'abdomen causant une importante hémorragie interne.': 'Herida perforante en el abdomen que provoca una fuerte hemorragia interna.',
    'Tir direct au niveau du cœur ou de la colonne vertébrale (sans port de plaques balistiques).': 'Disparo directo al corazón o a la columna vertebral (sin placas balísticas).',
    'Balle logée dans les tissus mous de l\'avant-bras.': 'Bala alojada en los tejidos blandos del antebrazo.',
    'Fracture de l\'os de l\'avant-bras (radius / cubitus).': 'Fractura del hueso del antebrazo (radio / cúbito).',
    'Sectionnement de l\'artère brachiale.': 'Sección de la arteria braquial.',
    'Balle logée dans le muscle du mollet.': 'Bala alojada en el músculo de la pantorrilla.',
    'Fracture du fémur.': 'Fractura de fémur.',
    'Fracture de la rotule du genou.': 'Fractura de la rótula de la rodilla.',
    'Sectionnement de l\'artère fémorale.': 'Sección de la arteria femoral.',
    'Éraflure superficielle due à un éclat sur la joue ou le lobe de l\'oreille.': 'Rasguño superficial por metralla en la mejilla o el lóbulo de la oreja.',
    'Multiples plaies par éclats de grenade sur le bras.': 'Múltiples heridas por metralla de granada en el brazo.',
    'Criblage d\'éclats de shrapnel sur l\'ensemble des deux jambes.': 'Ambas piernas acribilladas por metralla.',
    'Traumatisme contondant lourd au torse et sectionnement artériel à un bras suite à une explosion à proximité.': 'Traumatismo contundente grave en el torso y sección arterial en un brazo tras una explosión cercana.'
}
};
