/* BSE MEDICAL SYSTEM — DEUTSCH
   Les tables zone/grav/mat/membre/titre/soin/bilan sont indexees par le
   texte FRANCAIS d'origine, qui reste la cle interne des cartes. */
window.BSE_I18N.de = {
ui: {
    'hdr.multijoueur': 'Mehrspieler',
    'hdr.quitter': 'Spiel verlassen',
    'hdr.sortir': 'Verlassen',
    'hdr.paquets': 'Meine Decks',
    'hdr.reglages': 'Einstellungen',
    'hdr.bseLien': 'Bravo Sierra Events — Website öffnen',
    'hdr.bseAria': 'Website von Bravo Sierra Events öffnen',
    'statut.solo': 'Solo',
    'statut.organisateur': 'Organisator',
    'statut.coadmin': 'Co-Admin',
    'statut.reconnexion': '{nom} · Verbindung zum Spiel wird wiederhergestellt…',
    'paquet.balistique': 'Ballistik',
    'paquet.explosion': 'Explosion',

    'jeu.titre': 'Medizinische Beurteilung',
    'jeu.sous': 'Tippen, um die Beurteilung zu starten',
    'jeu.paquetActif': 'Aktives Deck',
    'jeu.chargement': 'Lädt...',
    'jeu.cartes': '{n} Karten',

    'march.titre': 'MARCH-Beurteilung',
    'march.m': 'Massive Blutung',
    'march.a': 'Atemwege',
    'march.r': 'Atmung',
    'march.c': 'Kreislauf',
    'march.h': 'Kopf / Unterkühlung',
    'march.analyse': 'Beurteilung läuft…',

    'sil.titre': 'Welcher Bereich wurde getroffen?',
    'sil.sous': 'Tippen Sie auf den getroffenen Körperteil',
    'sil.miroir': '(Spiegelansicht: sein rechter Arm ist links von Ihnen)',

    'fiche.mort': 'Im Einsatz gefallen',
    'fiche.mortSous': 'Zeit abgelaufen — tödliche Blutung',
    'fiche.fermer': 'Akte schließen',
    'fiche.label': 'Triage-Blatt',
    'fiche.zone': 'Getroffener Bereich',
    'fiche.bilan': 'Befund',
    'fiche.protocole': 'Behandlungsprotokoll',
    'fiche.hemorragie': 'Aktive Blutung — lebensbedrohlich',
    'fiche.nouveau': 'Neue Beurteilung',
    'fiche.soigner': 'Behandlung erfolgt (retten)',
    'fiche.stabilise': 'PATIENT STABILISIERT!',
    'fiche.protPortee': 'Ballistischer Schutz getragen: {reponse}',
    'fiche.avecProtection': ' mit getragenem Schutz',

    'btn.annuler': 'Abbrechen',
    'btn.valider': 'Bestätigen',
    'btn.fermer': 'Schließen',
    'btn.retour': 'Zurück',
    'btn.copier': 'Kopieren',
    'btn.ouvrir': 'Öffnen',
    'btn.oui': 'Ja',
    'btn.non': 'Nein',

    'qg.titre': 'HQ',
    'qg.partie': 'Spiel',
    'qg.enLigne': 'Online',
    'qg.ongletInvitation': 'Einladung',
    'qg.ongletJoueurs': 'Spieler',
    'qg.ongletEquipes': 'Teams',
    'qg.ongletEditeur': 'Editor',
    'qg.ongletPaquets': 'Decks',
    'qg.ongletLogs': 'Logs',
    'qg.codeAide': 'Spielcode — den Spielern vorlesen',
    'qg.lienAide': 'Verbindungslink (teilen oder QR)',
    'qg.qrGeneration': 'Wird erstellt...',
    'qg.qrAide': 'Die Spieler scannen den QR-Code oder geben den Spielnamen im Beitreten-Menü ein.',
    'qg.joueurs': 'SPIELER',
    'qg.equipes': 'TEAMS DIESES SPIELS',
    'qg.nomEquipePh': 'Teamname',
    'qg.couleurEquipePh': '#Hex-Farbe',
    'qg.ajouterEquipe': '+ TEAM',
    'qg.editeur': 'DECK-EDITOR',
    'qg.editeurAide': 'Stellen Sie Mengen, Material und Todesrisiko für alle Ihre Decks ein, bevor Sie sie verteilen.',
    'qg.paquetsAttribues': 'ZUGEWIESENE DECKS',
    'qg.paquetsAide1': 'Wählen Sie, woraus jeder Spieler zieht: Klassisch, Fortgeschritten, Extrem, Explosion oder eines Ihrer eigenen Decks. Ein zugewiesenes Deck <b>ersetzt</b> den Spielmodus beim Empfänger — er sieht nur dieses, mit den im Editor eingestellten Mengen.',
    'qg.paquetsAide2': 'Ein Spieler ohne Zuweisung spielt den im Editor festgelegten <b>aktuellen Modus</b>.',
    'qg.toutLeMonde': 'Alle',
    'qg.uneEquipe': 'Nur ein Team',
    'qg.unJoueur': 'Nur ein Spieler',
    'qg.ajouterPaquet': 'Dieses Deck zuweisen',
    'qg.journal': 'LIVE-PROTOKOLL',
    'qg.journalAide': 'Die Ereignisse eines Spielers erscheinen in seiner Teamfarbe.',
    'qg.telechargerLogs': 'Logs herunterladen (.txt)',
    'qg.effacerAffichage': 'Anzeige leeren',
    'qg.cloturer': 'Spiel beenden (alle Spieler trennen)',
    'qg.retourSession': 'Zurück zum Start (Sitzung behalten)',

    'reg.titre': 'Systemeinstellungen',
    'reg.profil': 'Mehrspieler-Profil',
    'reg.pseudo': 'Ihr Spielername',
    'reg.pseudoPh': 'z. B. Doc',
    'reg.mode': 'Spielmodus',
    'reg.hardcore': 'Hardcore-Option',
    'reg.activerMort': 'Todesrisiko aktivieren',
    'reg.proba': 'Wahrscheinlichkeit',
    'reg.probaSous': 'bei einer infrage kommenden Verletzung',
    'reg.delaiMin': 'Mindestzeit',
    'reg.delaiMinSous': 'bis zum Tod',
    'reg.delaiMax': 'Höchstzeit',
    'reg.etendreGraves': 'Auf schwere Verletzungen ausweiten',
    'reg.explosion': 'Explosion',
    'reg.activerExplosion': 'Explosionskarten aktivieren',
    'reg.materiel': 'Benötigtes Material',
    'reg.cartesActives': 'Aktive Karten',
    'reg.catalogue': 'Katalog',
    'reg.oeilAide': 'Das Auge in jeder Zeile öffnet den Modus-Katalog bei der betreffenden Karte.',
    'reg.aide': 'Hilfe',
    'reg.aideTexte': 'Die vollständige Anleitung, zum Lesen beim Briefing. Einmal geöffnet, bleibt sie offline verfügbar.',
    'reg.guide': 'Bedienungsanleitung (PDF)',

    'lang.titre': 'Sprache',
    'lang.choisir': 'Sprache wählen',

    'bld.titre': 'Meine Decks',
    'bld.sous': 'Erstellen Sie eigene Kartendecks und zeigen Sie sie auf dem Startbildschirm.',
    'bld.creer': '+ Deck erstellen',
    'bld.importer': 'Deck importieren',
    'bld.edition': 'Deck bearbeiten',
    'bld.nom': 'Deckname',
    'bld.nomPh': 'z. B. Chemische Verletzungen',
    'bld.afficherAccueil': 'Auf dem Startbildschirm zeigen',
    'bld.modeExtreme': 'Extrem-Modus',
    'bld.modeExtremeSous': '(Silhouette: getroffener Bereich + Schutz)',
    'bld.icone': 'Symbol der Schaltfläche',
    'bld.iconeAide': 'Es kennzeichnet das Deck auf dem Startbildschirm und bei den Spielern, denen Sie es zuweisen.',
    'bld.cartes': 'Karten',
    'bld.ajouterCarte': '+ Karte hinzufügen',
    'bld.enregistrer': 'Speichern',
    'bld.supprimerPaquet': 'Deck löschen',

    'ce.titreEcran': 'Karte',
    'ce.gravite': 'Schweregrad',
    'ce.titre': 'Titel',
    'ce.titrePh': 'z. B. Fraktur',
    'ce.zone': 'Getroffener Bereich',
    'ce.zonePh': 'z. B. Arm',
    'ce.protocole': 'Protokoll / Wirkung',
    'ce.protocolePh': 'z. B. Schiene + Morphin',
    'ce.matos': 'Benötigtes Material',
    'ce.matosAide': 'Tippen Sie auf einen Chip, um ihn auszuwählen. Hier hinzugefügtes Material wird nur in diesem Deck angeboten (✕ zum Entfernen).',
    'ce.nouveauMatosPh': 'Neues Material (z. B. Anti-Rad)',
    'ce.valider': 'Karte bestätigen',

    'mod.apercu': 'Vorschau',
    'multi.titre': 'Mehrspieler-Menü',
    'multi.nomPartie': 'Spielname (Host)',
    'multi.nomPartiePh': 'z. B. Übung Alpha',
    'multi.pseudoHote': 'Name des Hosts',
    'multi.pseudoHotePh': 'z. B. Orga',
    'multi.liaison': 'Verbindung zwischen Geräten',
    'multi.firebase': 'Firebase-Server (empfohlen)',
    'multi.peer': 'Peer-to-Peer (alt)',
    'multi.aideFirebase': 'Läuft über den Server: funktioniert über verschiedene Netze hinweg (4G / WLAN), und Sie können Ihre Seite schließen, ohne das Spiel zu beenden.',
    'multi.aidePeer': 'Direkte Verbindung zwischen Geräten. Braucht oft ein TURN-Relais, und Ihre Seite muss offen bleiben.',
    'multi.creer': 'Spiel erstellen (Host)',
    'multi.rejoindre': 'Einem Spiel beitreten',
    'multi.scanner': 'QR-Code scannen',
    'multi.codePh': 'Spielname oder Link',
    'multi.connexion': 'Verbinden',
    'multi.testerReseau': 'Netzwerk testen',
    'multi.turn': 'Netzwerk-Relais (TURN) — optional',
    'multi.turnAide': 'Nötig, wenn der Test ❌ TURN anzeigt und Ihre Spieler in anderen Netzen sind (4G, anderes WLAN). Legen Sie ein kostenloses Konto auf <b>metered.ca</b> an (50 GB/Monat), fügen Sie einen „TURN server“ hinzu und fügen Sie dessen Zugangsdaten hier ein. Sie werden über den Einladungslink / QR-Code automatisch an die Spieler weitergegeben.',
    'multi.turnUrlPh': 'URL (z. B. turn:standard.relay.metered.ca:443)',
    'multi.turnUserPh': 'Benutzername',
    'multi.turnPassPh': 'Passwort / Credential',
    'multi.turnSave': 'Relais speichern',
    'multi.statut': 'Verbindung...',

    'join.titre': 'Dem Spiel beitreten',
    'join.etabli': 'Verbindung hergestellt.',
    'join.pseudo': 'Ihr Spielername',
    'join.equipe': 'Ihr Team',

    'prot.question': 'Ballistischer Schutz getragen?',
    'prot.casque': 'Ballistischer Helm getragen?',
    'prot.gilet': 'Schutzweste getragen?',

    'share.titre': 'Deck teilen',

    'leave.titre': 'Spiel verlassen?',
    'leave.texte': 'Sie verlassen die Mehrspieler-Sitzung und kehren zum Hauptmenü zurück.',
    'leave.oui': 'Ja, verlassen',

    'mode.classique': 'Klassisch',
    'mode.avance': 'Fortgeschritten',
    'mode.extreme': 'Extrem',
    'mode.explosion': 'Explosion',
    'mode.perso': 'Eigenes',
    'mode.plusExplosion': ' + Explosion',
    'reg.modeClassique': 'KLASSISCH',
    'reg.modeAvance': 'FORTGESCHRITTEN',
    'reg.modeExtreme': 'EXTREM (Silhouette)',
    'reg.custom': '{nom} (Eigenes)',
    'reg.aucunMateriel': 'Für diesen Modus oder diese Auswahl ist kein Material nötig.',
    'reg.voirCarte': 'Karte ansehen',
    'reg.packExplosion': 'Explosions-Pack',
    'reg.verrouille': 'Einstellungen vom Host gesperrt',

    'cat.titre': 'Katalog — {mode}',
    'cat.sectionMode': 'Modus',
    'cat.sectionPerso': 'Eigenes Deck',
    'cat.sectionExplosion': 'Explosion',
    'cat.protPortee': 'Schutz getragen',
    'cat.sansProt': 'ohne Schutz',
    'cat.matos': 'Material:',
    'cat.aucuneCarte': 'Keine Karten für diesen Modus.',
    'carte.membreAleatoire': 'zufällige Gliedmaße',

    'btn.modifier': 'Bearbeiten',
    'btn.partager': 'Teilen',
    'btn.supprimer': 'Löschen',

    'bld.nouveauPaquet': 'Neues Deck',
    'bld.sansNom': 'Deck ohne Namen',
    'bld.sansTitre': 'Ohne Titel',
    'bld.masque': 'Ausgeblendet',
    'bld.surAccueil': 'Auf dem Startbildschirm',
    'bld.aucunPaquet': 'Noch kein eigenes Deck.',
    'bld.aucunPaquetAide': 'Tippen Sie auf „+ DECK ERSTELLEN“, um zu beginnen.',
    'bld.aucuneCarte': 'Keine Karten in diesem Deck.',
    'bld.aucuneCarteAide': 'Tippen Sie auf „+ KARTE HINZUFÜGEN“.',
    'bld.nMateriel': '{n} Material',
    'bld.enPartieTitre': 'Spiel läuft.',
    'bld.enPartieTexte': 'Sie spielen die vom Organisator zugewiesenen Decks. Ihre eigenen Decks sind beiseitegelegt und werden Ihnen zurückgegeben, sobald Sie das Spiel verlassen.',
    'bld.bloqueEnPartie': 'Während eines Spiels nicht möglich: die Konfiguration kommt vom Organisator und Ihr Deck würde gelöscht.\n\nVerlassen Sie das Spiel, um Ihre eigenen Decks zurückzubekommen und zu bearbeiten.',
    'bld.confirmSupprCarte': 'Karte „{nom}“ löschen?',
    'bld.confirmSupprPaquet': 'Deck „{nom}“ mit allen Karten löschen?',
    'ce.donnezTitre': 'Geben Sie der Karte einen Titel.',
    'ce.confirmRetirerMatos': '„{nom}“ aus diesem Deck entfernen? Es wird auch aus den Karten entfernt, die es verwenden.',

    'share.exportTitre': '„{nom}“ teilen',
    'share.exportAide': 'Senden Sie diesen Code an einen anderen Spieler (SMS, WhatsApp, E-Mail...). Er importiert ihn über „DECK IMPORTIEREN“ in Meine Decks.',
    'share.copierCode': 'CODE KOPIEREN',
    'share.importAide': 'Fügen Sie hier den erhaltenen Teilen-Code ein (er beginnt mit TMDECK1).',
    'share.importer': 'IMPORTIEREN',
    'share.codeCopie': 'Code kopiert!',
    'share.codeInvalide': 'Ungültiger oder unvollständiger Code. Prüfen Sie, ob er vollständig kopiert wurde.',
    'share.paquetImporte': 'Importiertes Deck',
    'share.importeOk': 'Deck „{nom}“ importiert ({n} Karten)!',

    'icone.cartes': 'Karten',
    'icone.blesse': 'Verwundeter',
    'icone.souffle': 'Druckwelle',
    'icone.balle': 'Kugel',
    'icone.reticule': 'Fadenkreuz',
    'icone.lame': 'Klinge',
    'icone.grenade': 'Granate',
    'icone.bombe': 'Bombe',
    'icone.explosion': 'Explosion',
    'icone.feu': 'Feuer',
    'icone.decharge': 'Entladung',
    'icone.froid': 'Kälte',
    'icone.biohazard': 'Biogefährdung',
    'icone.radiation': 'Strahlung',
    'icone.toxique': 'Giftig',
    'icone.masqueGaz': 'Gasmaske',
    'icone.zombie': 'Zombie',
    'icone.creature': 'Kreatur',
    'icone.robot': 'Roboter',
    'icone.crane': 'Totenkopf',
    'icone.seringue': 'Spritze',
    'icone.cachets': 'Tabletten',
    'icone.perfusion': 'Infusion',
    'icone.pouls': 'Puls',
    'icone.fracture': 'Fraktur',
    'icone.trousse': 'Sanitätstasche',
    'icone.protection': 'Schutz',

    'qg.ligneMode': 'Modus: {nom}',
    'qg.lignePerso': 'Eigenes: {nom}',
    'qg.joue': 'IM SPIEL',
    'qg.minEquipes': '(mind. 2 Teams)',
    'qg.horsLigne': 'offline',
    'qg.reviendra': 'Kommt automatisch zurück…',
    'qg.retirer': 'Entfernen',
    'qg.admin': 'Admin',
    'qg.kick': 'Kick',
    'qg.retirerPaquet': 'Dieses Deck entfernen',
    'qg.cibleEquipe': 'Team {nom}',
    'qg.cibleJoueur': 'Spieler {nom}',
    'qg.aucunPaquetDistribue': 'Kein Deck zugewiesen.',
    'qg.aucunPaquetDistribueAide': 'Die Spieler haben nur den Ballistik-Zug.',
    'qg.paquetVide': 'Dieses Deck ist mit der aktuellen Konfiguration leer.',
    'qg.dejaAttribueCible': '„{nom}“ ist diesem Ziel bereits zugewiesen.',
    'qg.dejaAttribueTous': '„{nom}“ ist bereits allen zugewiesen: es einem Team oder Spieler erneut zu geben, bringt nichts.',
    'qg.indiquezNomEquipe': 'Geben Sie einen Teamnamen an.',
    'qg.deuxEquipesMini': 'Es sind mindestens zwei Teams nötig.',
    'qg.choisirEquipe': 'Wählen Sie ein Team.',
    'qg.choisirJoueur': 'Wählen Sie einen (verbundenen) Spieler.',
    'qg.aucunLog': 'Keine Logs zum Herunterladen.',
    'qg.logEntete': 'Spielprotokoll',
    'qg.logExporte': 'Exportiert am',
    'qg.confirmCloture': 'Spiel beenden? Alle Spieler werden benachrichtigt und getrennt.',
    'qg.confirmClotureTous': 'Spiel für alle beenden?',
    'qg.qrIndisponible': 'QR nicht verfügbar.',
    'qg.qrIndisponibleAide': 'Teilen Sie den Link oder den Spielnamen.',
    'qg.qrAlt': 'Einladungs-QR-Code',

    'log.partieOuverte': 'Spiel eröffnet: {code}',
    'log.aRejoint': '{nom} ist beigetreten',
    'log.sEstReconnecte': '{nom} hat sich wieder verbunden',
    'log.quitteLaPartie': '{nom} verlässt das Spiel',
    'log.joueurDeconnecte': '{nom} getrennt (wartet auf Wiederverbindung)',
    'log.pseudoDejaPris': 'Name „{demande}“ bereits vergeben: dieser Spieler wird „{retenu}“',
    'log.sessionDemarree': 'Host-Sitzung gestartet: {code}',
    'log.sessionReprise': 'Sitzung fortgesetzt: {code}',
    'log.configModifiee': '{nom} (Co-Admin) hat die Konfiguration geändert',
    'log.ajoutRefuse': 'Zuweisung abgelehnt ({nom}): {raison}',
    'log.tirage': '{nom} · Zug: {carte} [{gravite}] · {source}',
    'log.coadmin': '{nom} · Co-Admin: {valeur}',
    'log.retireDeLaPartie': 'Aus dem Spiel entfernt: {nom}',
    'log.partieCloturee': 'Spiel beendet.',
    'log.partieClotureePar': 'Spiel beendet von {nom} (Co-Admin).',
    'qg.logEquipeAjoutee': 'Team hinzugefügt: {nom}',
    'qg.logEquipeSupprimee': 'Team gelöscht, Spieler neu zugeordnet.',
    'qg.logPaquetDistribue': 'Deck zugewiesen: {nom} → {cible}',
    'qg.logRemplaceParTous': '{nom}: {n} gezielte Zuweisung(en) durch „alle“ ersetzt',

    'multi.joueur': 'Spieler',
    'multi.orga': 'Orga',
    'multi.ouverture': 'Spiel wird eröffnet...',
    'multi.ouvertureImpossible': 'Eröffnen nicht möglich.',
    'multi.creation': 'Spiel wird erstellt...',
    'multi.reprise': 'Spiel wird fortgesetzt...',
    'multi.recherche': 'Spiel wird gesucht...',
    'multi.connexionReseau': 'Netzwerkverbindung läuft...',
    'multi.recuperation': 'Daten werden abgerufen...',
    'join.partieNommee': 'Spiel „{nom}“',

    'net.testEnCours': 'Test läuft (~15 s)...',
    'net.ligneSignalisation': 'Vermittlung (PeerJS-Server)',
    'net.ligneStun': 'STUN — direkte Verbindung möglich',
    'net.ligneTurn': 'TURN — Relais, wenn direkt blockiert ist',
    'net.aucunRelais': '(kein Relais eingerichtet)',
    'net.relaisEnregistre': 'Relais gespeichert. Es wird für die nächsten Verbindungen genutzt und über den Link / QR-Code an die Spieler weitergegeben.',
    'net.relaisEfface': 'Relais gelöscht.',
    'net.verdictOk': 'Alles funktioniert: die Verbindung sollte halten, auch zwischen verschiedenen Netzen (4G ↔ Router).',
    'net.verdictSansTurn': 'Kein TURN-Relais: die Verbindung kann zwischen verschiedenen Netzen scheitern oder wenn der Router seine Geräte isoliert. Richten Sie unten ein Relais ein (Netzwerk-Relais); es wird über den QR-Code an die Spieler weitergegeben.',
    'net.verdictStunBloque': 'STUN ist blockiert, obwohl das Internet funktioniert: fast immer blockiert der BROWSER das UDP von WebRTC.<br>• <b>Opera / Opera GX</b>: schalten Sie das eingebaute VPN aus, suchen Sie dann in den Einstellungen nach „WebRTC“ und wählen Sie „UDP ohne Proxy verwenden“.<br>• Sonst: VPN, Antivirus oder Firewall. Testen Sie zur Bestätigung in Chrome oder Edge.<br>• Ein eingerichtetes TURN-Relais läuft auch über TCP 443 und umgeht diese Sperre oft.',
    'net.verdictWebrtcOff': 'WebRTC ist in diesem Browser vollständig deaktiviert (kein Netzwerkkandidat). Prüfen Sie die Datenschutzeinstellungen des Browsers oder versuchen Sie einen anderen.',
    'net.verdictPasDeSignalisation': 'Vermittlungsserver nicht erreichbar: prüfen Sie den Internetzugang.',

    'msg.paquetIndisponible': 'Dieses Deck ist nicht mehr verfügbar.',
    'msg.aucunPaquetMode': 'Kein Kartendeck für diesen Modus. Prüfen Sie die Einstellungen oder das eigene Deck.',
    'msg.aucuneCarteMateriel': 'Keine Karte verfügbar. Prüfen Sie, ob Sie das benötigte Material haben (Einstellungen).',
    'msg.aucuneCarteZone': 'Keine Karte für diesen Bereich verfügbar{etat}.\n\nPrüfen Sie die Mengen und das verfügbare Material in den Einstellungen.',
    'msg.avecProtection': ' mit getragenem Schutz',
    'msg.sansProtection': ' ohne Schutz',
    'msg.lienCopie': 'Einladungslink kopiert.',
    'msg.codeCopie': 'Spielcode kopiert:',
    'msg.partiePasOuverte': 'Das Spiel ist noch nicht eröffnet.',
    'msg.scannerIndisponible': 'QR-Scanner nicht verfügbar (Bibliothek nicht geladen — prüfen Sie die Internetverbindung).',
    'msg.peerIndisponible': 'Mehrspieler nicht verfügbar (PeerJS-Bibliothek nicht geladen — prüfen Sie die Internetverbindung).',
    'msg.firebaseIndisponible': 'Firebase-Mehrspieler ist nicht verfügbar (Bibliothek fehlt).',
    'msg.droitsOrga': 'Änderung abgelehnt: Sie haben keine Organisatorrechte für dieses Spiel.',
    'msg.devenuCoOrga': 'Sie sind jetzt Co-Organisator: das Spiel-HQ erreichen Sie über die Mehrspieler-Schaltfläche oben rechts.',
    'msg.gradeRetire': 'Admin-Rechte entzogen.',
    'msg.retireDeLaPartie': 'Sie wurden aus dem Spiel entfernt.',
    'msg.exclu': 'Sie wurden aus dem Spiel geworfen.',
    'msg.orgaACloture': 'Der Organisator hat das Spiel beendet.',
    'msg.partieTerminee': 'Das Spiel ist vorbei.',
    'msg.nomPartiePris': 'Ein Spiel trägt diesen Namen bereits und gehört jemand anderem. Wählen Sie einen anderen Namen.',
    'msg.nomPartieDejaPris': 'Dieser Spielname wird bereits verwendet (oder die alte Sitzung ist noch nicht abgelaufen). Warten Sie eine Minute oder ändern Sie den Namen.',
    'msg.partieIntrouvable': 'Spiel nicht gefunden. Prüfen Sie den Namen beim Organisator.',
    'msg.partieIntrouvableHote': 'Das Spiel ist nicht auffindbar. Prüfen Sie, ob der Host seine Webseite geschlossen oder das Spiel abgebrochen hat.',
    'msg.partieCloturee': 'Dieses Spiel ist beendet.',
    'msg.erreurPeer': 'PeerJS-Fehler',
    'msg.repriseImpossible': 'Das Spiel „{nom}“ kann derzeit nicht fortgesetzt werden ({raison}). Ein neuer Versuch folgt, sobald Sie zur Seite zurückkehren, oder erstellen Sie das Spiel mit demselben Namen neu, um Ihre Spieler wiederzufinden.',
    'msg.dejaHote': 'Sie hosten auf diesem Gerät bereits ein Spiel. Verlassen Sie das alte Spiel über den Host-Bildschirm, um einem anderen als Spieler beizutreten.',
    'msg.indiquezNomPartie': 'Geben Sie den Spielnamen an oder scannen Sie den QR-Code.',
    'msg.indiquezPseudo': 'Geben Sie einen Spielernamen an: so sieht Sie der Organisator im Spiel.',
    'msg.delaiDepasse': 'Zeitüberschreitung: die Verbindung zum Host kam nicht zustande. Prüfen Sie, ob seine Seite offen ist, und starten Sie dann „Netzwerk testen“ im Mehrspieler-Menü: schlägt TURN fehl, muss der Host ein Relais einrichten („Netzwerk-Relais“) — es wird über seinen QR-Code automatisch weitergegeben.',
    'msg.hoteIntrouvable': 'Verbindung fehlgeschlagen: Host nicht gefunden oder Netzwerk instabil.',
    'msg.connexionImpossible': 'Verbindung fehlgeschlagen.',
    'msg.connexionPerdue': 'Verbindung verloren. Versuchen Sie erneut, dem Spiel beizutreten.',
    'msg.connexionPerdueHote': 'Verbindung zum Host verloren.',
    'msg.reconnexionImpossible': 'Wiederverbinden nicht möglich: das Spiel scheint beendet oder der Host nicht erreichbar.',
    'msg.connecte': 'Mit dem Spiel verbunden!',
    'msg.pseudoRemplace': 'Dieser Name war im Spiel schon vergeben. Sie erscheinen als: {nom}',
    'msg.changementEquipe': 'Teamwechsel'
},
zone: {
    'Tête ou Torse': 'Kopf oder Rumpf',
    'Torse': 'Rumpf',
    'Tête': 'Kopf',
    'Bras': 'Arm',
    'Jambe': 'Bein',
    'Jambes': 'Beine',
    'Torse et bras': 'Rumpf und Arm'
},
grav: {
    'DÉCÈS': 'TOD',
    'Critique': 'Kritisch',
    'Grave': 'Schwer',
    'Légère': 'Leicht',
    'Spécial': 'Spezial'
},
membre: {
    'Bras Gauche': 'Linker Arm',
    'Bras Droit': 'Rechter Arm',
    'Jambe Gauche': 'Linkes Bein',
    'Jambe Droite': 'Rechtes Bein'
},
mat: {
    'Garrot': 'Tourniquet',
    'Bandage': 'Verband',
    'Poche de transfusion': 'Blutbeutel',
    'Attelle': 'Schiene',
    'Morphine': 'Morphin',
    'Épinéphrine': 'Adrenalin',
    'Pansement 3 côtés': 'Dreiseitiger Verband'
},
titre: {
    'DCD': 'GEFALLEN',
    'Inconscient': 'Bewusstlos',
    'Hémorragie': 'Blutung',
    'Saignement': 'Blutverlust',
    'Fracture': 'Fraktur',
    'Éraflure': 'Schürfwunde',
    'Choc Casque': 'Helmtreffer',
    'Choc Gilet': 'Westentreffer',
    'Plaie soufflante': 'Offener Pneumothorax',
    'Saignement grave': 'Starker Blutverlust',
    'Prot. Balistique': 'Ballistischer Schutz',
    'Choc Balistique': 'Ballistischer Schock',
    'Impact sur casque': 'Treffer auf den Helm',
    'Plaie au front': 'Wunde an der Stirn',
    'Traumatisme crânien': 'Schädel-Hirn-Trauma',
    'Tir à la tête': 'Kopfschuss',
    'Impact sur plaque': 'Treffer auf die Platte',
    'Éraflure au flanc': 'Schürfwunde an der Flanke',
    'Côtes fracturées': 'Rippenbrüche',
    'Pneumothorax': 'Pneumothorax',
    'Hémorragie interne': 'Innere Blutung',
    'Tir vital': 'Tödlicher Schuss',
    'Balle dans l\'avant-bras': 'Kugel im Unterarm',
    'Fracture de l\'avant-bras': 'Unterarmfraktur',
    'Artère brachiale': 'Oberarmarterie',
    'Balle au mollet': 'Kugel in der Wade',
    'Fracture du fémur': 'Oberschenkelfraktur',
    'Fracture de la rotule': 'Kniescheibenfraktur',
    'Artère fémorale': 'Oberschenkelarterie',
    'DCD (Blast)': 'GEFALLEN (Druckwelle)',
    'Plaie Soufflante': 'Offener Pneumothorax',
    'Hémorragie Massive': 'Massive Blutung',
    'Saignement Grave': 'Starker Blutverlust',
    'Fracture Ouverte': 'Offene Fraktur',
    'Éraflure (Éclat)': 'Schürfwunde (Splitter)',
    'Souffle (Blast)': 'Druckwelle',
    'Éraflure au visage': 'Schürfwunde im Gesicht',
    'Éclats au bras': 'Splitter im Arm',
    'Criblage d\'éclats': 'Von Splittern durchsiebt',
    'Souffle d\'explosion': 'Explosionsdruckwelle'
},
soin: {
    'Respawn direct': 'Direkt zum Respawn',
    '30s massage + Poche': '30s Herzdruckmassage + Blutbeutel',
    'Garrot + Poche': 'Tourniquet + Blutbeutel',
    'Bandage + Poche': 'Verband + Blutbeutel',
    'Attelle': 'Schiene',
    'Bandage': 'Verband',
    'Si Protégé : Sonné (Médic aide à relever). Sinon : Bandage ([MEMBRE_ALEATOIRE])': 'Wenn geschützt: Benommen (Sanitäter hilft beim Aufstehen). Sonst: Verband ([MEMBRE_ALEATOIRE])',
    'Bandage + Massage + Épi + Poche': 'Verband + Herzdruckmassage + Adrenalin + Blutbeutel',
    'Pnsmt 3 côtés + Morphine + Poche': 'Dreiseitiger Verband + Morphin + Blutbeutel',
    'Garrot + Bandage + Morphine + Poche': 'Tourniquet + Verband + Morphin + Blutbeutel',
    'Bandage + Morphine': 'Verband + Morphin',
    'Bandage + Attelle + Morphine': 'Verband + Schiene + Morphin',
    'Tête — protégé : rien, sinon Éraflure (Bandage). Torse — protégé : Hématome (Morphine), sinon Bandage': 'Kopf — geschützt: nichts, sonst Schürfwunde (Verband). Rumpf — geschützt: Bluterguss (Morphin), sonst Verband',
    'Protégé : Sonné (le médic aide à relever). Sinon : DCD': 'Geschützt: Benommen (der Sanitäter hilft beim Aufstehen). Sonst: Gefallen',
    'Repos 2 minutes': '2 Minuten Ruhe',
    'Bandage + Épinéphrine + Morphine': 'Verband + Adrenalin + Morphin',
    'Repos 1 minute': '1 Minute Ruhe',
    'Bandage compressif + Morphine': 'Druckverband + Morphin',
    'Pansement 3 côtés + Morphine': 'Dreiseitiger Verband + Morphin',
    'Bandage + Poche de transfusion + Épinéphrine': 'Verband + Blutbeutel + Adrenalin',
    'Attelle + Bandage': 'Schiene + Verband',
    'Garrot + Bandage + Poche de transfusion': 'Tourniquet + Verband + Blutbeutel',
    'Attelle + Bandage + Morphine': 'Schiene + Verband + Morphin',
    'Attelle + Morphine': 'Schiene + Morphin',
    'Garrot + Poche de transfusion + Épinéphrine': 'Tourniquet + Blutbeutel + Adrenalin',
    'Bandage + 30s Massage + Épi + Poche': 'Verband + 30s Herzdruckmassage + Adrenalin + Blutbeutel',
    '2x Bandages + Morphine': '2x Verbände + Morphin',
    'Garrot + Pansement 3 côtés + Poche de transfusion + Épinéphrine': 'Tourniquet + Dreiseitiger Verband + Blutbeutel + Adrenalin',
    'Casque porté : aucune blessure.\nSinon : Éraflure → Bandage': 'Helm getragen: keine Verletzung.\nSonst: Schürfwunde → Verband',
    'Gilet porté : Hématome → Morphine.\nSinon : Bandage': 'Weste getragen: Bluterguss → Morphin.\nSonst: Verband',
    'Casque porté : Sonné → le médic aide à relever.\nSinon : DCD': 'Helm getragen: Benommen → der Sanitäter hilft beim Aufstehen.\nSonst: Gefallen',
    'Gilet porté : Sonné → le médic aide à relever.\nSinon : DCD': 'Weste getragen: Benommen → der Sanitäter hilft beim Aufstehen.\nSonst: Gefallen'
},
bilan: {
    'Impact direct sur le casque lourd.': 'Direkter Treffer auf den schweren Helm.',
    'Plaie ouverte et profonde au front.': 'Tiefe offene Wunde an der Stirn.',
    'Traumatisme crânien sévère.': 'Schweres Schädel-Hirn-Trauma.',
    'Tir direct à la tête (sans port du casque).': 'Direkter Schuss in den Kopf (ohne Helm).',
    'Impact encaissé par la plaque balistique du porte-plaques.': 'Treffer von der ballistischen Platte des Plattenträgers aufgefangen.',
    'Éraflure sur le flanc, hors de la zone couverte par les plaques balistiques.': 'Schürfwunde an der Flanke, außerhalb des von den ballistischen Platten gedeckten Bereichs.',
    'Fracture de plusieurs côtes par impact lourd.': 'Mehrere Rippen durch schweren Aufprall gebrochen.',
    'Pneumothorax suite à une balle perforante latérale.': 'Pneumothorax nach einem seitlichen Durchschuss.',
    'Blessure perforante à l\'abdomen causant une importante hémorragie interne.': 'Durchdringende Bauchverletzung mit starker innerer Blutung.',
    'Tir direct au niveau du cœur ou de la colonne vertébrale (sans port de plaques balistiques).': 'Direkter Schuss auf Herz oder Wirbelsäule (ohne ballistische Platten).',
    'Balle logée dans les tissus mous de l\'avant-bras.': 'Kugel im Weichgewebe des Unterarms steckengeblieben.',
    'Fracture de l\'os de l\'avant-bras (radius / cubitus).': 'Bruch des Unterarmknochens (Speiche / Elle).',
    'Sectionnement de l\'artère brachiale.': 'Durchtrennte Oberarmarterie.',
    'Balle logée dans le muscle du mollet.': 'Kugel im Wadenmuskel steckengeblieben.',
    'Fracture du fémur.': 'Oberschenkelfraktur.',
    'Fracture de la rotule du genou.': 'Bruch der Kniescheibe.',
    'Sectionnement de l\'artère fémorale.': 'Durchtrennte Oberschenkelarterie.',
    'Éraflure superficielle due à un éclat sur la joue ou le lobe de l\'oreille.': 'Oberflächliche Schürfwunde durch einen Splitter an Wange oder Ohrläppchen.',
    'Multiples plaies par éclats de grenade sur le bras.': 'Mehrere Splitterwunden vom Granatsplitter am Arm.',
    'Criblage d\'éclats de shrapnel sur l\'ensemble des deux jambes.': 'Beide Beine von Splittern durchsiebt.',
    'Traumatisme contondant lourd au torse et sectionnement artériel à un bras suite à une explosion à proximité.': 'Schweres stumpfes Trauma am Rumpf und durchtrennte Arterie an einem Arm durch eine nahe Explosion.'
}
};
