/* BSE MEDICAL SYSTEM — ENGLISH
   Les tables zone/grav/mat/membre/titre/soin/bilan sont indexees par le
   texte FRANCAIS d'origine, qui reste la cle interne des cartes. */
window.BSE_I18N.en = {
ui: {
    'hdr.multijoueur': 'Multiplayer',
    'hdr.quitter': 'Leave the game',
    'hdr.sortir': 'Leave',
    'hdr.paquets': 'My decks',
    'hdr.reglages': 'Settings',
    'hdr.bseLien': 'Bravo Sierra Events — open the website',
    'hdr.bseAria': 'Open the Bravo Sierra Events website',
    'social.discord': 'Bravo Sierra Events on Discord',
    'social.instagram': 'Bravo Sierra Events on Instagram',
    'social.youtube': 'Bravo Sierra Events on YouTube',
    'social.facebook': 'Bravo Sierra Events on Facebook',
    'statut.solo': 'Solo',
    'statut.organisateur': 'Organiser',
    'statut.coadmin': 'Co-admin',
    'statut.reconnexion': '{nom} · Reconnecting to the game…',
    'paquet.balistique': 'Ballistic',
    'paquet.explosion': 'Explosion',

    'jeu.titre': 'Medical assessment',
    'jeu.sous': 'Tap to run the assessment',
    'jeu.paquetActif': 'Active deck',
    'jeu.chargement': 'Loading...',
    'jeu.cartes': '{n} cards',

    'march.titre': 'MARCH assessment',
    'march.m': 'Massive bleeding',
    'march.a': 'Airways',
    'march.r': 'Respiration',
    'march.c': 'Circulation',
    'march.h': 'Head / Hypothermia',
    'march.analyse': 'Assessment in progress…',

    'sil.titre': 'Which area was hit?',
    'sil.sous': 'Tap the part of the body that was hit',
    'sil.miroir': '(mirror view: their right arm is on your left)',

    'fiche.mort': 'Killed in action',
    'fiche.mortSous': 'Time up — fatal haemorrhage',
    'fiche.fermer': 'Close the file',
    'fiche.label': 'Triage sheet',
    'fiche.zone': 'Area hit',
    'fiche.bilan': 'Assessment',
    'fiche.protocole': 'Treatment protocol',
    'fiche.hemorragie': 'Active haemorrhage — life-threatening',
    'fiche.nouveau': 'New assessment',
    'fiche.soigner': 'Treatment done (save)',
    'fiche.stabilise': 'PATIENT STABILISED!',
    'fiche.protPortee': 'Body armour worn: {reponse}',
    'fiche.avecProtection': ' with body armour worn',

    'btn.annuler': 'Cancel',
    'btn.valider': 'Confirm',
    'btn.fermer': 'Close',
    'btn.retour': 'Back',
    'btn.copier': 'Copy',
    'btn.ouvrir': 'Open',
    'btn.oui': 'Yes',
    'btn.non': 'No',

    'qg.titre': 'HQ',
    'qg.partie': 'Game',
    'qg.enLigne': 'Online',
    'qg.ongletInvitation': 'Invite',
    'qg.ongletJoueurs': 'Players',
    'qg.ongletEquipes': 'Teams',
    'qg.ongletEditeur': 'Editor',
    'qg.ongletPaquets': 'Decks',
    'qg.ongletLogs': 'Logs',
    'qg.codeAide': 'Game code — read it out to your players',
    'qg.lienAide': 'Connection link (share or QR)',
    'qg.qrGeneration': 'Generating...',
    'qg.qrAide': 'Players scan the QR code or type the game name in the Join menu.',
    'qg.joueurs': 'PLAYERS',
    'qg.equipes': 'TEAMS IN THIS GAME',
    'qg.nomEquipePh': 'Team name',
    'qg.couleurEquipePh': '#hex colour',
    'qg.ajouterEquipe': '+ TEAM',
    'qg.editeur': 'DECK EDITOR',
    'qg.editeurAide': 'Set the quantities, the equipment and the death risk for all your decks before handing them out.',
    'qg.paquetsAttribues': 'ASSIGNED DECKS',
    'qg.paquetsAide1': 'Choose what each player will draw from: Classic, Advanced, Extreme, Explosion or one of your own decks. An assigned deck <b>replaces</b> the game mode for that player — they will only see this one, with the quantities set in the Editor.',
    'qg.paquetsAide2': 'A player with no assignment plays the <b>current mode</b> set in the Editor.',
    'qg.toutLeMonde': 'Everyone',
    'qg.uneEquipe': 'One team only',
    'qg.unJoueur': 'One player only',
    'qg.ajouterPaquet': 'Assign this deck',
    'qg.journal': 'LIVE LOG',
    'qg.journalAide': 'A player’s events are shown with their team name and colour.',
    'qg.telechargerLogs': 'Download the logs (.txt)',
    'qg.effacerAffichage': 'Clear the display',
    'qg.cloturer': 'Close the game (disconnect all players)',
    'qg.retourSession': 'Back to home (keep the session)',

    'reg.titre': 'System settings',
    'reg.profil': 'Multiplayer profile',
    'reg.pseudo': 'Your player name',
    'reg.pseudoPh': 'e.g. Doc',
    'reg.mode': 'Game mode',
    'reg.hardcore': 'Hardcore option',
    'reg.activerMort': 'Enable the risk of death',
    'reg.proba': 'Probability',
    'reg.probaSous': 'on an eligible injury',
    'reg.delaiMin': 'Min. delay',
    'reg.delaiMinSous': 'before death',
    'reg.delaiMax': 'Max. delay',
    'reg.etendreGraves': 'Extend to Serious injuries',
    'reg.explosion': 'Explosion',
    'reg.activerExplosion': 'Enable explosion cards',
    'reg.materiel': 'Required equipment',
    'reg.cartesActives': 'Active cards',
    'reg.catalogue': 'Catalogue',
    'reg.oeilAide': 'The eye on each row opens the mode catalogue at that card.',
    'reg.aide': 'Help',
    'reg.aideTexte': 'The full user guide, to read at the briefing. It stays available offline once opened.',
    'reg.guide': 'User guide (PDF)',

    'lang.titre': 'Language',
    'lang.choisir': 'Choose the language',

    'bld.titre': 'My decks',
    'bld.sous': 'Build your own card decks and show them on the home screen.',
    'bld.creer': '+ Create a deck',
    'bld.importer': 'Import a deck',
    'bld.edition': 'Edit deck',
    'bld.nom': 'Deck name',
    'bld.nomPh': 'e.g. Chemical injuries',
    'bld.afficherAccueil': 'Show on the home screen',
    'bld.modeExtreme': 'Extreme mode',
    'bld.modeExtremeSous': '(silhouette: area hit + body armour)',
    'bld.icone': 'Button icon',
    'bld.iconeAide': 'It identifies the deck on the home screen and for the players you assign it to.',
    'bld.cartes': 'Cards',
    'bld.ajouterCarte': '+ Add a card',
    'bld.enregistrer': 'Save',
    'bld.supprimerPaquet': 'Delete the deck',

    'ce.titreEcran': 'Card',
    'ce.gravite': 'Severity',
    'ce.titre': 'Title',
    'ce.titrePh': 'e.g. Fracture',
    'ce.zone': 'Area hit',
    'ce.zonePh': 'e.g. Arm',
    'zoneOpt.tete': 'Head',
    'zoneOpt.torse': 'Torso',
    'zoneOpt.teteTorse': 'Head or torso',
    'zoneOpt.brasD': 'Right arm',
    'zoneOpt.brasG': 'Left arm',
    'zoneOpt.bras': 'Both arms',
    'zoneOpt.jambeD': 'Right leg',
    'zoneOpt.jambeG': 'Left leg',
    'zoneOpt.jambes': 'Both legs',
    'zoneOpt.membres': 'All four limbs',
    'zoneOpt.libre': 'Custom area…',
    'zoneOpt.aideGroupe': 'One card is enough: the exact area is drawn at random, and in Extreme mode it is the one hit on the silhouette.',
    'zoneOpt.aideLibre': 'Write any area you like. It is shown as typed, and the card can come up on any area in Extreme mode.',
    'ce.protocole': 'Protocol / effect',
    'ce.protocolePh': 'e.g. Splint + Morphine',
    'ce.matos': 'Required equipment',
    'ce.matosAide': 'Tap a chip to select it. Equipment added here is only offered in this deck (✕ to remove it).',
    'ce.nouveauMatosPh': 'New equipment (e.g. Anti-rad)',
    'ce.valider': 'Confirm the card',

    'mod.apercu': 'Preview',
    'multi.titre': 'Multiplayer menu',
    'multi.nomPartie': 'Game name (host)',
    'multi.nomPartiePh': 'e.g. Exercise Alpha',
    'multi.pseudoHote': 'Host name',
    'multi.pseudoHotePh': 'e.g. Orga',
    'multi.liaison': 'Link between devices',
    'multi.firebase': 'Firebase server (recommended)',
    'multi.peer': 'Peer-to-peer (legacy)',
    'multi.aideFirebase': 'Goes through the server: works across different networks (4G / WiFi), and you can close your page without ending the game.',
    'multi.aidePeer': 'Direct connection between devices. Often needs a TURN relay, and your page must stay open.',
    'multi.creer': 'Create a game (host)',
    'multi.rejoindre': 'Join a game',
    'multi.scanner': 'Scan the QR code',
    'multi.codePh': 'Game name or link',
    'multi.connexion': 'Connect',
    'multi.testerReseau': 'Test the network',
    'multi.turn': 'Network relay (TURN) — optional',
    'multi.turnAide': 'Needed if the test shows ❌ TURN and your players are on other networks (4G, another WiFi). Create a free account on <b>metered.ca</b> (50 GB/month), add a “TURN server” and paste its credentials here. They are passed on to players automatically through the invitation link / QR code.',
    'multi.turnUrlPh': 'URL (e.g. turn:standard.relay.metered.ca:443)',
    'multi.turnUserPh': 'Username',
    'multi.turnPassPh': 'Password / credential',
    'multi.turnSave': 'Save the relay',
    'multi.statut': 'Connecting...',

    'join.titre': 'Join the game',
    'join.etabli': 'Connection established.',
    'join.pseudo': 'Your player name',
    'join.equipe': 'Your team',

    'prot.question': 'Body armour worn?',
    'prot.casque': 'Ballistic helmet worn?',
    'prot.gilet': 'Bulletproof vest worn?',

    'share.titre': 'Share the deck',

    'leave.titre': 'Leave the game?',
    'leave.texte': 'You will leave the multiplayer session and return to the main menu.',
    'leave.oui': 'Yes, leave',

    'mode.classique': 'Classic',
    'mode.avance': 'Advanced',
    'mode.extreme': 'Extreme',
    'mode.explosion': 'Explosion',
    'mode.perso': 'Custom',
    'mode.plusExplosion': ' + explosion',
    'reg.modeClassique': 'CLASSIC',
    'reg.modeAvance': 'ADVANCED',
    'reg.modeExtreme': 'EXTREME (silhouette)',
    'reg.custom': '{nom} (Custom)',
    'reg.aucunMateriel': 'No equipment required for this mode or this selection.',
    'reg.voirCarte': 'View the card',
    'reg.packExplosion': 'Explosion pack',
    'reg.verrouille': 'Settings locked by the host',

    'cat.titre': 'Catalogue — {mode}',
    'cat.sectionMode': 'Mode',
    'cat.sectionPerso': 'Custom deck',
    'cat.sectionExplosion': 'Explosion',
    'cat.protPortee': 'body armour worn',
    'cat.sansProt': 'no body armour',
    'cat.matos': 'Equipment:',
    'cat.aucuneCarte': 'No cards for this mode.',
    'carte.membreAleatoire': 'random limb',

    'btn.modifier': 'Edit',
    'btn.partager': 'Share',
    'btn.supprimer': 'Delete',

    'bld.nouveauPaquet': 'New deck',
    'bld.sansNom': 'Unnamed deck',
    'bld.sansTitre': 'Untitled',
    'bld.masque': 'Hidden',
    'bld.surAccueil': 'On the home screen',
    'bld.aucunPaquet': 'No custom deck yet.',
    'bld.aucunPaquetAide': 'Tap “+ CREATE A DECK” to get started.',
    'bld.aucuneCarte': 'No cards in this deck.',
    'bld.aucuneCarteAide': 'Tap “+ ADD A CARD”.',
    'bld.nMateriel': '{n} item(s)',
    'bld.enPartieTitre': 'Game in progress.',
    'bld.enPartieTexte': 'You are playing the decks assigned by the organiser. Your own decks are set aside and will be given back as soon as you leave the game.',
    'bld.bloqueEnPartie': 'Not possible during a game: the configuration comes from the organiser and your deck would be erased.\n\nLeave the game to get your own decks back and edit them.',
    'bld.confirmSupprCarte': 'Delete the card “{nom}”?',
    'bld.confirmSupprPaquet': 'Delete the deck “{nom}” and all its cards?',
    'ce.donnezTitre': 'Give the card a title.',
    'ce.confirmRetirerMatos': 'Remove “{nom}” from this deck? It will also be removed from the cards that use it.',

    'share.exportTitre': 'Share “{nom}”',
    'share.exportAide': 'Send this code to another player (SMS, WhatsApp, email...). They import it via “IMPORT A DECK” in My decks.',
    'share.copierCode': 'COPY THE CODE',
    'share.importAide': 'Paste the share code you received here (it starts with TMDECK1).',
    'share.importer': 'IMPORT',
    'share.codeCopie': 'Code copied!',
    'share.codeInvalide': 'Invalid or incomplete code. Check that it was copied in full.',
    'share.paquetImporte': 'Imported deck',
    'share.importeOk': 'Deck “{nom}” imported ({n} cards)!',

    'icone.cartes': 'Cards',
    'icone.blesse': 'Casualty',
    'icone.souffle': 'Blast',
    'icone.balle': 'Bullet',
    'icone.reticule': 'Crosshair',
    'icone.lame': 'Blade',
    'icone.grenade': 'Grenade',
    'icone.bombe': 'Bomb',
    'icone.explosion': 'Explosion',
    'icone.feu': 'Fire',
    'icone.decharge': 'Shock',
    'icone.froid': 'Cold',
    'icone.biohazard': 'Biohazard',
    'icone.radiation': 'Radiation',
    'icone.toxique': 'Toxic',
    'icone.masqueGaz': 'Gas mask',
    'icone.zombie': 'Zombie',
    'icone.creature': 'Creature',
    'icone.robot': 'Robot',
    'icone.crane': 'Skull',
    'icone.seringue': 'Syringe',
    'icone.cachets': 'Pills',
    'icone.perfusion': 'IV drip',
    'icone.pouls': 'Pulse',
    'icone.fracture': 'Fracture',
    'icone.trousse': 'Med kit',
    'icone.protection': 'Body armour',

    'qg.ligneMode': 'Mode: {nom}',
    'qg.lignePerso': 'Custom: {nom}',
    'qg.joue': 'IN PLAY',
    'qg.minEquipes': '(min. 2 teams)',
    'qg.horsLigne': 'offline',
    'qg.reviendra': 'Will come back automatically…',
    'qg.retirer': 'Remove',
    'qg.admin': 'Admin',
    'qg.kick': 'Kick',
    'qg.retirerPaquet': 'Remove this deck',
    'qg.cibleEquipe': 'Team {nom}',
    'qg.cibleJoueur': 'Player {nom}',
    'qg.aucunPaquetDistribue': 'No deck assigned.',
    'qg.aucunPaquetDistribueAide': 'Players only have the Ballistic draw.',
    'qg.paquetVide': 'This deck is empty with the current configuration.',
    'qg.dejaAttribueCible': '“{nom}” is already assigned to this target.',
    'qg.dejaAttribueTous': '“{nom}” is already assigned to everyone: no need to give it again to a team or a player.',
    'qg.indiquezNomEquipe': 'Enter a team name.',
    'qg.deuxEquipesMini': 'At least two teams are required.',
    'qg.choisirEquipe': 'Choose a team.',
    'qg.choisirJoueur': 'Choose a player (connected).',
    'qg.aucunLog': 'No logs to download.',
    'qg.logEntete': 'game log',
    'qg.logExporte': 'Exported on',
    'qg.confirmCloture': 'Close the game? All players will be notified and disconnected.',
    'qg.confirmClotureTous': 'Close the game for everyone?',
    'qg.qrIndisponible': 'QR unavailable.',
    'qg.qrIndisponibleAide': 'Share the link or the game name.',
    'qg.qrAlt': 'Invitation QR code',

    'log.partieOuverte': 'Game opened: {code}',
    'log.aRejoint': '{nom} joined',
    'log.sEstReconnecte': '{nom} reconnected',
    'log.quitteLaPartie': '{nom} left the game',
    'log.joueurDeconnecte': '{nom} disconnected (waiting to reconnect)',
    'log.pseudoDejaPris': 'Name “{demande}” already taken: this player becomes “{retenu}”',
    'log.sessionDemarree': 'Host session started: {code}',
    'log.sessionReprise': 'Session resumed: {code}',
    'log.configModifiee': '{nom} (co-admin) changed the configuration',
    'log.ajoutRefuse': 'Assignment refused ({nom}): {raison}',
    'log.tirage': '{nom} · draw: {carte} [{gravite}] · {source}',
    'log.coadmin': '{nom} · co-admin: {valeur}',
    'log.retireDeLaPartie': 'Removed from the game: {nom}',
    'log.partieCloturee': 'Game closed.',
    'log.partieClotureePar': 'Game closed by {nom} (co-admin).',
    'qg.logEquipeAjoutee': 'Team added: {nom}',
    'qg.logEquipeSupprimee': 'Team deleted, players reassigned.',
    'qg.logPaquetDistribue': 'Deck assigned: {nom} → {cible}',
    'qg.logRemplaceParTous': '{nom}: {n} targeted assignment(s) replaced by “everyone”',

    'multi.joueur': 'Player',
    'multi.orga': 'Orga',
    'multi.ouverture': 'Opening the game...',
    'multi.ouvertureImpossible': 'Could not open the game.',
    'multi.creation': 'Creating the game...',
    'multi.reprise': 'Resuming the game...',
    'multi.recherche': 'Looking for the game...',
    'multi.connexionReseau': 'Network connection in progress...',
    'multi.recuperation': 'Fetching the data...',
    'join.partieNommee': 'Game “{nom}”',

    'net.testEnCours': 'Test in progress (~15 s)...',
    'net.ligneSignalisation': 'Signalling (PeerJS server)',
    'net.ligneStun': 'STUN — direct connection possible',
    'net.ligneTurn': 'TURN — relay when direct is blocked',
    'net.aucunRelais': '(no relay configured)',
    'net.relaisEnregistre': 'Relay saved. It will be used for the next connections and passed on to players through the link / QR code.',
    'net.relaisEfface': 'Relay cleared.',
    'net.verdictOk': 'Everything is working: the connection should hold, even across different networks (4G ↔ router).',
    'net.verdictSansTurn': 'No TURN relay: the connection may fail across different networks or if the router isolates its devices. Set up a relay below (Network relay); it will be passed on to players through the QR code.',
    'net.verdictStunBloque': 'STUN is blocked although the Internet works: it is almost always the BROWSER blocking WebRTC’s UDP.<br>• <b>Opera / Opera GX</b>: turn off the built-in VPN, then in the settings look for “WebRTC” and choose “Use UDP without proxy”.<br>• Otherwise: VPN, antivirus or firewall. Try Chrome or Edge to confirm.<br>• A configured TURN relay also goes through TCP 443 and often gets around this block.',
    'net.verdictWebrtcOff': 'WebRTC is completely disabled in this browser (no network candidate). Check the browser’s privacy settings or try another one.',
    'net.verdictPasDeSignalisation': 'Signalling server unreachable: check your Internet access.',

    'msg.paquetIndisponible': 'This deck is no longer available.',
    'msg.aucunPaquetMode': 'No card deck for this mode. Check the settings or the custom deck.',
    'msg.aucuneCarteMateriel': 'No card available. Check that you have the required equipment (Settings).',
    'msg.aucuneCarteZone': 'No card available for this area{etat}.\n\nCheck the quantities and the available equipment in the Settings.',
    'msg.avecProtection': ' with body armour worn',
    'msg.sansProtection': ' without body armour',
    'msg.lienCopie': 'Invitation link copied.',
    'msg.codeCopie': 'Game code copied:',
    'msg.partiePasOuverte': 'The game is not open yet.',
    'msg.scannerIndisponible': 'QR scanner unavailable (library not loaded — check your Internet connection).',
    'msg.peerIndisponible': 'Multiplayer unavailable (PeerJS library not loaded — check your Internet connection).',
    'msg.firebaseIndisponible': 'Firebase multiplayer is not available (library missing).',
    'msg.droitsOrga': 'Change refused: you do not have organiser rights on this game.',
    'msg.devenuCoOrga': 'You are now a co-organiser: the game HQ is available through the multiplayer button, top right.',
    'msg.gradeRetire': 'Admin rights removed.',
    'msg.retireDeLaPartie': 'You have been removed from the game.',
    'msg.exclu': 'You have been kicked from the game.',
    'msg.orgaACloture': 'The organiser closed the game.',
    'msg.partieTerminee': 'The game is over.',
    'msg.nomPartiePris': 'A game already has this name and belongs to someone else. Choose another name.',
    'msg.nomPartieDejaPris': 'This game name is already in use (or the previous session has not expired yet). Wait a minute or change the name.',
    'msg.partieIntrouvable': 'Game not found. Check the name with the organiser.',
    'msg.partieIntrouvableHote': 'The game cannot be found. Check that the Host has not closed their web page or cancelled the game.',
    'msg.partieCloturee': 'This game is closed.',
    'msg.erreurPeer': 'PeerJS error',
    'msg.repriseImpossible': 'The game “{nom}” cannot be resumed right now ({raison}). It will try again next time you come back to the page, or recreate the game with the same name to get your players back.',
    'msg.dejaHote': 'You are already hosting a game on this device. Leave the previous game through the Host screen before joining another one as a player.',
    'msg.indiquezNomPartie': 'Enter the game name or scan the QR code.',
    'msg.indiquezPseudo': 'Enter a player name: this is how the organiser will see you in the game.',
    'msg.delaiDepasse': 'Timed out: the link with the Host could not be established. Check that their page is open, then run “Test the network” in the multiplayer menu: if TURN fails, the host must set up a relay (“Network relay”) — it is passed on automatically through their QR code.',
    'msg.hoteIntrouvable': 'Connection failed: host not found or unstable network.',
    'msg.connexionImpossible': 'Connection failed.',
    'msg.connexionPerdue': 'Connection lost. Try joining the game again.',
    'msg.connexionPerdueHote': 'Connection to the host lost.',
    'msg.reconnexionImpossible': 'Cannot reconnect: the game seems to be over or the host unreachable.',
    'msg.connecte': 'Connected to the game!',
    'msg.pseudoRemplace': 'That name was already taken in the game. You appear as: {nom}',
    'msg.changementEquipe': 'Team change'
},
zone: {
    'Membres': 'Limbs',
    'Tête ou Torse': 'Head or Torso',
    'Torse': 'Torso',
    'Tête': 'Head',
    'Bras': 'Arm',
    'Jambe': 'Leg',
    'Jambes': 'Legs',
    'Torse et bras': 'Torso and arm'
},
grav: {
    'DÉCÈS': 'DEATH',
    'Critique': 'Critical',
    'Grave': 'Serious',
    'Légère': 'Minor',
    'Spécial': 'Special'
},
membre: {
    'Bras Gauche': 'Left Arm',
    'Bras Droit': 'Right Arm',
    'Jambe Gauche': 'Left Leg',
    'Jambe Droite': 'Right Leg'
},
mat: {
    'Garrot': 'Tourniquet',
    'Bandage': 'Bandage',
    'Poche de transfusion': 'Blood bag',
    'Attelle': 'Splint',
    'Morphine': 'Morphine',
    'Épinéphrine': 'Epinephrine',
    'Pansement 3 côtés': '3-sided seal'
},
titre: {
    'DCD': 'KIA',
    'Inconscient': 'Unconscious',
    'Hémorragie': 'Haemorrhage',
    'Saignement': 'Bleeding',
    'Fracture': 'Fracture',
    'Éraflure': 'Graze',
    'Choc Casque': 'Helmet Impact',
    'Choc Gilet': 'Vest Impact',
    'Plaie soufflante': 'Sucking chest wound',
    'Saignement grave': 'Severe bleeding',
    'Prot. Balistique': 'Body Armour',
    'Choc Balistique': 'Ballistic Impact',
    'Impact sur casque': 'Impact on the helmet',
    'Plaie au front': 'Wound to the forehead',
    'Traumatisme crânien': 'Head trauma',
    'Tir à la tête': 'Headshot',
    'Impact sur plaque': 'Impact on the plate',
    'Éraflure au flanc': 'Graze to the flank',
    'Côtes fracturées': 'Broken ribs',
    'Pneumothorax': 'Pneumothorax',
    'Hémorragie interne': 'Internal haemorrhage',
    'Tir vital': 'Fatal shot',
    'Balle dans l\'avant-bras': 'Bullet in the forearm',
    'Fracture de l\'avant-bras': 'Fractured forearm',
    'Artère brachiale': 'Brachial artery',
    'Balle au mollet': 'Bullet in the calf',
    'Fracture du fémur': 'Fractured femur',
    'Fracture de la rotule': 'Fractured kneecap',
    'Artère fémorale': 'Femoral artery',
    'DCD (Blast)': 'KIA (Blast)',
    'Plaie Soufflante': 'Sucking Chest Wound',
    'Hémorragie Massive': 'Massive Haemorrhage',
    'Saignement Grave': 'Severe Bleeding',
    'Fracture Ouverte': 'Open Fracture',
    'Éraflure (Éclat)': 'Graze (Shrapnel)',
    'Souffle (Blast)': 'Blast Wave',
    'Éraflure au visage': 'Graze to the face',
    'Éclats au bras': 'Shrapnel in the arm',
    'Criblage d\'éclats': 'Riddled with shrapnel',
    'Souffle d\'explosion': 'Explosion blast'
},
soin: {
    'Respawn direct': 'Straight to respawn',
    '30s massage + Poche': '30s CPR + Blood bag',
    'Garrot + Poche': 'Tourniquet + Blood bag',
    'Bandage + Poche': 'Bandage + Blood bag',
    'Attelle': 'Splint',
    'Bandage': 'Bandage',
    'Si Protégé : Sonné (Médic aide à relever). Sinon : Bandage ([MEMBRE_ALEATOIRE])': 'If protected: Stunned (medic helps them up). Otherwise: Bandage ([MEMBRE_ALEATOIRE])',
    'Bandage + Massage + Épi + Poche': 'Bandage + CPR + Epi + Blood bag',
    'Pnsmt 3 côtés + Morphine + Poche': '3-sided seal + Morphine + Blood bag',
    'Garrot + Bandage + Morphine + Poche': 'Tourniquet + Bandage + Morphine + Blood bag',
    'Bandage + Morphine': 'Bandage + Morphine',
    'Bandage + Attelle + Morphine': 'Bandage + Splint + Morphine',
    'Tête — protégé : rien, sinon Éraflure (Bandage). Torse — protégé : Hématome (Morphine), sinon Bandage': 'Head — protected: nothing, otherwise Graze (Bandage). Torso — protected: Bruising (Morphine), otherwise Bandage',
    'Protégé : Sonné (le médic aide à relever). Sinon : DCD': 'Protected: Stunned (the medic helps them up). Otherwise: KIA',
    'Repos 2 minutes': 'Rest for 2 minutes',
    'Bandage + Épinéphrine + Morphine': 'Bandage + Epinephrine + Morphine',
    'Repos 1 minute': 'Rest for 1 minute',
    'Bandage compressif + Morphine': 'Pressure bandage + Morphine',
    'Pansement 3 côtés + Morphine': '3-sided seal + Morphine',
    'Bandage + Poche de transfusion + Épinéphrine': 'Bandage + Blood bag + Epinephrine',
    'Attelle + Bandage': 'Splint + Bandage',
    'Garrot + Bandage + Poche de transfusion': 'Tourniquet + Bandage + Blood bag',
    'Attelle + Bandage + Morphine': 'Splint + Bandage + Morphine',
    'Attelle + Morphine': 'Splint + Morphine',
    'Garrot + Poche de transfusion + Épinéphrine': 'Tourniquet + Blood bag + Epinephrine',
    'Bandage + 30s Massage + Épi + Poche': 'Bandage + 30s CPR + Epi + Blood bag',
    '2x Bandages + Morphine': '2x Bandages + Morphine',
    'Garrot + Pansement 3 côtés + Poche de transfusion + Épinéphrine': 'Tourniquet + 3-sided seal + Blood bag + Epinephrine',
    'Casque porté : aucune blessure.\nSinon : Éraflure → Bandage': 'Helmet worn: no injury.\nOtherwise: Graze → Bandage',
    'Gilet porté : Hématome → Morphine.\nSinon : Bandage': 'Vest worn: Bruising → Morphine.\nOtherwise: Bandage',
    'Casque porté : Sonné → le médic aide à relever.\nSinon : DCD': 'Helmet worn: Stunned → the medic helps them up.\nOtherwise: KIA',
    'Gilet porté : Sonné → le médic aide à relever.\nSinon : DCD': 'Vest worn: Stunned → the medic helps them up.\nOtherwise: KIA'
},
bilan: {
    'Impact direct sur le casque lourd.': 'Direct impact on the heavy helmet.',
    'Plaie ouverte et profonde au front.': 'Deep open wound to the forehead.',
    'Traumatisme crânien sévère.': 'Severe head trauma.',
    'Tir direct à la tête (sans port du casque).': 'Direct shot to the head (no helmet worn).',
    'Impact encaissé par la plaque balistique du porte-plaques.': 'Impact absorbed by the plate carrier’s ballistic plate.',
    'Éraflure sur le flanc, hors de la zone couverte par les plaques balistiques.': 'Graze to the flank, outside the area covered by the ballistic plates.',
    'Fracture de plusieurs côtes par impact lourd.': 'Several ribs broken by a heavy impact.',
    'Pneumothorax suite à une balle perforante latérale.': 'Pneumothorax from a penetrating side shot.',
    'Blessure perforante à l\'abdomen causant une importante hémorragie interne.': 'Penetrating wound to the abdomen causing heavy internal bleeding.',
    'Tir direct au niveau du cœur ou de la colonne vertébrale (sans port de plaques balistiques).': 'Direct shot to the heart or the spine (no ballistic plates worn).',
    'Balle logée dans les tissus mous de l\'avant-bras.': 'Bullet lodged in the soft tissue of the forearm.',
    'Fracture de l\'os de l\'avant-bras (radius / cubitus).': 'Fracture of the forearm bone (radius / ulna).',
    'Sectionnement de l\'artère brachiale.': 'Severed brachial artery.',
    'Balle logée dans le muscle du mollet.': 'Bullet lodged in the calf muscle.',
    'Fracture du fémur.': 'Fractured femur.',
    'Fracture de la rotule du genou.': 'Fractured kneecap.',
    'Sectionnement de l\'artère fémorale.': 'Severed femoral artery.',
    'Éraflure superficielle due à un éclat sur la joue ou le lobe de l\'oreille.': 'Superficial graze from shrapnel on the cheek or the earlobe.',
    'Multiples plaies par éclats de grenade sur le bras.': 'Multiple grenade shrapnel wounds on the arm.',
    'Criblage d\'éclats de shrapnel sur l\'ensemble des deux jambes.': 'Both legs riddled with shrapnel.',
    'Traumatisme contondant lourd au torse et sectionnement artériel à un bras suite à une explosion à proximité.': 'Heavy blunt trauma to the torso and a severed artery in one arm from a nearby explosion.'
}
};
