/* BSE MEDICAL SYSTEM — ITALIANO
   Les tables zone/grav/mat/membre/titre/soin/bilan sont indexees par le
   texte FRANCAIS d'origine, qui reste la cle interne des cartes. */
window.BSE_I18N.it = {
ui: {
    'hdr.multijoueur': 'Multigiocatore',
    'hdr.quitter': 'Lascia la partita',
    'hdr.sortir': 'Esci',
    'hdr.paquets': 'I miei mazzi',
    'hdr.reglages': 'Impostazioni',
    'hdr.bseLien': 'Bravo Sierra Events — apri il sito',
    'hdr.bseAria': 'Apri il sito di Bravo Sierra Events',
    'social.discord': 'Bravo Sierra Events su Discord',
    'social.instagram': 'Bravo Sierra Events su Instagram',
    'social.youtube': 'Bravo Sierra Events su YouTube',
    'social.facebook': 'Bravo Sierra Events su Facebook',
    'statut.solo': 'Solo',
    'statut.organisateur': 'Organizzatore',
    'statut.coadmin': 'Co-admin',
    'statut.reconnexion': '{nom} · Riconnessione alla partita…',
    'paquet.balistique': 'Balistica',
    'paquet.explosion': 'Esplosione',

    'jeu.titre': 'Diagnosi medica',
    'jeu.sous': 'Tocca per avviare la diagnosi',
    'jeu.paquetActif': 'Mazzo attivo',
    'jeu.chargement': 'Caricamento...',
    'jeu.cartes': '{n} carte',

    'march.titre': 'Valutazione MARCH',
    'march.m': 'Emorragia massiva',
    'march.a': 'Vie aeree',
    'march.r': 'Respirazione',
    'march.c': 'Circolazione',
    'march.h': 'Testa / Ipotermia',
    'march.analyse': 'Valutazione in corso…',

    'sil.titre': 'Quale zona è stata colpita?',
    'sil.sous': 'Tocca la parte del corpo colpita',
    'sil.miroir': '(vista a specchio: il suo braccio destro è alla tua sinistra)',

    'fiche.mort': 'Caduto in combattimento',
    'fiche.mortSous': 'Tempo scaduto — emorragia fatale',
    'fiche.fermer': 'Chiudi la scheda',
    'fiche.label': 'Scheda di triage',
    'fiche.zone': 'Zona colpita',
    'fiche.bilan': 'Quadro clinico',
    'fiche.protocole': 'Protocollo di cura',
    'fiche.hemorragie': 'Emorragia in corso — urgenza vitale',
    'fiche.nouveau': 'Nuova diagnosi',
    'fiche.soigner': 'Cure effettuate (salvare)',
    'fiche.stabilise': 'PAZIENTE STABILIZZATO!',
    'fiche.protPortee': 'Protezione balistica indossata: {reponse}',
    'fiche.avecProtection': ' con protezione indossata',

    'btn.annuler': 'Annulla',
    'btn.valider': 'Conferma',
    'btn.fermer': 'Chiudi',
    'btn.retour': 'Indietro',
    'btn.copier': 'Copia',
    'btn.ouvrir': 'Apri',
    'btn.oui': 'Sì',
    'btn.non': 'No',

    'qg.titre': 'QG',
    'qg.partie': 'Partita',
    'qg.enLigne': 'Online',
    'qg.ongletInvitation': 'Invito',
    'qg.ongletJoueurs': 'Giocatori',
    'qg.ongletEquipes': 'Squadre',
    'qg.ongletEditeur': 'Editor',
    'qg.ongletPaquets': 'Mazzi',
    'qg.ongletLogs': 'Registro',
    'qg.codeAide': 'Codice della partita — da dettare ai giocatori',
    'qg.lienAide': 'Link di connessione (condivisione o QR)',
    'qg.qrGeneration': 'Generazione...',
    'qg.qrAide': 'I giocatori scansionano il codice QR o digitano il nome della partita nel menu Unisciti.',
    'qg.joueurs': 'GIOCATORI',
    'qg.equipes': 'SQUADRE DELLA PARTITA',
    'qg.nomEquipePh': 'Nome squadra',
    'qg.couleurEquipePh': '#hex colore',
    'qg.ajouterEquipe': '+ SQUADRA',
    'qg.editeur': 'EDITOR DEI MAZZI',
    'qg.editeurAide': 'Regola le quantità, il materiale e il rischio di morte per tutti i tuoi mazzi prima di distribuirli.',
    'qg.paquetsAttribues': 'MAZZI ASSEGNATI',
    'qg.paquetsAide1': 'Scegli da cosa pescherà ogni giocatore: Classico, Avanzato, Estremo, Esplosione o uno dei tuoi mazzi personali. Il mazzo assegnato <b>sostituisce</b> la modalità di gioco del destinatario — vedrà solo quello, con le quantità impostate nell’Editor.',
    'qg.paquetsAide2': 'Un giocatore senza alcuna assegnazione gioca la <b>modalità in corso</b> definita nell’Editor.',
    'qg.toutLeMonde': 'Tutti',
    'qg.uneEquipe': 'Solo una squadra',
    'qg.unJoueur': 'Solo un giocatore',
    'qg.ajouterPaquet': 'Assegna questo mazzo',
    'qg.journal': 'REGISTRO IN TEMPO REALE',
    'qg.journalAide': 'Gli eventi di un giocatore appaiono con il nome e il colore della sua squadra.',
    'qg.telechargerLogs': 'Scarica il registro (.txt)',
    'qg.effacerAffichage': 'Svuota la visualizzazione',
    'qg.cloturer': 'Chiudi la partita (disconnetti i giocatori)',
    'qg.retourSession': 'Torna alla home (mantieni la sessione)',

    'reg.titre': 'Impostazioni di sistema',
    'reg.profil': 'Profilo multigiocatore',
    'reg.pseudo': 'Il tuo nome giocatore',
    'reg.pseudoPh': 'Es.: Doc',
    'reg.mode': 'Modalità di gioco',
    'reg.hardcore': 'Opzione hardcore',
    'reg.activerMort': 'Attiva il rischio di morte',
    'reg.proba': 'Probabilità',
    'reg.probaSous': 'su una ferita idonea',
    'reg.delaiMin': 'Tempo minimo',
    'reg.delaiMinSous': 'prima del decesso',
    'reg.delaiMax': 'Tempo massimo',
    'reg.etendreGraves': 'Estendi alle ferite Gravi',
    'reg.explosion': 'Esplosione',
    'reg.activerExplosion': 'Attiva le carte esplosione',
    'reg.materiel': 'Materiale necessario',
    'reg.cartesActives': 'Carte attive',
    'reg.catalogue': 'Catalogo',
    'reg.oeilAide': 'L’occhio di ogni riga apre il catalogo della modalità sulla carta interessata.',
    'reg.aide': 'Aiuto',
    'reg.aideTexte': 'La guida completa, da leggere al briefing. Resta consultabile offline una volta aperta.',
    'reg.guide': 'Guida all’uso (PDF)',

    'lang.titre': 'Lingua',
    'lang.choisir': 'Scegli la lingua',

    'bld.titre': 'I miei mazzi',
    'bld.sous': 'Crea i tuoi mazzi di carte e mostrali sulla schermata iniziale.',
    'bld.creer': '+ Crea un mazzo',
    'bld.importer': 'Importa un mazzo',
    'bld.edition': 'Modifica del mazzo',
    'bld.nom': 'Nome del mazzo',
    'bld.nomPh': 'Es.: Ferite chimiche',
    'bld.afficherAccueil': 'Mostra sulla schermata iniziale',
    'bld.modeExtreme': 'Modalità estrema',
    'bld.modeExtremeSous': '(sagoma: zona colpita + protezione)',
    'bld.icone': 'Icona del pulsante',
    'bld.iconeAide': 'Identifica il mazzo sulla schermata iniziale e presso i giocatori a cui lo assegni.',
    'bld.cartes': 'Carte',
    'bld.ajouterCarte': '+ Aggiungi una carta',
    'bld.enregistrer': 'Salva',
    'bld.supprimerPaquet': 'Elimina il mazzo',

    'ce.titreEcran': 'Carta',
    'ce.gravite': 'Gravità',
    'ce.titre': 'Titolo',
    'ce.titrePh': 'Es.: Frattura',
    'ce.zone': 'Zona colpita',
    'ce.zonePh': 'Es.: Braccio',
    'zoneOpt.tete': 'Testa',
    'zoneOpt.torse': 'Torso',
    'zoneOpt.teteTorse': 'Testa o torso',
    'zoneOpt.brasD': 'Braccio destro',
    'zoneOpt.brasG': 'Braccio sinistro',
    'zoneOpt.bras': 'Entrambe le braccia',
    'zoneOpt.jambeD': 'Gamba destra',
    'zoneOpt.jambeG': 'Gamba sinistra',
    'zoneOpt.jambes': 'Entrambe le gambe',
    'zoneOpt.membres': 'Tutti e quattro gli arti',
    'zoneOpt.libre': 'Zona personalizzata…',
    'zoneOpt.aideGroupe': 'Basta una carta: la zona esatta viene estratta a caso e, in modalità Estrema, è quella colpita sulla sagoma.',
    'zoneOpt.aideLibre': 'Scrivi la zona che vuoi. Appare così com\'è, e la carta può uscire su qualsiasi zona in modalità Estrema.',
    'ce.protection': 'Protezione balistica',
    'prot.peuImporte': 'Indifferente',
    'prot.avec': 'Con protezione',
    'prot.sans': 'Senza protezione',
    'prot.aide': 'Agisce solo in modalità Estrema, e solo su testa e torso: è lì che viene posta la domanda sull\'elmetto o sul giubbotto. Su un arto, la carta esce comunque.',
    'ce.protocole': 'Protocollo / effetto',
    'ce.protocolePh': 'Es.: Stecca + Morfina',
    'ce.matos': 'Materiale necessario',
    'ce.matosAide': 'Tocca una pastiglia per selezionarla. Il materiale aggiunto qui è proposto solo in questo mazzo (✕ per toglierlo).',
    'ce.nouveauMatosPh': 'Nuovo materiale (es.: Anti-rad)',
    'ce.valider': 'Conferma la carta',

    'mod.apercu': 'Anteprima',
    'multi.titre': 'Menu multigiocatore',
    'multi.nomPartie': 'Nome della partita (host)',
    'multi.nomPartiePh': 'Es.: Esercitazione Alfa',
    'multi.pseudoHote': 'Nome dell’host',
    'multi.pseudoHotePh': 'Es.: Orga',
    'multi.liaison': 'Collegamento tra dispositivi',
    'multi.firebase': 'Server Firebase (consigliato)',
    'multi.peer': 'Peer-to-peer (vecchio)',
    'multi.aideFirebase': 'Passa dal server: funziona tra reti diverse (4G / WiFi) e puoi chiudere la tua pagina senza interrompere la partita.',
    'multi.aidePeer': 'Connessione diretta tra dispositivi. Richiede spesso un relay TURN e la tua pagina deve restare aperta.',
    'multi.creer': 'Crea una partita (host)',
    'multi.rejoindre': 'Unisciti a una partita',
    'multi.scanner': 'Scansiona il codice QR',
    'multi.codePh': 'Nome della partita o link',
    'multi.connexion': 'Connetti',
    'multi.testerReseau': 'Prova la rete',
    'multi.turn': 'Relay di rete (TURN) — opzionale',
    'multi.turnAide': 'Necessario se il test mostra ❌ TURN e i tuoi giocatori sono su altre reti (4G, altro WiFi). Crea un account gratuito su <b>metered.ca</b> (50 GB/mese), aggiungi un «TURN server» e incolla qui le sue credenziali. Vengono trasmesse automaticamente ai giocatori tramite il link / codice QR d’invito.',
    'multi.turnUrlPh': 'URL (es.: turn:standard.relay.metered.ca:443)',
    'multi.turnUserPh': 'Nome utente',
    'multi.turnPassPh': 'Password / credenziale',
    'multi.turnSave': 'Salva il relay',
    'multi.statut': 'Connessione...',

    'join.titre': 'Unisciti alla partita',
    'join.etabli': 'Connessione stabilita.',
    'join.pseudo': 'Il tuo nome giocatore',
    'join.equipe': 'La tua squadra',

    'prot.question': 'Protezione balistica indossata?',
    'prot.casque': 'Elmetto balistico indossato?',
    'prot.gilet': 'Giubbotto antiproiettile indossato?',

    'share.titre': 'Condividi il mazzo',

    'leave.titre': 'Lasciare la partita?',
    'leave.texte': 'Uscirai dalla sessione multigiocatore e tornerai al menu principale.',
    'leave.oui': 'Sì, esci',

    'mode.classique': 'Classico',
    'mode.avance': 'Avanzato',
    'mode.extreme': 'Estremo',
    'mode.explosion': 'Esplosione',
    'mode.perso': 'Personale',
    'mode.plusExplosion': ' + esplosione',
    'reg.modeClassique': 'CLASSICO',
    'reg.modeAvance': 'AVANZATO',
    'reg.modeExtreme': 'ESTREMO (sagoma)',
    'reg.custom': '{nom} (Personale)',
    'reg.aucunMateriel': 'Nessun materiale necessario per questa modalità o questa selezione.',
    'reg.voirCarte': 'Vedi la carta',
    'reg.packExplosion': 'Pacchetto esplosione',
    'reg.verrouille': 'Impostazioni bloccate dall’host',

    'cat.titre': 'Catalogo — {mode}',
    'cat.sectionMode': 'Modalità',
    'cat.sectionPerso': 'Mazzo personale',
    'cat.sectionExplosion': 'Esplosione',
    'cat.protPortee': 'protezione indossata',
    'cat.sansProt': 'senza protezione',
    'cat.matos': 'Materiale:',
    'cat.aucuneCarte': 'Nessuna carta per questa modalità.',
    'carte.membreAleatoire': 'arto a caso',

    'btn.modifier': 'Modifica',
    'btn.partager': 'Condividi',
    'btn.supprimer': 'Elimina',

    'bld.nouveauPaquet': 'Nuovo mazzo',
    'bld.sansNom': 'Mazzo senza nome',
    'bld.sansTitre': 'Senza titolo',
    'bld.masque': 'Nascosto',
    'bld.surAccueil': 'Sulla schermata iniziale',
    'bld.aucunPaquet': 'Nessun mazzo personale per ora.',
    'bld.aucunPaquetAide': 'Premi «+ CREA UN MAZZO» per iniziare.',
    'bld.aucuneCarte': 'Nessuna carta in questo mazzo.',
    'bld.aucuneCarteAide': 'Premi «+ AGGIUNGI UNA CARTA».',
    'bld.nMateriel': '{n} materiale/i',
    'bld.enPartieTitre': 'Partita in corso.',
    'bld.enPartieTexte': 'Stai giocando i mazzi assegnati dall’organizzatore. I tuoi mazzi personali sono messi da parte e ti verranno restituiti appena lascerai la partita.',
    'bld.bloqueEnPartie': 'Impossibile durante una partita: la configurazione viene dall’organizzatore e il tuo mazzo verrebbe cancellato.\n\nEsci dalla partita per ritrovare e modificare i tuoi mazzi personali.',
    'bld.confirmSupprCarte': 'Eliminare la carta «{nom}»?',
    'bld.confirmSupprPaquet': 'Eliminare il mazzo «{nom}» e tutte le sue carte?',
    'ce.donnezTitre': 'Dai un titolo alla carta.',
    'ce.confirmRetirerMatos': 'Togliere «{nom}» da questo mazzo? Verrà tolto anche dalle carte che lo usano.',

    'share.exportTitre': 'Condividi «{nom}»',
    'share.exportAide': 'Manda questo codice a un altro giocatore (SMS, WhatsApp, e-mail...). Lo importerà tramite «IMPORTA UN MAZZO» in I miei mazzi.',
    'share.copierCode': 'COPIA IL CODICE',
    'share.importAide': 'Incolla qui il codice di condivisione ricevuto (inizia con TMDECK1).',
    'share.importer': 'IMPORTA',
    'share.codeCopie': 'Codice copiato!',
    'share.codeInvalide': 'Codice non valido o incompleto. Controlla che sia stato copiato per intero.',
    'share.paquetImporte': 'Mazzo importato',
    'share.importeOk': 'Mazzo «{nom}» importato ({n} carte)!',

    'icone.cartes': 'Carte',
    'icone.blesse': 'Ferito',
    'icone.souffle': 'Onda d’urto',
    'icone.balle': 'Proiettile',
    'icone.reticule': 'Mirino',
    'icone.lame': 'Lama',
    'icone.grenade': 'Granata',
    'icone.bombe': 'Bomba',
    'icone.explosion': 'Esplosione',
    'icone.feu': 'Fuoco',
    'icone.decharge': 'Scarica',
    'icone.froid': 'Freddo',
    'icone.biohazard': 'Rischio biologico',
    'icone.radiation': 'Radiazione',
    'icone.toxique': 'Tossico',
    'icone.masqueGaz': 'Maschera antigas',
    'icone.zombie': 'Zombie',
    'icone.creature': 'Creatura',
    'icone.robot': 'Robot',
    'icone.crane': 'Teschio',
    'icone.seringue': 'Siringa',
    'icone.cachets': 'Pastiglie',
    'icone.perfusion': 'Flebo',
    'icone.pouls': 'Battito',
    'icone.fracture': 'Frattura',
    'icone.trousse': 'Kit medico',
    'icone.protection': 'Protezione',

    'qg.ligneMode': 'Modalità: {nom}',
    'qg.lignePerso': 'Personale: {nom}',
    'qg.joue': 'IN GIOCO',
    'qg.minEquipes': '(min. 2 squadre)',
    'qg.horsLigne': 'offline',
    'qg.reviendra': 'Tornerà automaticamente…',
    'qg.retirer': 'Togli',
    'qg.admin': 'Admin',
    'qg.kick': 'Espelli',
    'qg.retirerPaquet': 'Togli questo mazzo',
    'qg.cibleEquipe': 'Squadra {nom}',
    'qg.cibleJoueur': 'Giocatore {nom}',
    'qg.aucunPaquetDistribue': 'Nessun mazzo assegnato.',
    'qg.aucunPaquetDistribueAide': 'I giocatori hanno solo la pesca Balistica.',
    'qg.paquetVide': 'Questo mazzo è vuoto con la configurazione attuale.',
    'qg.dejaAttribueCible': '«{nom}» è già assegnato a questo destinatario.',
    'qg.dejaAttribueTous': '«{nom}» è già assegnato a tutti: è inutile ridarlo a una squadra o a un giocatore.',
    'qg.indiquezNomEquipe': 'Indica un nome di squadra.',
    'qg.deuxEquipesMini': 'Servono almeno due squadre.',
    'qg.choisirEquipe': 'Scegli una squadra.',
    'qg.choisirJoueur': 'Scegli un giocatore (connesso).',
    'qg.aucunLog': 'Nessun registro da scaricare.',
    'qg.logEntete': 'registro della partita',
    'qg.logExporte': 'Esportato il',
    'qg.confirmCloture': 'Chiudere la partita? Tutti i giocatori saranno avvisati e disconnessi.',
    'qg.confirmClotureTous': 'Chiudere la partita per tutti?',
    'qg.qrIndisponible': 'QR non disponibile.',
    'qg.qrIndisponibleAide': 'Condividi il link o il nome della partita.',
    'qg.qrAlt': 'Codice QR d’invito',

    'log.partieOuverte': 'Partita aperta: {code}',
    'log.aRejoint': '{nom} si è unito',
    'log.sEstReconnecte': '{nom} si è riconnesso',
    'log.quitteLaPartie': '{nom} lascia la partita',
    'log.joueurDeconnecte': '{nom} disconnesso (in attesa di riconnessione)',
    'log.pseudoDejaPris': 'Nome «{demande}» già in uso: questo giocatore diventa «{retenu}»',
    'log.sessionDemarree': 'Sessione host avviata: {code}',
    'log.sessionReprise': 'Sessione ripresa: {code}',
    'log.configModifiee': '{nom} (co-admin) ha modificato la configurazione',
    'log.ajoutRefuse': 'Assegnazione rifiutata ({nom}): {raison}',
    'log.tirage': '{nom} · pesca: {carte} [{gravite}] · {source}',
    'log.coadmin': '{nom} · co-admin: {valeur}',
    'log.retireDeLaPartie': 'Rimosso dalla partita: {nom}',
    'log.partieCloturee': 'Partita chiusa.',
    'log.partieClotureePar': 'Partita chiusa da {nom} (co-admin).',
    'qg.logEquipeAjoutee': 'Squadra aggiunta: {nom}',
    'qg.logEquipeSupprimee': 'Squadra eliminata, giocatori riassegnati.',
    'qg.logPaquetDistribue': 'Mazzo assegnato: {nom} → {cible}',
    'qg.logRemplaceParTous': '{nom}: {n} assegnazione/i mirata/e sostituita/e con «tutti»',

    'multi.joueur': 'Giocatore',
    'multi.orga': 'Orga',
    'multi.ouverture': 'Apertura della partita...',
    'multi.ouvertureImpossible': 'Apertura impossibile.',
    'multi.creation': 'Creazione della partita...',
    'multi.reprise': 'Ripresa della partita...',
    'multi.recherche': 'Ricerca della partita...',
    'multi.connexionReseau': 'Connessione di rete in corso...',
    'multi.recuperation': 'Recupero dei dati...',
    'join.partieNommee': 'Partita «{nom}»',

    'net.testEnCours': 'Test in corso (~15 s)...',
    'net.ligneSignalisation': 'Segnalazione (server PeerJS)',
    'net.ligneStun': 'STUN — connessione diretta possibile',
    'net.ligneTurn': 'TURN — relay se la diretta è bloccata',
    'net.aucunRelais': '(nessun relay configurato)',
    'net.relaisEnregistre': 'Relay salvato. Sarà usato per le prossime connessioni e trasmesso ai giocatori tramite il link / codice QR.',
    'net.relaisEfface': 'Relay cancellato.',
    'net.verdictOk': 'Tutto funziona: la connessione dovrebbe reggere, anche tra reti diverse (4G ↔ router).',
    'net.verdictSansTurn': 'Nessun relay TURN: la connessione può fallire tra reti diverse o se il router isola i suoi dispositivi. Configura un relay qui sotto (Relay di rete); sarà trasmesso ai giocatori tramite il codice QR.',
    'net.verdictStunBloque': 'STUN è bloccato anche se Internet funziona: quasi sempre è il BROWSER a bloccare l’UDP di WebRTC.<br>• <b>Opera / Opera GX</b>: disattiva la VPN integrata, poi nelle impostazioni cerca «WebRTC» e scegli «Usa UDP senza proxy».<br>• Altrimenti: VPN, antivirus o firewall. Prova con Chrome o Edge per confermarlo.<br>• Un relay TURN configurato passa anche da TCP 443 e spesso aggira questo blocco.',
    'net.verdictWebrtcOff': 'WebRTC è completamente disattivato in questo browser (nessun candidato di rete). Controlla le impostazioni sulla privacy del browser o provane un altro.',
    'net.verdictPasDeSignalisation': 'Server di segnalazione irraggiungibile: controlla l’accesso a Internet.',

    'msg.paquetIndisponible': 'Questo mazzo non è più disponibile.',
    'msg.aucunPaquetMode': 'Nessun mazzo di carte per questa modalità. Controlla le impostazioni o il mazzo personale.',
    'msg.aucuneCarteMateriel': 'Nessuna carta disponibile. Controlla di avere il materiale necessario (Impostazioni).',
    'msg.aucuneCarteZone': 'Nessuna carta disponibile per questa zona{etat}.\n\nControlla le quantità e il materiale disponibile nelle Impostazioni.',
    'msg.avecProtection': ' con protezione indossata',
    'msg.sansProtection': ' senza protezione',
    'msg.lienCopie': 'Link d’invito copiato.',
    'msg.codeCopie': 'Codice della partita copiato:',
    'msg.partiePasOuverte': 'La partita non è ancora aperta.',
    'msg.scannerIndisponible': 'Scanner QR non disponibile (libreria non caricata — controlla la connessione a Internet).',
    'msg.peerIndisponible': 'Multigiocatore non disponibile (libreria PeerJS non caricata — controlla la connessione a Internet).',
    'msg.firebaseIndisponible': 'Il multigiocatore Firebase non è disponibile (libreria assente).',
    'msg.droitsOrga': 'Modifica rifiutata: non hai i diritti di organizzatore su questa partita.',
    'msg.devenuCoOrga': 'Sei co-organizzatore: il QG della partita è accessibile dal pulsante multigiocatore, in alto a destra.',
    'msg.gradeRetire': 'Grado admin revocato.',
    'msg.retireDeLaPartie': 'Sei stato rimosso dalla partita.',
    'msg.exclu': 'Sei stato espulso dalla partita.',
    'msg.orgaACloture': 'L’organizzatore ha chiuso la partita.',
    'msg.partieTerminee': 'La partita è finita.',
    'msg.nomPartiePris': 'Una partita ha già questo nome e appartiene a qualcun altro. Scegli un altro nome.',
    'msg.nomPartieDejaPris': 'Questo nome di partita è già in uso (o la vecchia sessione non è ancora scaduta). Aspetta un minuto o cambia nome.',
    'msg.partieIntrouvable': 'Partita non trovata. Controlla il nome con l’organizzatore.',
    'msg.partieIntrouvableHote': 'La partita non si trova. Controlla che l’host non abbia chiuso la sua pagina web o annullato la partita.',
    'msg.partieCloturee': 'Questa partita è chiusa.',
    'msg.erreurPeer': 'Errore PeerJS',
    'msg.repriseImpossible': 'Per ora la partita «{nom}» non può essere ripresa ({raison}). Nuovo tentativo al prossimo ritorno sulla pagina, oppure ricrea la partita con lo stesso nome per ritrovare i tuoi giocatori.',
    'msg.dejaHote': 'Stai già ospitando una partita su questo dispositivo. Esci dalla vecchia partita dalla schermata Host per poterne raggiungere un’altra come giocatore.',
    'msg.indiquezNomPartie': 'Indica il nome della partita o scansiona il codice QR.',
    'msg.indiquezPseudo': 'Indica un nome giocatore: è così che l’organizzatore ti vedrà nella partita.',
    'msg.delaiDepasse': 'Tempo scaduto: il collegamento con l’host non si è stabilito. Controlla che la sua pagina sia aperta, poi lancia «Prova la rete» nel menu multigiocatore: se TURN fallisce, l’host deve configurare un relay («Relay di rete») — sarà trasmesso automaticamente dal suo codice QR.',
    'msg.hoteIntrouvable': 'Connessione impossibile: host non trovato o rete instabile.',
    'msg.connexionImpossible': 'Connessione impossibile.',
    'msg.connexionPerdue': 'Connessione persa. Riprova a unirti alla partita.',
    'msg.connexionPerdueHote': 'Connessione con l’host persa.',
    'msg.reconnexionImpossible': 'Riconnessione impossibile: la partita sembra finita o l’host irraggiungibile.',
    'msg.connecte': 'Connesso alla partita!',
    'msg.pseudoRemplace': 'Questo nome era già preso nella partita. Compari come: {nom}',
    'msg.changementEquipe': 'Cambio di squadra'
},
zone: {
    'Membres': 'Arti',
    'Tête ou Torse': 'Testa o Torso',
    'Torse': 'Torso',
    'Tête': 'Testa',
    'Bras': 'Braccio',
    'Jambe': 'Gamba',
    'Jambes': 'Gambe',
    'Torse et bras': 'Torso e braccio'
},
grav: {
    'DÉCÈS': 'MORTE',
    'Critique': 'Critica',
    'Grave': 'Grave',
    'Légère': 'Lieve',
    'Spécial': 'Speciale'
},
membre: {
    'Bras Gauche': 'Braccio sinistro',
    'Bras Droit': 'Braccio destro',
    'Jambe Gauche': 'Gamba sinistra',
    'Jambe Droite': 'Gamba destra'
},
mat: {
    'Garrot': 'Laccio emostatico',
    'Bandage': 'Bendaggio',
    'Poche de transfusion': 'Sacca di sangue',
    'Attelle': 'Stecca',
    'Morphine': 'Morfina',
    'Épinéphrine': 'Adrenalina',
    'Pansement 3 côtés': 'Medicazione a 3 lati'
},
titre: {
    'DCD': 'MORTO',
    'Inconscient': 'Incosciente',
    'Hémorragie': 'Emorragia',
    'Saignement': 'Sanguinamento',
    'Fracture': 'Frattura',
    'Éraflure': 'Escoriazione',
    'Choc Casque': 'Impatto sull’elmetto',
    'Choc Gilet': 'Impatto sul giubbotto',
    'Plaie soufflante': 'Ferita toracica soffiante',
    'Saignement grave': 'Sanguinamento grave',
    'Prot. Balistique': 'Prot. balistica',
    'Choc Balistique': 'Shock balistico',
    'Impact sur casque': 'Impatto sull’elmetto',
    'Plaie au front': 'Ferita alla fronte',
    'Traumatisme crânien': 'Trauma cranico',
    'Tir à la tête': 'Colpo alla testa',
    'Impact sur plaque': 'Impatto sulla piastra',
    'Éraflure au flanc': 'Escoriazione al fianco',
    'Côtes fracturées': 'Costole fratturate',
    'Pneumothorax': 'Pneumotorace',
    'Hémorragie interne': 'Emorragia interna',
    'Tir vital': 'Colpo vitale',
    'Balle dans l\'avant-bras': 'Proiettile nell’avambraccio',
    'Fracture de l\'avant-bras': 'Frattura dell’avambraccio',
    'Artère brachiale': 'Arteria brachiale',
    'Balle au mollet': 'Proiettile nel polpaccio',
    'Fracture du fémur': 'Frattura del femore',
    'Fracture de la rotule': 'Frattura della rotula',
    'Artère fémorale': 'Arteria femorale',
    'DCD (Blast)': 'MORTO (onda d’urto)',
    'Plaie Soufflante': 'Ferita toracica soffiante',
    'Hémorragie Massive': 'Emorragia massiva',
    'Saignement Grave': 'Sanguinamento grave',
    'Fracture Ouverte': 'Frattura esposta',
    'Éraflure (Éclat)': 'Escoriazione (scheggia)',
    'Souffle (Blast)': 'Onda d’urto',
    'Éraflure au visage': 'Escoriazione al viso',
    'Éclats au bras': 'Schegge nel braccio',
    'Criblage d\'éclats': 'Crivellato di schegge',
    'Souffle d\'explosion': 'Onda d’urto dell’esplosione'
},
soin: {
    'Respawn direct': 'Respawn diretto',
    '30s massage + Poche': '30 s di massaggio + Sacca di sangue',
    'Garrot + Poche': 'Laccio emostatico + Sacca di sangue',
    'Bandage + Poche': 'Bendaggio + Sacca di sangue',
    'Attelle': 'Stecca',
    'Bandage': 'Bendaggio',
    'Si Protégé : Sonné (Médic aide à relever). Sinon : Bandage ([MEMBRE_ALEATOIRE])': 'Se protetto: Stordito (il medico aiuta a rialzarsi). Altrimenti: Bendaggio ([MEMBRE_ALEATOIRE])',
    'Bandage + Massage + Épi + Poche': 'Bendaggio + Massaggio + Adrenalina + Sacca di sangue',
    'Pnsmt 3 côtés + Morphine + Poche': 'Medicazione 3 lati + Morfina + Sacca di sangue',
    'Garrot + Bandage + Morphine + Poche': 'Laccio emostatico + Bendaggio + Morfina + Sacca di sangue',
    'Bandage + Morphine': 'Bendaggio + Morfina',
    'Bandage + Attelle + Morphine': 'Bendaggio + Stecca + Morfina',
    'Tête — protégé : rien, sinon Éraflure (Bandage). Torse — protégé : Hématome (Morphine), sinon Bandage': 'Testa — protetta: niente, altrimenti Escoriazione (Bendaggio). Torso — protetto: Ematoma (Morfina), altrimenti Bendaggio',
    'Protégé : Sonné (le médic aide à relever). Sinon : DCD': 'Protetto: Stordito (il medico aiuta a rialzarsi). Altrimenti: Morto',
    'Repos 2 minutes': 'Riposo di 2 minuti',
    'Bandage + Épinéphrine + Morphine': 'Bendaggio + Adrenalina + Morfina',
    'Repos 1 minute': 'Riposo di 1 minuto',
    'Bandage compressif + Morphine': 'Bendaggio compressivo + Morfina',
    'Pansement 3 côtés + Morphine': 'Medicazione a 3 lati + Morfina',
    'Bandage + Poche de transfusion + Épinéphrine': 'Bendaggio + Sacca di sangue + Adrenalina',
    'Attelle + Bandage': 'Stecca + Bendaggio',
    'Garrot + Bandage + Poche de transfusion': 'Laccio emostatico + Bendaggio + Sacca di sangue',
    'Attelle + Bandage + Morphine': 'Stecca + Bendaggio + Morfina',
    'Attelle + Morphine': 'Stecca + Morfina',
    'Garrot + Poche de transfusion + Épinéphrine': 'Laccio emostatico + Sacca di sangue + Adrenalina',
    'Bandage + 30s Massage + Épi + Poche': 'Bendaggio + 30 s di massaggio + Adrenalina + Sacca di sangue',
    '2x Bandages + Morphine': '2x Bendaggi + Morfina',
    'Garrot + Pansement 3 côtés + Poche de transfusion + Épinéphrine': 'Laccio emostatico + Medicazione a 3 lati + Sacca di sangue + Adrenalina',
    'Casque porté : aucune blessure.\nSinon : Éraflure → Bandage': 'Elmetto indossato: nessuna ferita.\nAltrimenti: Escoriazione → Bendaggio',
    'Gilet porté : Hématome → Morphine.\nSinon : Bandage': 'Giubbotto indossato: Ematoma → Morfina.\nAltrimenti: Bendaggio',
    'Casque porté : Sonné → le médic aide à relever.\nSinon : DCD': 'Elmetto indossato: Stordito → il medico aiuta a rialzarsi.\nAltrimenti: Morto',
    'Gilet porté : Sonné → le médic aide à relever.\nSinon : DCD': 'Giubbotto indossato: Stordito → il medico aiuta a rialzarsi.\nAltrimenti: Morto'
},
bilan: {
    'Impact direct sur le casque lourd.': 'Impatto diretto sull’elmetto pesante.',
    'Plaie ouverte et profonde au front.': 'Ferita aperta e profonda alla fronte.',
    'Traumatisme crânien sévère.': 'Trauma cranico grave.',
    'Tir direct à la tête (sans port du casque).': 'Colpo diretto alla testa (senza elmetto).',
    'Impact encaissé par la plaque balistique du porte-plaques.': 'Impatto assorbito dalla piastra balistica del portapiastre.',
    'Éraflure sur le flanc, hors de la zone couverte par les plaques balistiques.': 'Escoriazione sul fianco, fuori dalla zona coperta dalle piastre balistiche.',
    'Fracture de plusieurs côtes par impact lourd.': 'Frattura di più costole per un impatto violento.',
    'Pneumothorax suite à une balle perforante latérale.': 'Pneumotorace dovuto a un proiettile perforante laterale.',
    'Blessure perforante à l\'abdomen causant une importante hémorragie interne.': 'Ferita perforante all’addome che provoca una forte emorragia interna.',
    'Tir direct au niveau du cœur ou de la colonne vertébrale (sans port de plaques balistiques).': 'Colpo diretto al cuore o alla colonna vertebrale (senza piastre balistiche).',
    'Balle logée dans les tissus mous de l\'avant-bras.': 'Proiettile conficcato nei tessuti molli dell’avambraccio.',
    'Fracture de l\'os de l\'avant-bras (radius / cubitus).': 'Frattura dell’osso dell’avambraccio (radio / ulna).',
    'Sectionnement de l\'artère brachiale.': 'Recisione dell’arteria brachiale.',
    'Balle logée dans le muscle du mollet.': 'Proiettile conficcato nel muscolo del polpaccio.',
    'Fracture du fémur.': 'Frattura del femore.',
    'Fracture de la rotule du genou.': 'Frattura della rotula del ginocchio.',
    'Sectionnement de l\'artère fémorale.': 'Recisione dell’arteria femorale.',
    'Éraflure superficielle due à un éclat sur la joue ou le lobe de l\'oreille.': 'Escoriazione superficiale da scheggia sulla guancia o sul lobo dell’orecchio.',
    'Multiples plaies par éclats de grenade sur le bras.': 'Ferite multiple da schegge di granata sul braccio.',
    'Criblage d\'éclats de shrapnel sur l\'ensemble des deux jambes.': 'Entrambe le gambe crivellate di schegge.',
    'Traumatisme contondant lourd au torse et sectionnement artériel à un bras suite à une explosion à proximité.': 'Trauma contusivo grave al torso e recisione arteriosa a un braccio dopo un’esplosione ravvicinata.'
}
};
