/* BSE MEDICAL SYSTEM — 日本語
   Les tables zone/grav/mat/membre/titre/soin/bilan sont indexees par le
   texte FRANCAIS d'origine, qui reste la cle interne des cartes. */
window.BSE_I18N.ja = {
ui: {
    'hdr.multijoueur': 'マルチプレイ',
    'hdr.quitter': 'ゲームを退出',
    'hdr.sortir': '退出',
    'hdr.paquets': 'マイデッキ',
    'hdr.reglages': '設定',
    'hdr.bseLien': 'Bravo Sierra Events — サイトを開く',
    'hdr.bseAria': 'Bravo Sierra Events のサイトを開く',
    'social.discord': 'Bravo Sierra Events の Discord',
    'social.instagram': 'Bravo Sierra Events の Instagram',
    'social.youtube': 'Bravo Sierra Events の YouTube',
    'social.facebook': 'Bravo Sierra Events の Facebook',
    'statut.solo': 'ソロ',
    'statut.organisateur': '主催者',
    'statut.coadmin': '副管理者',
    'statut.reconnexion': '{nom} · ゲームに再接続中…',
    'paquet.balistique': '弾道',
    'paquet.explosion': '爆発',

    'jeu.titre': 'メディカル診断',
    'jeu.sous': 'タップして診断を開始',
    'jeu.paquetActif': '使用中のデッキ',
    'jeu.chargement': '読み込み中...',
    'jeu.cartes': '{n} 枚',

    'march.titre': 'MARCH 評価',
    'march.m': '大量出血',
    'march.a': '気道',
    'march.r': '呼吸',
    'march.c': '循環',
    'march.h': '頭部 / 低体温',
    'march.analyse': '評価中…',

    'sil.titre': 'どの部位に被弾？',
    'sil.sous': '負傷した部位をタップ',
    'sil.miroir': '（鏡像表示：相手の右腕はあなたの左側）',

    'fiche.mort': '戦死',
    'fiche.mortSous': '時間切れ — 致命的な出血',
    'fiche.fermer': 'カルテを閉じる',
    'fiche.label': 'トリアージ票',
    'fiche.zone': '負傷部位',
    'fiche.bilan': '所見',
    'fiche.protocole': '処置手順',
    'fiche.hemorragie': '出血継続中 — 生命の危機',
    'fiche.nouveau': '新しい診断',
    'fiche.soigner': '処置完了（救命）',
    'fiche.stabilise': '傷病者は安定しました！',
    'fiche.protPortee': '防弾装備の着用：{reponse}',
    'fiche.avecProtection': '（防具あり）',

    'btn.annuler': 'キャンセル',
    'btn.valider': '決定',
    'btn.fermer': '閉じる',
    'btn.retour': '戻る',
    'btn.copier': 'コピー',
    'btn.ouvrir': '開く',
    'btn.oui': 'はい',
    'btn.non': 'いいえ',

    'qg.titre': '司令部',
    'qg.partie': 'ゲーム',
    'qg.enLigne': 'オンライン',
    'qg.ongletInvitation': '招待',
    'qg.ongletJoueurs': 'プレイヤー',
    'qg.ongletEquipes': 'チーム',
    'qg.ongletEditeur': 'エディタ',
    'qg.ongletPaquets': 'デッキ',
    'qg.ongletLogs': 'ログ',
    'qg.codeAide': 'ゲームコード — プレイヤーに読み上げてください',
    'qg.lienAide': '接続リンク（共有または QR）',
    'qg.qrGeneration': '生成中...',
    'qg.qrAide': 'プレイヤーは QR コードを読み取るか、参加メニューにゲーム名を入力します。',
    'qg.joueurs': 'プレイヤー',
    'qg.equipes': 'このゲームのチーム',
    'qg.nomEquipePh': 'チーム名',
    'qg.couleurEquipePh': '#16進カラー',
    'qg.ajouterEquipe': '+ チーム',
    'qg.editeur': 'デッキエディタ',
    'qg.editeurAide': '配布する前に、すべてのデッキの枚数・資材・死亡リスクを調整してください。',
    'qg.paquetsAttribues': '割り当て済みデッキ',
    'qg.paquetsAide1': '各プレイヤーが引くものを選びます：クラシック、アドバンス、エクストリーム、爆発、または自作デッキ。割り当てたデッキは受け取る側のゲームモードを<b>置き換えます</b> — そのプレイヤーはそれだけを、エディタで設定した枚数で引きます。',
    'qg.paquetsAide2': '割り当てのないプレイヤーは、エディタで設定した<b>現在のモード</b>をプレイします。',
    'qg.toutLeMonde': '全員',
    'qg.uneEquipe': '特定のチームのみ',
    'qg.unJoueur': '特定のプレイヤーのみ',
    'qg.ajouterPaquet': 'このデッキを割り当てる',
    'qg.journal': 'リアルタイムログ',
    'qg.journalAide': 'プレイヤーの出来事には、そのチームの名前と色が付きます。',
    'qg.telechargerLogs': 'ログをダウンロード（.txt）',
    'qg.effacerAffichage': '表示を消去',
    'qg.cloturer': 'ゲームを終了（全員を切断）',
    'qg.retourSession': 'ホームに戻る（セッションは維持）',

    'reg.titre': 'システム設定',
    'reg.profil': 'マルチプレイのプロフィール',
    'reg.pseudo': 'あなたのプレイヤー名',
    'reg.pseudoPh': '例：Doc',
    'reg.mode': 'ゲームモード',
    'reg.hardcore': 'ハードコア設定',
    'reg.activerMort': '死亡リスクを有効にする',
    'reg.proba': '確率',
    'reg.probaSous': '対象となる負傷に対して',
    'reg.delaiMin': '最短時間',
    'reg.delaiMinSous': '死亡までの',
    'reg.delaiMax': '最長時間',
    'reg.etendreGraves': '重傷にも適用する',
    'reg.explosion': '爆発',
    'reg.activerExplosion': '爆発カードを有効にする',
    'reg.materiel': '必要な資材',
    'reg.cartesActives': '有効なカード',
    'reg.catalogue': 'カタログ',
    'reg.oeilAide': '各行の目のアイコンで、そのカードの位置からモードのカタログが開きます。',
    'reg.aide': 'ヘルプ',
    'reg.aideTexte': 'ブリーフィングで読む完全版ガイド。一度開けばオフラインでも閲覧できます。',
    'reg.guide': '利用ガイド（PDF）',

    'lang.titre': '言語',
    'lang.choisir': '言語を選択',

    'bld.titre': 'マイデッキ',
    'bld.sous': '自分だけのカードデッキを作り、ホーム画面に表示できます。',
    'bld.creer': '+ デッキを作成',
    'bld.importer': 'デッキをインポート',
    'bld.edition': 'デッキの編集',
    'bld.nom': 'デッキ名',
    'bld.nomPh': '例：化学損傷',
    'bld.afficherAccueil': 'ホーム画面に表示',
    'bld.modeExtreme': 'エクストリームモード',
    'bld.modeExtremeSous': '（人体図：負傷部位 + 防具）',
    'bld.icone': 'ボタンのアイコン',
    'bld.iconeAide': 'ホーム画面と、割り当てたプレイヤーの画面でデッキを見分けるためのものです。',
    'bld.cartes': 'カード',
    'bld.ajouterCarte': '+ カードを追加',
    'bld.enregistrer': '保存',
    'bld.supprimerPaquet': 'デッキを削除',

    'ce.titreEcran': 'カード',
    'ce.gravite': '重症度',
    'ce.titre': 'タイトル',
    'ce.titrePh': '例：骨折',
    'ce.zone': '負傷部位',
    'ce.zonePh': '例：腕',
    'zoneOpt.tete': '頭部',
    'zoneOpt.torse': '胴体',
    'zoneOpt.teteTorse': '頭部または胴体',
    'zoneOpt.brasD': '右腕',
    'zoneOpt.brasG': '左腕',
    'zoneOpt.bras': '両腕',
    'zoneOpt.jambeD': '右脚',
    'zoneOpt.jambeG': '左脚',
    'zoneOpt.jambes': '両脚',
    'zoneOpt.membres': '四肢すべて',
    'zoneOpt.libre': 'カスタム部位…',
    'zoneOpt.aideGroupe': 'カードは1枚で足ります：正確な部位は抽選で決まり、エクストリームモードでは人体図で選んだ部位になります。',
    'zoneOpt.aideLibre': '好きな部位を書けます。そのまま表示され、エクストリームモードではどの部位でも出ます。',
    'ce.protection': '防弾装備',
    'prot.peuImporte': 'どちらでも',
    'prot.avec': '防具あり',
    'prot.sans': '防具なし',
    'prot.aide': 'エクストリームモードでのみ、しかも頭部と胴体にだけ効きます。ヘルメットやベストを尋ねるのはそこだからです。四肢の場合、このカードはどちらでも出ます。',
    'ce.protocole': '手順 / 効果',
    'ce.protocolePh': '例：副木 + モルヒネ',
    'ce.matos': '必要な資材',
    'ce.matosAide': 'タグをタップして選択します。ここで追加した資材は、このデッキ内でのみ表示されます（✕ で削除）。',
    'ce.nouveauMatosPh': '新しい資材（例：抗放射線剤）',
    'ce.valider': 'カードを確定',

    'mod.apercu': 'プレビュー',
    'multi.titre': 'マルチプレイメニュー',
    'multi.nomPartie': 'ゲーム名（ホスト）',
    'multi.nomPartiePh': '例：演習アルファ',
    'multi.pseudoHote': 'ホスト名',
    'multi.pseudoHotePh': '例：Orga',
    'multi.liaison': '端末間の接続',
    'multi.firebase': 'Firebase サーバー（推奨）',
    'multi.peer': 'ピアツーピア（旧方式）',
    'multi.aideFirebase': 'サーバー経由：異なるネットワーク間（4G / WiFi）でも動作し、ページを閉じてもゲームは切れません。',
    'multi.aidePeer': '端末どうしの直接接続。多くの場合 TURN リレーが必要で、ページを開いたままにする必要があります。',
    'multi.creer': 'ゲームを作成（ホスト）',
    'multi.rejoindre': 'ゲームに参加',
    'multi.scanner': 'QR コードを読み取る',
    'multi.codePh': 'ゲーム名またはリンク',
    'multi.connexion': '接続',
    'multi.testerReseau': 'ネットワークをテスト',
    'multi.turn': 'ネットワークリレー（TURN）— 任意',
    'multi.turnAide': 'テストで ❌ TURN と表示され、プレイヤーが別のネットワーク（4G、別の WiFi）にいる場合に必要です。<b>metered.ca</b> で無料アカウント（月 50 GB）を作り、「TURN server」を追加して、その認証情報をここに貼り付けてください。招待リンク / QR コードで自動的にプレイヤーへ渡されます。',
    'multi.turnUrlPh': 'URL（例：turn:standard.relay.metered.ca:443）',
    'multi.turnUserPh': 'ユーザー名',
    'multi.turnPassPh': 'パスワード / 認証情報',
    'multi.turnSave': 'リレーを保存',
    'multi.statut': '接続中...',

    'join.titre': 'ゲームに参加',
    'join.etabli': '接続しました。',
    'join.pseudo': 'あなたのプレイヤー名',
    'join.equipe': 'あなたのチーム',

    'prot.question': '防弾装備を着用していますか？',
    'prot.casque': '防弾ヘルメットを着用していますか？',
    'prot.gilet': '防弾ベストを着用していますか？',

    'share.titre': 'デッキを共有',

    'leave.titre': 'ゲームを退出しますか？',
    'leave.texte': 'マルチプレイのセッションを抜けて、メインメニューに戻ります。',
    'leave.oui': 'はい、退出する',

    'mode.classique': 'クラシック',
    'mode.avance': 'アドバンス',
    'mode.extreme': 'エクストリーム',
    'mode.explosion': '爆発',
    'mode.perso': 'カスタム',
    'mode.plusExplosion': ' + 爆発',
    'reg.modeClassique': 'クラシック',
    'reg.modeAvance': 'アドバンス',
    'reg.modeExtreme': 'エクストリーム（人体図）',
    'reg.custom': '{nom}（カスタム）',
    'reg.aucunMateriel': 'このモードまたはこの選択では資材は不要です。',
    'reg.voirCarte': 'カードを見る',
    'reg.packExplosion': '爆発パック',
    'reg.verrouille': '設定はホストによりロックされています',

    'cat.titre': 'カタログ — {mode}',
    'cat.sectionMode': 'モード',
    'cat.sectionPerso': 'カスタムデッキ',
    'cat.sectionExplosion': '爆発',
    'cat.protPortee': '防具あり',
    'cat.sansProt': '防具なし',
    'cat.matos': '資材：',
    'cat.aucuneCarte': 'このモードにカードはありません。',
    'carte.membreAleatoire': 'ランダムな四肢',

    'btn.modifier': '編集',
    'btn.partager': '共有',
    'btn.supprimer': '削除',

    'bld.nouveauPaquet': '新しいデッキ',
    'bld.sansNom': '名称未設定のデッキ',
    'bld.sansTitre': 'タイトルなし',
    'bld.masque': '非表示',
    'bld.surAccueil': 'ホーム画面に表示中',
    'bld.aucunPaquet': 'カスタムデッキはまだありません。',
    'bld.aucunPaquetAide': '「+ デッキを作成」を押して始めましょう。',
    'bld.aucuneCarte': 'このデッキにカードがありません。',
    'bld.aucuneCarteAide': '「+ カードを追加」を押してください。',
    'bld.nMateriel': '資材 {n} 点',
    'bld.enPartieTitre': 'ゲーム進行中。',
    'bld.enPartieTexte': '主催者が割り当てたデッキをプレイ中です。あなた自身のデッキは一時的に預けられ、ゲームを退出すればすぐに戻ります。',
    'bld.bloqueEnPartie': 'ゲーム中は操作できません：設定は主催者から届いており、あなたのデッキが消えてしまいます。\n\nゲームを退出すると、自分のデッキを取り戻して編集できます。',
    'bld.confirmSupprCarte': 'カード「{nom}」を削除しますか？',
    'bld.confirmSupprPaquet': 'デッキ「{nom}」とそのカードをすべて削除しますか？',
    'ce.donnezTitre': 'カードにタイトルを付けてください。',
    'ce.confirmRetirerMatos': 'このデッキから「{nom}」を外しますか？ それを使っているカードからも外れます。',

    'share.exportTitre': '「{nom}」を共有',
    'share.exportAide': 'このコードを他のプレイヤーに送ってください（SMS、WhatsApp、メールなど）。相手は「マイデッキ」の「デッキをインポート」から取り込みます。',
    'share.copierCode': 'コードをコピー',
    'share.importAide': '受け取った共有コードをここに貼り付けてください（TMDECK1 で始まります）。',
    'share.importer': 'インポート',
    'share.codeCopie': 'コードをコピーしました！',
    'share.codeInvalide': 'コードが無効または不完全です。全体がコピーされているか確認してください。',
    'share.paquetImporte': 'インポートしたデッキ',
    'share.importeOk': 'デッキ「{nom}」をインポートしました（{n} 枚）！',

    'icone.cartes': 'カード',
    'icone.blesse': '負傷者',
    'icone.souffle': '爆風',
    'icone.balle': '弾丸',
    'icone.reticule': '照準',
    'icone.lame': '刃物',
    'icone.grenade': '手榴弾',
    'icone.bombe': '爆弾',
    'icone.explosion': '爆発',
    'icone.feu': '火',
    'icone.decharge': '電撃',
    'icone.froid': '低温',
    'icone.biohazard': 'バイオハザード',
    'icone.radiation': '放射線',
    'icone.toxique': '毒物',
    'icone.masqueGaz': 'ガスマスク',
    'icone.zombie': 'ゾンビ',
    'icone.creature': 'クリーチャー',
    'icone.robot': 'ロボット',
    'icone.crane': 'ドクロ',
    'icone.seringue': '注射器',
    'icone.cachets': '錠剤',
    'icone.perfusion': '点滴',
    'icone.pouls': '脈拍',
    'icone.fracture': '骨折',
    'icone.trousse': '救急キット',
    'icone.protection': '防具',

    'qg.ligneMode': 'モード：{nom}',
    'qg.lignePerso': 'カスタム：{nom}',
    'qg.joue': '使用中',
    'qg.minEquipes': '（最低 2 チーム）',
    'qg.horsLigne': 'オフライン',
    'qg.reviendra': '自動的に戻ります…',
    'qg.retirer': '外す',
    'qg.admin': '管理者',
    'qg.kick': 'キック',
    'qg.retirerPaquet': 'このデッキを外す',
    'qg.cibleEquipe': 'チーム {nom}',
    'qg.cibleJoueur': 'プレイヤー {nom}',
    'qg.aucunPaquetDistribue': '割り当てたデッキはありません。',
    'qg.aucunPaquetDistribueAide': 'プレイヤーは「弾道」の抽選のみ行えます。',
    'qg.paquetVide': '現在の設定では、このデッキは空です。',
    'qg.dejaAttribueCible': '「{nom}」はこの対象にすでに割り当て済みです。',
    'qg.dejaAttribueTous': '「{nom}」はすでに全員に割り当て済みです。チームや個人に再度渡す必要はありません。',
    'qg.indiquezNomEquipe': 'チーム名を入力してください。',
    'qg.deuxEquipesMini': 'チームは最低 2 つ必要です。',
    'qg.choisirEquipe': 'チームを選んでください。',
    'qg.choisirJoueur': '（接続中の）プレイヤーを選んでください。',
    'qg.aucunLog': 'ダウンロードできるログがありません。',
    'qg.logEntete': 'ゲームログ',
    'qg.logExporte': 'エクスポート日時',
    'qg.confirmCloture': 'ゲームを終了しますか？ 全プレイヤーに通知され、切断されます。',
    'qg.confirmClotureTous': '全員のゲームを終了しますか？',
    'qg.qrIndisponible': 'QR を表示できません。',
    'qg.qrIndisponibleAide': 'リンクかゲーム名を共有してください。',
    'qg.qrAlt': '招待用 QR コード',

    'log.partieOuverte': 'ゲーム開始：{code}',
    'log.aRejoint': '{nom} が参加しました',
    'log.sEstReconnecte': '{nom} が再接続しました',
    'log.quitteLaPartie': '{nom} がゲームを退出しました',
    'log.joueurDeconnecte': '{nom} が切断（再接続待ち）',
    'log.pseudoDejaPris': '名前「{demande}」は使用済み：このプレイヤーは「{retenu}」になります',
    'log.sessionDemarree': 'ホストセッション開始：{code}',
    'log.sessionReprise': 'セッション再開：{code}',
    'log.configModifiee': '{nom}（副管理者）が設定を変更しました',
    'log.ajoutRefuse': '割り当てを拒否（{nom}）：{raison}',
    'log.tirage': '{nom} · 抽選：{carte}［{gravite}］· {source}',
    'log.coadmin': '{nom} · 副管理者：{valeur}',
    'log.retireDeLaPartie': 'ゲームから除外：{nom}',
    'log.partieCloturee': 'ゲームを終了しました。',
    'log.partieClotureePar': '{nom}（副管理者）がゲームを終了しました。',
    'qg.logEquipeAjoutee': 'チームを追加：{nom}',
    'qg.logEquipeSupprimee': 'チームを削除し、プレイヤーを再割り当てしました。',
    'qg.logPaquetDistribue': 'デッキを割り当て：{nom} → {cible}',
    'qg.logRemplaceParTous': '{nom}：{n} 件の個別割り当てを「全員」に置き換えました',

    'multi.joueur': 'プレイヤー',
    'multi.orga': 'Orga',
    'multi.ouverture': 'ゲームを開いています...',
    'multi.ouvertureImpossible': '開けませんでした。',
    'multi.creation': 'ゲームを作成しています...',
    'multi.reprise': 'ゲームを再開しています...',
    'multi.recherche': 'ゲームを探しています...',
    'multi.connexionReseau': 'ネットワークに接続中...',
    'multi.recuperation': 'データを取得しています...',
    'join.partieNommee': 'ゲーム「{nom}」',

    'net.testEnCours': 'テスト中（約 15 秒）...',
    'net.ligneSignalisation': 'シグナリング（PeerJS サーバー）',
    'net.ligneStun': 'STUN — 直接接続が可能',
    'net.ligneTurn': 'TURN — 直接接続が塞がれた場合のリレー',
    'net.aucunRelais': '（リレー未設定）',
    'net.relaisEnregistre': 'リレーを保存しました。次回以降の接続で使われ、リンク / QR コードでプレイヤーにも渡されます。',
    'net.relaisEfface': 'リレーを削除しました。',
    'net.verdictOk': 'すべて正常です：異なるネットワーク間（4G ↔ ルーター）でも接続できるはずです。',
    'net.verdictSansTurn': 'TURN リレーがありません：ネットワークが異なる場合や、ルーターが端末を分離している場合に接続が失敗することがあります。下の「ネットワークリレー」でリレーを設定してください。QR コードでプレイヤーに渡されます。',
    'net.verdictStunBloque': 'インターネットは使えるのに STUN が塞がれています：ほとんどの場合、ブラウザが WebRTC の UDP を遮断しています。<br>• <b>Opera / Opera GX</b>：内蔵 VPN をオフにし、設定で「WebRTC」を探して「プロキシを使わずに UDP を使用」を選んでください。<br>• それ以外：VPN、ウイルス対策、ファイアウォール。Chrome や Edge で試して確認してください。<br>• 設定済みの TURN リレーは TCP 443 も通るため、この遮断を回避できることが多いです。',
    'net.verdictWebrtcOff': 'このブラウザでは WebRTC が完全に無効です（ネットワーク候補がゼロ）。ブラウザのプライバシー設定を確認するか、別のブラウザをお試しください。',
    'net.verdictPasDeSignalisation': 'シグナリングサーバーに接続できません：インターネット接続を確認してください。',

    'msg.paquetIndisponible': 'このデッキはもう利用できません。',
    'msg.aucunPaquetMode': 'このモードにはデッキがありません。設定またはカスタムデッキを確認してください。',
    'msg.aucuneCarteMateriel': '利用できるカードがありません。必要な資材があるか確認してください（設定）。',
    'msg.aucuneCarteZone': 'この部位{etat}に該当するカードがありません。\n\n設定で枚数と利用可能な資材を確認してください。',
    'msg.avecProtection': '（防具あり）',
    'msg.sansProtection': '（防具なし）',
    'msg.lienCopie': '招待リンクをコピーしました。',
    'msg.codeCopie': 'ゲームコードをコピーしました：',
    'msg.partiePasOuverte': 'ゲームはまだ開始されていません。',
    'msg.scannerIndisponible': 'QR スキャナーを利用できません（ライブラリ未読み込み — インターネット接続を確認してください）。',
    'msg.peerIndisponible': 'マルチプレイを利用できません（PeerJS ライブラリ未読み込み — インターネット接続を確認してください）。',
    'msg.firebaseIndisponible': 'Firebase のマルチプレイを利用できません（ライブラリがありません）。',
    'msg.droitsOrga': '変更を拒否しました：このゲームの主催者権限がありません。',
    'msg.devenuCoOrga': 'あなたは副主催者になりました：右上のマルチプレイボタンからゲーム司令部を開けます。',
    'msg.gradeRetire': '管理者権限が解除されました。',
    'msg.retireDeLaPartie': 'あなたはゲームから外されました。',
    'msg.exclu': 'あなたはゲームからキックされました。',
    'msg.orgaACloture': '主催者がゲームを終了しました。',
    'msg.partieTerminee': 'ゲームは終了しました。',
    'msg.nomPartiePris': '同じ名前のゲームがすでにあり、別の人のものです。別の名前を選んでください。',
    'msg.nomPartieDejaPris': 'このゲーム名はすでに使われています（または前のセッションがまだ期限切れになっていません）。1 分ほど待つか、名前を変えてください。',
    'msg.partieIntrouvable': 'ゲームが見つかりません。主催者に名前を確認してください。',
    'msg.partieIntrouvableHote': 'ゲームが見つかりません。ホストがページを閉じたり、ゲームを取り消したりしていないか確認してください。',
    'msg.partieCloturee': 'このゲームは終了しています。',
    'msg.erreurPeer': 'PeerJS エラー',
    'msg.repriseImpossible': 'ゲーム「{nom}」は今は再開できません（{raison}）。次にこのページへ戻ったときに再試行されます。同じ名前でゲームを作り直せばプレイヤーも戻ります。',
    'msg.dejaHote': 'この端末ではすでにゲームをホストしています。プレイヤーとして別のゲームに参加するには、ホスト画面から前のゲームを退出してください。',
    'msg.indiquezNomPartie': 'ゲーム名を入力するか、QR コードを読み取ってください。',
    'msg.indiquezPseudo': 'プレイヤー名を入力してください：主催者にはこの名前で表示されます。',
    'msg.delaiDepasse': 'タイムアウト：ホストとの接続を確立できませんでした。相手のページが開いているか確認し、マルチプレイメニューで「ネットワークをテスト」を実行してください。TURN が失敗する場合、ホストがリレー（「ネットワークリレー」）を設定する必要があります — QR コードで自動的に共有されます。',
    'msg.hoteIntrouvable': '接続できません：ホストが見つからないか、ネットワークが不安定です。',
    'msg.connexionImpossible': '接続できません。',
    'msg.connexionPerdue': '接続が切れました。もう一度ゲームに参加してください。',
    'msg.connexionPerdueHote': 'ホストとの接続が切れました。',
    'msg.reconnexionImpossible': '再接続できません：ゲームが終了したか、ホストに到達できません。',
    'msg.connecte': 'ゲームに接続しました！',
    'msg.pseudoRemplace': 'その名前はゲーム内ですでに使われていました。あなたは次の名前で表示されます：{nom}',
    'msg.changementEquipe': 'チーム変更'
},
zone: {
    'Membres': '四肢',
    'Tête ou Torse': '頭部または胴体',
    'Torse': '胴体',
    'Tête': '頭部',
    'Bras': '腕',
    'Jambe': '脚',
    'Jambes': '両脚',
    'Torse et bras': '胴体と腕'
},
grav: {
    'DÉCÈS': '死亡',
    'Critique': '重篤',
    'Grave': '重傷',
    'Légère': '軽傷',
    'Spécial': '特殊'
},
membre: {
    'Bras Gauche': '左腕',
    'Bras Droit': '右腕',
    'Jambe Gauche': '左脚',
    'Jambe Droite': '右脚'
},
mat: {
    'Garrot': '止血帯',
    'Bandage': '包帯',
    'Poche de transfusion': '輸血パック',
    'Attelle': '副木',
    'Morphine': 'モルヒネ',
    'Épinéphrine': 'アドレナリン',
    'Pansement 3 côtés': '三辺テーピング'
},
titre: {
    'DCD': '戦死',
    'Inconscient': '意識不明',
    'Hémorragie': '大出血',
    'Saignement': '出血',
    'Fracture': '骨折',
    'Éraflure': 'かすり傷',
    'Choc Casque': 'ヘルメット被弾',
    'Choc Gilet': 'ベスト被弾',
    'Plaie soufflante': '開放性気胸',
    'Saignement grave': '重度の出血',
    'Prot. Balistique': '防弾装備',
    'Choc Balistique': '弾道衝撃',
    'Impact sur casque': 'ヘルメットへの着弾',
    'Plaie au front': '前額部の裂傷',
    'Traumatisme crânien': '頭部外傷',
    'Tir à la tête': 'ヘッドショット',
    'Impact sur plaque': 'プレートへの着弾',
    'Éraflure au flanc': '脇腹のかすり傷',
    'Côtes fracturées': '肋骨骨折',
    'Pneumothorax': '気胸',
    'Hémorragie interne': '内出血',
    'Tir vital': '致命部位への被弾',
    'Balle dans l\'avant-bras': '前腕への被弾',
    'Fracture de l\'avant-bras': '前腕骨折',
    'Artère brachiale': '上腕動脈',
    'Balle au mollet': 'ふくらはぎへの被弾',
    'Fracture du fémur': '大腿骨骨折',
    'Fracture de la rotule': '膝蓋骨骨折',
    'Artère fémorale': '大腿動脈',
    'DCD (Blast)': '戦死（爆風）',
    'Plaie Soufflante': '開放性気胸',
    'Hémorragie Massive': '大量出血',
    'Saignement Grave': '重度の出血',
    'Fracture Ouverte': '開放骨折',
    'Éraflure (Éclat)': 'かすり傷（破片）',
    'Souffle (Blast)': '爆風',
    'Éraflure au visage': '顔面のかすり傷',
    'Éclats au bras': '腕の破片創',
    'Criblage d\'éclats': '多数の破片創',
    'Souffle d\'explosion': '爆発の爆風'
},
soin: {
    'Respawn direct': '即リスポーン',
    '30s massage + Poche': '心臓マッサージ 30 秒 + 輸血パック',
    'Garrot + Poche': '止血帯 + 輸血パック',
    'Bandage + Poche': '包帯 + 輸血パック',
    'Attelle': '副木',
    'Bandage': '包帯',
    'Si Protégé : Sonné (Médic aide à relever). Sinon : Bandage ([MEMBRE_ALEATOIRE])': '防具あり：意識朦朧（衛生兵が起こす）。なし：包帯（[MEMBRE_ALEATOIRE]）',
    'Bandage + Massage + Épi + Poche': '包帯 + 心臓マッサージ + アドレナリン + 輸血パック',
    'Pnsmt 3 côtés + Morphine + Poche': '三辺テーピング + モルヒネ + 輸血パック',
    'Garrot + Bandage + Morphine + Poche': '止血帯 + 包帯 + モルヒネ + 輸血パック',
    'Bandage + Morphine': '包帯 + モルヒネ',
    'Bandage + Attelle + Morphine': '包帯 + 副木 + モルヒネ',
    'Tête — protégé : rien, sinon Éraflure (Bandage). Torse — protégé : Hématome (Morphine), sinon Bandage': '頭部 — 防具あり：無傷、なし：かすり傷（包帯）。胴体 — 防具あり：血腫（モルヒネ）、なし：包帯',
    'Protégé : Sonné (le médic aide à relever). Sinon : DCD': '防具あり：意識朦朧（衛生兵が起こす）。なし：戦死',
    'Repos 2 minutes': '2 分間の安静',
    'Bandage + Épinéphrine + Morphine': '包帯 + アドレナリン + モルヒネ',
    'Repos 1 minute': '1 分間の安静',
    'Bandage compressif + Morphine': '圧迫包帯 + モルヒネ',
    'Pansement 3 côtés + Morphine': '三辺テーピング + モルヒネ',
    'Bandage + Poche de transfusion + Épinéphrine': '包帯 + 輸血パック + アドレナリン',
    'Attelle + Bandage': '副木 + 包帯',
    'Garrot + Bandage + Poche de transfusion': '止血帯 + 包帯 + 輸血パック',
    'Attelle + Bandage + Morphine': '副木 + 包帯 + モルヒネ',
    'Attelle + Morphine': '副木 + モルヒネ',
    'Garrot + Poche de transfusion + Épinéphrine': '止血帯 + 輸血パック + アドレナリン',
    'Bandage + 30s Massage + Épi + Poche': '包帯 + 心臓マッサージ 30 秒 + アドレナリン + 輸血パック',
    '2x Bandages + Morphine': '包帯 ×2 + モルヒネ',
    'Garrot + Pansement 3 côtés + Poche de transfusion + Épinéphrine': '止血帯 + 三辺テーピング + 輸血パック + アドレナリン',
    'Casque porté : aucune blessure.\nSinon : Éraflure → Bandage': 'ヘルメット着用：無傷。\nなし：かすり傷 → 包帯',
    'Gilet porté : Hématome → Morphine.\nSinon : Bandage': 'ベスト着用：血腫 → モルヒネ。\nなし：包帯',
    'Casque porté : Sonné → le médic aide à relever.\nSinon : DCD': 'ヘルメット着用：意識朦朧 → 衛生兵が起こす。\nなし：戦死',
    'Gilet porté : Sonné → le médic aide à relever.\nSinon : DCD': 'ベスト着用：意識朦朧 → 衛生兵が起こす。\nなし：戦死'
},
bilan: {
    'Impact direct sur le casque lourd.': '重装ヘルメットへの直撃。',
    'Plaie ouverte et profonde au front.': '前額部の深い開放創。',
    'Traumatisme crânien sévère.': '重度の頭部外傷。',
    'Tir direct à la tête (sans port du casque).': '頭部への直撃（ヘルメット非着用）。',
    'Impact encaissé par la plaque balistique du porte-plaques.': 'プレートキャリアの防弾プレートが着弾を受け止めた。',
    'Éraflure sur le flanc, hors de la zone couverte par les plaques balistiques.': '防弾プレートの覆う範囲の外、脇腹のかすり傷。',
    'Fracture de plusieurs côtes par impact lourd.': '強い衝撃による複数の肋骨骨折。',
    'Pneumothorax suite à une balle perforante latérale.': '側方からの貫通弾による気胸。',
    'Blessure perforante à l\'abdomen causant une importante hémorragie interne.': '腹部の貫通創により大量の内出血。',
    'Tir direct au niveau du cœur ou de la colonne vertébrale (sans port de plaques balistiques).': '心臓または脊椎への直撃（防弾プレート非着用）。',
    'Balle logée dans les tissus mous de l\'avant-bras.': '前腕の軟部組織に弾が残留。',
    'Fracture de l\'os de l\'avant-bras (radius / cubitus).': '前腕骨（橈骨 / 尺骨）の骨折。',
    'Sectionnement de l\'artère brachiale.': '上腕動脈の切断。',
    'Balle logée dans le muscle du mollet.': 'ふくらはぎの筋肉に弾が残留。',
    'Fracture du fémur.': '大腿骨の骨折。',
    'Fracture de la rotule du genou.': '膝の膝蓋骨骨折。',
    'Sectionnement de l\'artère fémorale.': '大腿動脈の切断。',
    'Éraflure superficielle due à un éclat sur la joue ou le lobe de l\'oreille.': '頬または耳たぶに破片が当たってできた浅いかすり傷。',
    'Multiples plaies par éclats de grenade sur le bras.': '腕に手榴弾の破片による多数の創傷。',
    'Criblage d\'éclats de shrapnel sur l\'ensemble des deux jambes.': '両脚全体に多数の破片創。',
    'Traumatisme contondant lourd au torse et sectionnement artériel à un bras suite à une explosion à proximité.': '至近距離の爆発による胴体の重度鈍的外傷と、片腕の動脈切断。'
}
};
